/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kadjust_array1[] =
{
	MAKE_STRING(95, "The \'array\' argument given to ADJUST-ARRAY, ~A,\n                     isn\'t an adjustable array."),	/* 0 */
	MAKE_STRING(116, "The \'new-dimensions\' argument given to ADJUST-ARRAY, ~A, ~\n              is not the same rank as the argument array."),	/* 2 */
	MAKE_STRING(127, "The \'element-type\' argument to ADJUST-ARRAY, ~A ~\n                  is inconsistent with that of the array to be adjusted [~A]."),	/* 4 */
	MAKE_STRING(107, "A :fill-pointer argument was given to ADJUST-ARRAY, ~\n   \t\t but the array being adjusted, doesn\'t have one."),	/* 6 */
	MAKE_STRING(23, "internal displace-error"),	/* 8 */
};

static void Z56_dim_to_skips(CL_FORM *base);
static void Z57_rmi_copy(CL_FORM *base, CL_FORM *display[]);

void adjust_array1(CL_FORM *base)
{
	CL_FORM *display[1];
	COPY(ARG(0), ARG(11));
	if(CL_SMVECP(ARG(11)))
	{
		rt_plain_vector_element_code(ARG(11));
	}
	else
	{
		COPY(ARG(11), ARG(12));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(13));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(12));
		if(CL_TRUEP(ARG(12)))
		{
			COPY(ARG(11), ARG(12));
			M1_1:;
			COPY(ARG(12), ARG(13));
			COPY(ARG(13), ARG(14));
			COPY(ARG(14), ARG(15));
			LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(16));	/* COMPLEX-BASE-ARRAY */
			rt_struct_typep(ARG(15));
			if(CL_TRUEP(ARG(15)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 0 + 1), ARG(12));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(12));	/* NO_STRUCT */
				COPY(ARG(14), ARG(13));
				LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(14));	/* COMPLEX-BASE-ARRAY */
				Ferror(ARG(12), 3);
			}
			if(CL_SMVECP(ARG(12)))
			{
			}
			else
			{
				goto M1_1;
			}
			goto RETURN1;
			RETURN1:;
			rt_plain_vector_element_code(ARG(12));
			COPY(ARG(12), ARG(11));
		}
		else
		{
			COPY(SYMVAL(Slisp, 152), ARG(12));	/* NO_ARRAY */
			COPY(ARG(11), ARG(13));
			Ferror(ARG(12), 2);
		}
	}
	to_element_type(ARG(11));
	COPY(ARG(0), ARG(12));
	Farray_dimensions(ARG(12));
	LOAD_NIL(ARG(13));
	COPY(ARG(0), ARG(14));
	Fadjustable_array_p(ARG(14));
	if(CL_TRUEP(ARG(14)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kadjust_array1[0], ARG(14));	/* The 'array' argument given to ADJUST-ARRAY, ~A,
                     isn't an adjustable array. */
		COPY(ARG(0), ARG(15));
		Ferror(ARG(14), 2);
	}
	if(CL_ATOMP(ARG(1)))
	{
		COPY(ARG(1), ARG(14));
		Flist(ARG(14), 1);
		COPY(ARG(14), ARG(1));
	}
	COPY(ARG(1), ARG(14));
	Flength(ARG(14));
	COPY(ARG(0), ARG(15));
	Farray_rank(ARG(15));
	Fnumneql(ARG(14), 2);
	if(CL_TRUEP(ARG(14)))
	{
		LOAD_SMSTR((CL_FORM *)&Kadjust_array1[2], ARG(14));	/* The 'new-dimensions' argument given to ADJUST-ARRAY, ~A, ~
              is not the same rank as the argument array. */
		COPY(ARG(1), ARG(15));
		Ferror(ARG(14), 2);
	}
	if(CL_TRUEP(ARG(9)))
	{
		COPY(ARG(2), ARG(14));
		Fupgraded_array_element_type(ARG(14));
		COPY(ARG(14), ARG(2));
		if(EQ(ARG(2), ARG(11)))
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Kadjust_array1[4], ARG(14));	/* The 'element-type' argument to ADJUST-ARRAY, ~A ~
                  is inconsistent with that of the array to be adjusted [~A]. */
			COPY(ARG(2), ARG(15));
			COPY(ARG(11), ARG(16));
			Ferror(ARG(14), 3);
		}
	}
	if(CL_TRUEP(ARG(10)))
	{
		COPY(ARG(0), ARG(14));
		Farray_has_fill_pointer_p(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Kadjust_array1[6], ARG(14));	/* A :fill-pointer argument was given to ADJUST-ARRAY, ~
   		 but the array being adjusted, doesn't have one. */
			Ferror(ARG(14), 1);
		}
		if(CL_TRUEP(ARG(5)))
		{
		}
		else
		{
			COPY(ARG(0), ARG(14));
			COPY(ARG(14), ARG(15));
			Farray_has_fill_pointer_p(ARG(15));
			if(CL_TRUEP(ARG(15)))
			{
			}
			else
			{
				COPY(SYMVAL(Slisp, 154), ARG(15));	/* NO_FILL_PTR */
				COPY(ARG(14), ARG(16));
				Ferror(ARG(15), 2);
			}
			COPY(ARG(14), ARG(15));
			COPY(ARG(15), ARG(16));
			COPY(ARG(16), ARG(17));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(17));
			if(CL_TRUEP(ARG(17)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(16))), 3 + 1), ARG(5));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(17));	/* NO_STRUCT */
				COPY(ARG(16), ARG(18));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
				Ferror(ARG(17), 3);
			}
		}
	}
	else
	{
		COPY(ARG(0), ARG(14));
		Farray_has_fill_pointer_p(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(0), ARG(14));
			COPY(ARG(14), ARG(15));
			Farray_has_fill_pointer_p(ARG(15));
			if(CL_TRUEP(ARG(15)))
			{
			}
			else
			{
				COPY(SYMVAL(Slisp, 154), ARG(15));	/* NO_FILL_PTR */
				COPY(ARG(14), ARG(16));
				Ferror(ARG(15), 2);
			}
			COPY(ARG(14), ARG(15));
			COPY(ARG(15), ARG(16));
			COPY(ARG(16), ARG(17));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(17));
			if(CL_TRUEP(ARG(17)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(16))), 3 + 1), ARG(5));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(17));	/* NO_STRUCT */
				COPY(ARG(16), ARG(18));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(19));	/* COMPLEX-VECTOR */
				Ferror(ARG(17), 3);
			}
		}
	}
	LOAD_GLOBFUN(&CFmake_array, ARG(13));
	COPY(ARG(1), ARG(14));
	LOAD_SYMBOL(SYMBOL(Slisp, 99), ARG(15));	/* ELEMENT-TYPE */
	COPY(ARG(11), ARG(16));
	LOAD_SYMBOL(SYMBOL(Slisp, 100), ARG(17));	/* ADJUSTABLE */
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(18));	/* T */
	LOAD_SYMBOL(SYMBOL(Slisp, 101), ARG(19));	/* FILL-POINTER */
	COPY(ARG(5), ARG(20));
	COPY(ARG(8), ARG(21));
	Fapply(ARG(13), 9);
	mv_count = 1;
	if(CL_TRUEP(ARG(4)))
	{
	}
	else
	{
		LOAD_GLOBFUN(&CFmin, ARG(14));
		COPY(ARG(1), ARG(15));
		COPY(ARG(12), ARG(16));
		Fmapcar(ARG(14), 3);
		COPY(ARG(1), ARG(15));
		Z56_dim_to_skips(ARG(15));
		if(CL_CONSP(ARG(15)))
		{
			COPY(GET_CDR(ARG(15)), ARG(15));
		}
		else
		{
			if(CL_TRUEP(ARG(15)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(16));	/* ~a is not a list */
				COPY(ARG(15), ARG(17));
				Ferror(ARG(16), 2);
			}
			else
			{
			}
		}
		COPY(ARG(12), ARG(16));
		Z56_dim_to_skips(ARG(16));
		if(CL_CONSP(ARG(16)))
		{
			COPY(GET_CDR(ARG(16)), ARG(16));
		}
		else
		{
			if(CL_TRUEP(ARG(16)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(17));	/* ~a is not a list */
				COPY(ARG(16), ARG(18));
				Ferror(ARG(17), 2);
			}
			else
			{
			}
		}
		LOAD_FIXNUM(ARG(17), 0, ARG(17));
		LOAD_FIXNUM(ARG(18), 0, ARG(18));
		display[0] = ARG(0);
		Z57_rmi_copy(ARG(14), display);
	}
	COPY(ARG(0), ARG(14));
	LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
	rt_struct_typep(ARG(14));
	if(CL_TRUEP(ARG(14)))
	{
		COPY(ARG(13), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 0 + 1), ARG(14));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
			COPY(ARG(13), ARG(15));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
			Ferror(ARG(14), 3);
		}
		LOAD_FIXNUM(ARG(15), 0, ARG(15));
		COPY(ARG(0), ARG(16));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(16));
		if(CL_TRUEP(ARG(16)))
		{
			COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 0 + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
			COPY(ARG(0), ARG(17));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(18));	/* COMPLEX-ARRAY */
			Ferror(ARG(16), 3);
		}
		COPY(ARG(13), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 1 + 1), ARG(14));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
			COPY(ARG(13), ARG(15));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
			Ferror(ARG(14), 3);
		}
		LOAD_FIXNUM(ARG(15), 1, ARG(15));
		COPY(ARG(0), ARG(16));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(16));
		if(CL_TRUEP(ARG(16)))
		{
			COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 1 + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
			COPY(ARG(0), ARG(17));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(18));	/* COMPLEX-ARRAY */
			Ferror(ARG(16), 3);
		}
		COPY(ARG(13), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(15));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 2 + 1), ARG(14));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
			COPY(ARG(13), ARG(15));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(16));	/* COMPLEX-ARRAY */
			Ferror(ARG(14), 3);
		}
		LOAD_FIXNUM(ARG(15), 2, ARG(15));
		COPY(ARG(0), ARG(16));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(17));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(16));
		if(CL_TRUEP(ARG(16)))
		{
			COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 2 + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
			COPY(ARG(0), ARG(17));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(18));	/* COMPLEX-ARRAY */
			Ferror(ARG(16), 3);
		}
	}
	else
	{
		COPY(ARG(0), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(13), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 0 + 1), ARG(14));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
				COPY(ARG(13), ARG(15));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
				Ferror(ARG(14), 3);
			}
			LOAD_FIXNUM(ARG(15), 0, ARG(15));
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(16));
			if(CL_TRUEP(ARG(16)))
			{
				COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 0 + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
				COPY(ARG(0), ARG(17));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
				Ferror(ARG(16), 3);
			}
			COPY(ARG(13), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 1 + 1), ARG(14));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
				COPY(ARG(13), ARG(15));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
				Ferror(ARG(14), 3);
			}
			LOAD_FIXNUM(ARG(15), 1, ARG(15));
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(16));
			if(CL_TRUEP(ARG(16)))
			{
				COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 1 + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
				COPY(ARG(0), ARG(17));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
				Ferror(ARG(16), 3);
			}
			COPY(ARG(13), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 2 + 1), ARG(14));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
				COPY(ARG(13), ARG(15));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
				Ferror(ARG(14), 3);
			}
			LOAD_FIXNUM(ARG(15), 2, ARG(15));
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(16));
			if(CL_TRUEP(ARG(16)))
			{
				COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 2 + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
				COPY(ARG(0), ARG(17));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
				Ferror(ARG(16), 3);
			}
			COPY(ARG(13), ARG(14));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(15));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(13))), 3 + 1), ARG(14));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(14));	/* NO_STRUCT */
				COPY(ARG(13), ARG(15));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(16));	/* COMPLEX-VECTOR */
				Ferror(ARG(14), 3);
			}
			LOAD_FIXNUM(ARG(15), 3, ARG(15));
			COPY(ARG(0), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(17));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(16));
			if(CL_TRUEP(ARG(16)))
			{
				COPY(ARG(14), OFFSET(AR_BASE(GET_FORM(ARG(0))), 3 + 1));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(16));	/* NO_STRUCT */
				COPY(ARG(0), ARG(17));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(18));	/* COMPLEX-VECTOR */
				Ferror(ARG(16), 3);
			}
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Kadjust_array1[8], ARG(14));	/* internal displace-error */
			Ferror(ARG(14), 1);
		}
	}
}

static void Z56_dim_to_skips(CL_FORM *base)
{
	if(CL_CONSP(ARG(0)))
	{
		bool_result = CL_TRUEP(GET_CDR(ARG(0)));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(1));	/* ~a is not a list */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
		else
		{
			bool_result = CL_TRUEP(ARG(0));
		}
	}
	if(bool_result)
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CDR(ARG(0)), ARG(1));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(1));	/* ~a is not a list */
				COPY(ARG(0), ARG(2));
				Ferror(ARG(1), 2);
			}
			else
			{
				COPY(ARG(0), ARG(1));
			}
		}
		Z56_dim_to_skips(ARG(1));
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(2));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
			else
			{
				COPY(ARG(0), ARG(2));
			}
		}
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(3));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(3));	/* ~a is not a list */
				COPY(ARG(1), ARG(4));
				Ferror(ARG(3), 2);
			}
			else
			{
				COPY(ARG(1), ARG(3));
			}
		}
		Fmult(ARG(2), 2);
		ALLOC_CONS(ARG(4), ARG(2), ARG(1), ARG(0));
	}
	else
	{
	}
}

static void Z57_rmi_copy(CL_FORM *base, CL_FORM *display[])
{
	if(CL_CONSP(ARG(0)))
	{
		bool_result = CL_TRUEP(GET_CDR(ARG(0)));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
			COPY(ARG(0), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			bool_result = CL_TRUEP(ARG(0));
		}
	}
	if(bool_result)
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(5));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(5));	/* ~a is not a list */
				COPY(ARG(0), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
				COPY(ARG(0), ARG(5));
			}
		}
		LOAD_FIXNUM(ARG(6), 0, ARG(6));
		M1_1:;
		COPY(ARG(6), ARG(7));
		COPY(ARG(5), ARG(8));
		Fge(ARG(7), 2);
		if(CL_TRUEP(ARG(7)))
		{
			LOAD_NIL(ARG(0));
			goto RETURN1;
		}
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CDR(ARG(0)), ARG(7));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(7));	/* ~a is not a list */
				COPY(ARG(0), ARG(8));
				Ferror(ARG(7), 2);
			}
			else
			{
				COPY(ARG(0), ARG(7));
			}
		}
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CDR(ARG(1)), ARG(8));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(8));	/* ~a is not a list */
				COPY(ARG(1), ARG(9));
				Ferror(ARG(8), 2);
			}
			else
			{
				COPY(ARG(1), ARG(8));
			}
		}
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CDR(ARG(2)), ARG(9));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(9));	/* ~a is not a list */
				COPY(ARG(2), ARG(10));
				Ferror(ARG(9), 2);
			}
			else
			{
				COPY(ARG(2), ARG(9));
			}
		}
		COPY(ARG(3), ARG(10));
		COPY(ARG(6), ARG(11));
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(12));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(12));	/* ~a is not a list */
				COPY(ARG(1), ARG(13));
				Ferror(ARG(12), 2);
			}
			else
			{
				COPY(ARG(1), ARG(12));
			}
		}
		Fmult(ARG(11), 2);
		Fplus(ARG(10), 2);
		COPY(ARG(4), ARG(11));
		COPY(ARG(6), ARG(12));
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CAR(ARG(2)), ARG(13));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(13));	/* ~a is not a list */
				COPY(ARG(2), ARG(14));
				Ferror(ARG(13), 2);
			}
			else
			{
				COPY(ARG(2), ARG(13));
			}
		}
		Fmult(ARG(12), 2);
		Fplus(ARG(11), 2);
		Z57_rmi_copy(ARG(7), display);
		F1plus(ARG(6));
		goto M1_1;
		RETURN1:;
	}
	else
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(5));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(5));	/* ~a is not a list */
				COPY(ARG(0), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
				COPY(ARG(0), ARG(5));
			}
		}
		LOAD_FIXNUM(ARG(6), 0, ARG(6));
		M2_1:;
		COPY(ARG(6), ARG(7));
		COPY(ARG(5), ARG(8));
		Fge(ARG(7), 2);
		if(CL_TRUEP(ARG(7)))
		{
			LOAD_NIL(ARG(0));
			goto RETURN2;
		}
		COPY(&display[0][0], ARG(7));
		COPY(ARG(4), ARG(8));
		Frow_major_aref(ARG(7));
		COPY(&display[0][13], ARG(8));
		COPY(ARG(3), ARG(9));
		Fset_row_major_aref(ARG(7));
		F1plus(ARG(3));
		F1plus(ARG(4));
		F1plus(ARG(6));
		goto M2_1;
		RETURN2:;
	}
}
