/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Carray_reader, array_reader, 3);

CL_INIT Karray_reader[] =
{
	MAKE_STRING(37, "Rank argument must be supplied to #~a"),	/* 0 */
};

static void Z140_calc_dim(CL_FORM *base);

void array_reader(CL_FORM *base)
{
	if(CL_TRUEP(SYMVAL(Slisp, 418)))	/* *READ-SUPPRESS* */
	{
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(4));	/* T */
		LOAD_NIL(ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
		read1(ARG(3));
		LOAD_NIL(ARG(0));
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(0), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(4));	/* T */
			LOAD_NIL(ARG(5));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
			read1(ARG(3));
			COPY(ARG(2), ARG(4));
			COPY(ARG(3), ARG(5));
			Z140_calc_dim(ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(5));	/* T */
			LOAD_NIL(ARG(6));
			COPY(ARG(3), ARG(7));
			LOAD_NIL(ARG(8));
			LOAD_NIL(ARG(9));
			LOAD_NIL(ARG(10));
			LOAD_FIXNUM(ARG(11), 0, ARG(11));
			LOAD_NIL(ARG(12));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(13));	/* T */
			LOAD_NIL(ARG(14));
			make_array1(ARG(4));
			COPY(ARG(4), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Karray_reader[0], ARG(0));	/* Rank argument must be supplied to #~a */
			Ferror(ARG(0), 2);
		}
	}
}

static void Z140_calc_dim(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 0)
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(ARG(1), ARG(2));
		Flength(ARG(2));
		COPY(ARG(0), ARG(3));
		F1minus(ARG(3));
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(4));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(4));	/* ~a is not a list */
				COPY(ARG(1), ARG(5));
				Ferror(ARG(4), 2);
			}
			else
			{
				COPY(ARG(1), ARG(4));
			}
		}
		Z140_calc_dim(ARG(3));
		ALLOC_CONS(ARG(4), ARG(2), ARG(3), ARG(0));
	}
}
