/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Ccons_reader, cons_reader, 2);

CL_INIT Kcons_reader[] =
{
	MAKE_STRING(40, "Nothing appears before the dot in a list"),	/* 0 */
	MAKE_STRING(39, "Nothing appears after the dot in a list"),	/* 2 */
	MAKE_STRING(46, "More than one object found after dot in a list"),	/* 4 */
};

void cons_reader(CL_FORM *base)
{
	LOAD_NIL(ARG(2));
	LOAD_NIL(ARG(3));
	LOAD_NIL(ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(5));	/* T */
	BIND_SPECIAL(SYMBOL(Slisp, 451), ARG(5));	/* *DOT-FLAG* */
	LOAD_CHAR(ARG(6), ')', ARG(6));
	BIND_SPECIAL(SYMBOL(Slisp, 452), ARG(6));	/* *PARENTHESIS-OPEN* */
	COPY(ARG(0), ARG(7));
	COPY(ARG(7), ARG(8));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(9));	/* T */
	LOAD_NIL(ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
	internal_read(ARG(8));
	COPY(ARG(8), ARG(4));
	bool_result = CL_TRUEP(SYMVAL(Slisp, 452));	/* *PARENTHESIS-OPEN* */
	if(bool_result)
	{
	}
	else
	{
		LOAD_NIL(ARG(0));
		RESTORE_SPECIAL;
		RESTORE_SPECIAL;
		goto RETURN1;
	}
	bool_result = CL_TRUEP(SYMVAL(Slisp, 451));	/* *DOT-FLAG* */
	if(bool_result)
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kcons_reader[0], ARG(7));	/* Nothing appears before the dot in a list */
		Ferror(ARG(7), 1);
	}
	LOAD_NIL(ARG(8));
	ALLOC_CONS(ARG(9), ARG(4), ARG(8), ARG(3));
	COPY(ARG(3), ARG(2));
	M1_1:;
	COPY(ARG(0), ARG(7));
	COPY(ARG(7), ARG(8));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(9));	/* T */
	LOAD_NIL(ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
	internal_read(ARG(8));
	COPY(ARG(8), ARG(4));
	bool_result = CL_TRUEP(SYMVAL(Slisp, 452));	/* *PARENTHESIS-OPEN* */
	if(bool_result)
	{
	}
	else
	{
		COPY(ARG(2), ARG(0));
		goto RETURN2;
	}
	bool_result = CL_TRUEP(SYMVAL(Slisp, 451));	/* *DOT-FLAG* */
	if(bool_result)
	{
		COPY(ARG(3), ARG(7));
		LOAD_NIL(ARG(9));
		ALLOC_CONS(ARG(10), ARG(4), ARG(9), ARG(8));
		COPY(ARG(8), ARG(9));
		COPY(ARG(7), ARG(10));
		COPY(ARG(9), GET_CDR(ARG(10)));
		COPY(ARG(9), ARG(3));
	}
	else
	{
		COPY(ARG(0), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
		LOAD_NIL(ARG(9));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
		internal_read(ARG(7));
		COPY(ARG(7), GET_CDR(ARG(3)));
		bool_result = CL_TRUEP(SYMVAL(Slisp, 452));	/* *PARENTHESIS-OPEN* */
		if(bool_result)
		{
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Kcons_reader[2], ARG(7));	/* Nothing appears after the dot in a list */
			Ferror(ARG(7), 1);
		}
		COPY(ARG(0), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
		LOAD_NIL(ARG(9));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
		internal_read(ARG(7));
		bool_result = CL_TRUEP(SYMVAL(Slisp, 452));	/* *PARENTHESIS-OPEN* */
		if(bool_result)
		{
			LOAD_SMSTR((CL_FORM *)&Kcons_reader[4], ARG(7));	/* More than one object found after dot in a list */
			Ferror(ARG(7), 1);
		}
		COPY(ARG(2), ARG(0));
		goto RETURN2;
	}
	goto M1_1;
	RETURN2:;
	RESTORE_SPECIAL;
	RESTORE_SPECIAL;
	RETURN1:;
}
