/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kdigit_char_p1[] =
{
	MAKE_STRING(27, "~A should be suitable radix"),	/* 0 */
};

void digit_char_p1(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(1)))
	{
		LOAD_FIXNUM(ARG(2), 2, ARG(2));
		COPY(ARG(1), ARG(3));
		LOAD_FIXNUM(ARG(4), 36, ARG(4));
		Fle(ARG(2), 3);
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		ELSE1:;
		LOAD_SMSTR((CL_FORM *)&Kdigit_char_p1[0], ARG(2));	/* ~A should be suitable radix */
		COPY(ARG(1), ARG(3));
		Ferror(ARG(2), 2);
	}
	if(CL_CHARP(ARG(0)))
	{
		COPY(ARG(0), ARG(2));
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(2));	/* WRONG_TYPE */
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(4));	/* CHARACTER */
		Ferror(ARG(2), 3);
	}
	rt_digit_char(ARG(2));
	COPY(ARG(2), ARG(0));
	if(CL_TRUEP(ARG(0)))
	{
		COPY(ARG(0), ARG(2));
		COPY(ARG(1), ARG(3));
		Flt(ARG(2), 2);
		if(CL_TRUEP(ARG(2)))
		{
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
