/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void error_in(CL_FORM *base, int nargs)
{
	Flist(ARG(2), nargs - 2);
	LOAD_SMSTR((CL_FORM *)&KClisp[240], ARG(3));	/* ~&Error in ~A: ~?~% */
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	COPY(ARG(2), ARG(6));
	Ferror(ARG(3), 4);
}
