/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fadjust_array(CL_FORM *base, int nargs)
{
	BOOL supl_flags[6];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 99),	/* ELEMENT-TYPE */
		SYMBOL(Slisp, 155),	/* INITIAL-ELEMENT */
		SYMBOL(Slisp, 103),	/* INITIAL-CONTENTS */
		SYMBOL(Slisp, 101),	/* FILL-POINTER */
		SYMBOL(Slisp, 156),	/* DISPLACED-TO */
		SYMBOL(Slisp, 157),	/* DISPLACED-INDEX-OFFSET */
	};
	keysort(ARG(2), nargs - 2, 6, keylist, supl_flags, FALSE);
	Flist(ARG(8), nargs - 2);
	if(NOT(supl_flags[0]))
	{
		LOAD_NIL(ARG(2));
		LOAD_NIL(ARG(9));
	}
	else
	{
		LOAD_T(ARG(9));
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_NIL(ARG(3));
	}
	if(NOT(supl_flags[2]))
	{
		LOAD_NIL(ARG(4));
	}
	if(NOT(supl_flags[3]))
	{
		LOAD_NIL(ARG(5));
		LOAD_NIL(ARG(10));
	}
	else
	{
		LOAD_T(ARG(10));
	}
	if(NOT(supl_flags[4]))
	{
		LOAD_NIL(ARG(6));
	}
	if(NOT(supl_flags[5]))
	{
		LOAD_NIL(ARG(7));
	}
	adjust_array1(ARG(0));
}
