/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Farray_rank(CL_FORM *base)
{
	LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(2));
	}
	if(CL_TRUEP(ARG(2)))
	{
		THEN1:;
		LOAD_FIXNUM(ARG(1), 1, ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(2));	/* COMPLEX-ARRAY */
		rt_struct_typep(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			complex_array_dims(ARG(0));
			Flength(ARG(0));
		}
		else
		{
			COPY(SYMVAL(Slisp, 152), ARG(1));	/* NO_ARRAY */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
	}
}
