/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fash(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	Fminusp(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(1), ARG(3));
		Fminus(ARG(3), 1);
		LOAD_FIXNUM(ARG(4), GET_FIXNUM(ARG(0)) >> GET_FIXNUM(ARG(3)), ARG(0));
	}
	else
	{
		LOAD_FIXNUM(ARG(4), GET_FIXNUM(ARG(0)) << GET_FIXNUM(ARG(1)), ARG(0));
	}
}
