/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fcaaaar(CL_FORM *base)
{
	Fcar(ARG(0));
	Fcar(ARG(0));
	Fcar(ARG(0));
	Fcar(ARG(0));
}
