/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fcddddr(CL_FORM *base)
{
	Fcdr(ARG(0));
	Fcdr(ARG(0));
	Fcdr(ARG(0));
	Fcdr(ARG(0));
}
