/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fclrhash(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	hash_table_array(ARG(1));
	LOAD_FIXNUM(ARG(2), 0, ARG(2));
	LOAD_FIXNUM(ARG(3), 1, ARG(3));
	COPY(ARG(0), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(5));	/* HASH-TABLE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_FIXNUM(ARG(4), 0, ARG(4));
		COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(ARG(0))), 1 + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(0), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(6));	/* HASH-TABLE */
		Ferror(ARG(4), 3);
	}
	LOAD_FIXNUM(ARG(2), 0, ARG(2));
	M1_1:;
	COPY(ARG(2), ARG(3));
	COPY(ARG(1), ARG(4));
	Flength(ARG(4));
	Fge(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		goto RETURN1;
	}
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	COPY(ARG(2), ARG(5));
	rt_set_vref(ARG(3));
	F1plus(ARG(2));
	goto M1_1;
	RETURN1:;
}
