/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFconcatenate, Fconcatenate, -2);

void Fconcatenate(CL_FORM *base, int nargs)
{
	CL_FORM *rest_0;
	CL_FORM *local;
	rest_0 = ARG(1);
	local = ARG(nargs);
	if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 28))	/* LIST */
	{
		LOAD_GLOBFUN(&Cconcatenate_to_list, LOCAL(0));
		REST_APPLY(LOCAL(0), 1, rest_0);
		COPY(LOCAL(0), ARG(0));
	}
	else
	{
		LOAD_GLOBFUN(&Cconcatenate_to_non_list, LOCAL(0));
		COPY(ARG(0), LOCAL(1));
		REST_APPLY(LOCAL(0), 2, rest_0);
		COPY(LOCAL(0), ARG(0));
	}
}
