/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFdelete, Fdelete, -3);

void Fdelete(CL_FORM *base, int nargs)
{
	CL_FORM *rest_0;
	CL_FORM *local;
	rest_0 = ARG(2);
	local = ARG(nargs);
	LOAD_GLOBFUN(&CFremove, LOCAL(0));
	COPY(ARG(0), LOCAL(1));
	COPY(ARG(1), LOCAL(2));
	REST_APPLY(LOCAL(0), 3, rest_0);
	COPY(LOCAL(0), ARG(0));
}
