/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Felt(CL_FORM *base)
{
	if(CL_CONSP(ARG(0)))
	{
		COPY(ARG(1), ARG(2));
		COPY(ARG(0), ARG(3));
		Fnthcdr(ARG(2));
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CAR(ARG(2)), ARG(0));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(0));	/* ~a is not a list */
				COPY(ARG(2), ARG(1));
				Ferror(ARG(0), 2);
			}
			else
			{
				COPY(ARG(2), ARG(0));
			}
		}
	}
	else
	{
		LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(0), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(4));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(3));
		}
		if(CL_TRUEP(ARG(3)))
		{
			THEN1:;
			Frow_major_aref(ARG(0));
		}
		else
		{
			COPY(SYMVAL(Slisp, 58), ARG(2));	/* WRONG_TYPE */
			COPY(ARG(0), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 36), ARG(4));	/* SEQUENCE */
			Ferror(ARG(2), 3);
		}
	}
}
