/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFequal, Fequal, 2);

void Fequal(CL_FORM *base)
{
	M1_1:;
	if(CL_CONSP(ARG(0)))
	{
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(0)), ARG(2));
			COPY(GET_CAR(ARG(1)), ARG(3));
			Fequal(ARG(2));
			if(CL_TRUEP(ARG(2)))
			{
				COPY(GET_CDR(ARG(0)), ARG(2));
				COPY(GET_CDR(ARG(1)), ARG(3));
				COPY(ARG(2), ARG(0));
				COPY(ARG(3), ARG(1));
				goto M1_1;
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Fstringp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(1), ARG(2));
			Fstringp(ARG(2));
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_FIXNUM(ARG(2), 0, ARG(2));
				LOAD_NIL(ARG(3));
				LOAD_FIXNUM(ARG(4), 0, ARG(4));
				LOAD_NIL(ARG(5));
				stringE1(ARG(0));
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		else
		{
			LOAD_BOOL(EQL(ARG(0), ARG(1)), ARG(0));
		}
	}
	goto RETURN1;
	RETURN1:;
}
