/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void FFI_c_char(CL_FORM *base)
{
	if(CL_CHARP(ARG(0)))
	{
		rt_make_c_char(ARG(0));
	}
	else
	{
		if(CL_C_CHAR_P(ARG(0)))
		{
			rt_cast_c_char(ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[62], ARG(1));	/* C-CHAR */
			LOAD_SMSTR((CL_FORM *)&KClisp[60], ARG(2));	/* The evaluated value ~S is not of type character. */
			COPY(ARG(0), ARG(3));
			error_in(ARG(1), 3);
		}
	}
}
