/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void FFI_c_long(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(0)))
	{
		rt_make_c_long(ARG(0));
	}
	else
	{
		if(CL_C_LONG_P(ARG(0)))
		{
			rt_cast_c_long(ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[50], ARG(1));	/* C-LONG */
			LOAD_SMSTR((CL_FORM *)&KClisp[48], ARG(2));	/* The evaluated value ~S is not of type fixnum. */
			COPY(ARG(0), ARG(3));
			error_in(ARG(1), 3);
		}
	}
}
