/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z132_lambda(CL_FORM *base);

void Ffind_package(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(1));
	{
		CONTENV new_cont;
		CL_FORM *caller_base;
		new_cont.bind_top = bind_top;
		new_cont.last = last_cont;
		LOAD_UNIQUE_TAG(ARG(1));
		GEN_HEAPVAR(ARG(1), ARG(2));
		caller_base = (CL_FORM *)SETJMP(new_cont.jmp_buf);
		if(caller_base == NULL)
		{
			last_cont = &new_cont;
			if(CL_SYMBOLP(INDIRECT(ARG(0))) || CL_NILP(INDIRECT(ARG(0))))
			{
				COPY(INDIRECT(ARG(0)), ARG(2));
				if(CL_SYMBOLP(ARG(2)))
				{
					LOAD_SMSTR(SYM_NAME(ARG(2)), INDIRECT(ARG(0)));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[266], INDIRECT(ARG(0)));	/* NIL */
				}
			}
			LOAD_NIL(ARG(2));
			{
				GEN_CLOSURE(array, ARG(3), 5, Z132_lambda, 1);
				COPY(ARG(1), &array[3]);
				COPY(ARG(0), &array[4]);
				LOAD_CLOSURE(array, ARG(3));
			}
			COPY(ARG(3), ARG(3));
			COPY(SYMVAL(Slisp, 389), ARG(4));	/* *PACKAGE-ARRAY* */
			Fmap(ARG(2), 3);
			COPY(ARG(2), ARG(0));
			RETURN1:;
			last_cont = new_cont.last;
		}
		else
		{
			last_cont = new_cont.last;
			if(EQ(STACK(caller_base, 0), INDIRECT(ARG(1))))
			{
				COPY(STACK(caller_base, 1), ARG(0));
			}
			else
			{
				call_cont(caller_base);
			}
		}
	}
}

static void Z132_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
	COPY(ARG(1), ARG(3));
	Ppackage_name(ARG(3));
	LOAD_FIXNUM(ARG(4), 0, ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_FIXNUM(ARG(6), 0, ARG(6));
	LOAD_NIL(ARG(7));
	stringE1(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
		COPY(ARG(1), ARG(3));
		call_cont(ARG(2));
	}
	LOAD_NIL(ARG(2));
	COPY(ARG(1), ARG(3));
	Ppackage_nicknames(ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(ARG(2));
		COPY(ARG(2), ARG(0));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), ARG(2));
	COPY(ARG(2), ARG(4));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(5));
	LOAD_FIXNUM(ARG(6), 0, ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_FIXNUM(ARG(8), 0, ARG(8));
	LOAD_NIL(ARG(9));
	stringE1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(4));
		COPY(ARG(1), ARG(5));
		call_cont(ARG(4));
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
}
