/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Ffloat_sign(CL_FORM *base, int nargs)
{
	MEM_UP_MOVE(ARG(0 + nargs), ARG(1), 1);
	LOAD_NIL(ARG(1));
	nargs = nargs + 1;
	if(nargs > 3)
	{
		goto ALL_OPT_SUPPLIED;
	}
	switch(nargs)
	{
		case 3:
		ALL_OPT_SUPPLIED:;
		LOAD_T(ARG(1));
	}
	switch(nargs)
	{
		case 2:
		GEN_FLOAT(ARG(2), 1.0, ARG(2));
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	float_sign1(ARG(0));
}
