/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "inline.h"

void Ffloatp(CL_FORM *base)
{
	LOAD_BOOL(CL_FLOATP(ARG(0)), ARG(0));
}
