/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void fill1(CL_FORM *base)
{
	COPY(ARG(2), ARG(4));
	COPY(ARG(3), ARG(5));
	COPY(ARG(0), ARG(6));
	Flength(ARG(6));
	check_seq_start_end(ARG(4));
	COPY(ARG(4), ARG(3));
	COPY(ARG(2), ARG(4));
	M1_1:;
	COPY(ARG(4), ARG(5));
	COPY(ARG(3), ARG(6));
	Fge(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		goto RETURN1;
	}
	COPY(ARG(1), ARG(5));
	COPY(ARG(0), ARG(6));
	COPY(ARG(4), ARG(7));
	Fset_elt(ARG(5));
	F1plus(ARG(4));
	goto M1_1;
	RETURN1:;
}
