/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kfind_symbol1[] =
{
	MAKE_STRING(18, "~a is not a string"),	/* 0 */
};

void find_symbol1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	Fstringp(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kfind_symbol1[0], ARG(2));	/* ~a is not a string */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
	LOAD_FIXNUM(ARG(2), 101, ARG(2));
	COPY(ARG(0), ARG(3));
	string_to_simple_string(ARG(3));
	rt_sxhash_string(ARG(3));
	COPY(ARG(3), ARG(4));
	LOAD_FIXNUM(ARG(5), 101, ARG(5));
	rt_floor(ARG(4));
	COPY(&mv_buf[0], ARG(5));
	mv_count = 1;
	{
		COPY(ARG(5), ARG(2));
	}
	COPY(ARG(1), ARG(3));
	coerce_to_package(ARG(3));
	COPY(ARG(3), ARG(1));
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 3 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(2), ARG(5));
	Fsvref(ARG(4));
	M1_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN2;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	if(CL_SYMBOLP(ARG(3)))
	{
		LOAD_SMSTR(SYM_NAME(ARG(3)), ARG(5));
	}
	else
	{
		if(CL_TRUEP(ARG(3)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(5));	/* SYM_EXPECTED */
			COPY(ARG(3), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(5));	/* NIL */
		}
	}
	COPY(ARG(0), ARG(6));
	COPY(ARG(5), ARG(7));
	LOAD_FIXNUM(ARG(8), 0, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_FIXNUM(ARG(10), 0, ARG(10));
	LOAD_NIL(ARG(11));
	stringE1(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(3), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 385), ARG(1));	/* EXTERNAL */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M1_1;
	RETURN2:;
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 2 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(2), ARG(5));
	Fsvref(ARG(4));
	M2_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN3;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	if(CL_SYMBOLP(ARG(3)))
	{
		LOAD_SMSTR(SYM_NAME(ARG(3)), ARG(5));
	}
	else
	{
		if(CL_TRUEP(ARG(3)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(5));	/* SYM_EXPECTED */
			COPY(ARG(3), ARG(6));
			Ferror(ARG(5), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(5));	/* NIL */
		}
	}
	COPY(ARG(0), ARG(6));
	COPY(ARG(5), ARG(7));
	LOAD_FIXNUM(ARG(8), 0, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_FIXNUM(ARG(10), 0, ARG(10));
	LOAD_NIL(ARG(11));
	stringE1(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(3), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 384), ARG(1));	/* INTERNAL */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M2_1;
	RETURN3:;
	LOAD_NIL(ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	M3_1:;
	if(CL_ATOMP(ARG(4)))
	{
		LOAD_NIL(ARG(3));
		goto RETURN4;
	}
	COPY(ARG(4), ARG(5));
	COPY(GET_CAR(ARG(5)), ARG(3));
	LOAD_NIL(ARG(5));
	COPY(ARG(3), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 3 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
		COPY(ARG(3), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(2), ARG(7));
	Fsvref(ARG(6));
	M4_1:;
	if(CL_ATOMP(ARG(6)))
	{
		LOAD_NIL(ARG(5));
		goto RETURN5;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CAR(ARG(7)), ARG(5));
	if(CL_SYMBOLP(ARG(5)))
	{
		LOAD_SMSTR(SYM_NAME(ARG(5)), ARG(7));
	}
	else
	{
		if(CL_TRUEP(ARG(5)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(7));	/* SYM_EXPECTED */
			COPY(ARG(5), ARG(8));
			Ferror(ARG(7), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(7));	/* NIL */
		}
	}
	COPY(ARG(0), ARG(8));
	COPY(ARG(7), ARG(9));
	LOAD_FIXNUM(ARG(10), 0, ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_FIXNUM(ARG(12), 0, ARG(12));
	LOAD_NIL(ARG(13));
	stringE1(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(5), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 393), ARG(1));	/* INHERITED */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
		goto RETURN1;
	}
	COPY(ARG(6), ARG(7));
	COPY(GET_CDR(ARG(7)), ARG(6));
	goto M4_1;
	RETURN5:;
	COPY(ARG(4), ARG(5));
	COPY(GET_CDR(ARG(5)), ARG(4));
	goto M3_1;
	RETURN4:;
	LOAD_NIL(ARG(0));
	LOAD_NIL(ARG(1));
	COPY(ARG(1), &mv_buf[0]);
	mv_count = 2;
	RETURN1:;
}
