/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fldiff(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		LOAD_NIL(ARG(2));
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	}
	if(CL_TRUEP(ARG(2)))
	{
		goto THEN1;
	}
	else
	{
	}
	if(EQ(ARG(0), ARG(1)))
	{
		THEN1:;
		LOAD_NIL(ARG(0));
	}
	else
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(2));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
			else
			{
				COPY(ARG(0), ARG(2));
			}
		}
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CDR(ARG(0)), ARG(3));
		}
		else
		{
			if(CL_TRUEP(ARG(0)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(3));	/* ~a is not a list */
				COPY(ARG(0), ARG(4));
				Ferror(ARG(3), 2);
			}
			else
			{
				COPY(ARG(0), ARG(3));
			}
		}
		COPY(ARG(1), ARG(4));
		Fldiff(ARG(3));
		ALLOC_CONS(ARG(4), ARG(2), ARG(3), ARG(0));
	}
}
