/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void float_sign1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(1)))
	{
		if(CL_FLOATP(ARG(2)))
		{
			COPY(ARG(2), ARG(3));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[244], ARG(3));	/* type error: ~S is not of type ~S */
			COPY(ARG(2), ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 24), ARG(5));	/* FLOAT */
			Ferror(ARG(3), 3);
		}
		COPY(ARG(3), ARG(4));
		Fminusp(ARG(4));
		if(CL_TRUEP(ARG(4)))
		{
			Fminus(ARG(3), 1);
		}
		else
		{
		}
		COPY(ARG(3), ARG(2));
	}
	if(CL_FLOATP(ARG(0)))
	{
		COPY(ARG(0), ARG(3));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[244], ARG(3));	/* type error: ~S is not of type ~S */
		COPY(ARG(0), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 24), ARG(5));	/* FLOAT */
		Ferror(ARG(3), 3);
	}
	Fminusp(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(2), ARG(0));
		Fminus(ARG(0), 1);
	}
	else
	{
		COPY(ARG(2), ARG(0));
	}
}
