/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Flogandc2(CL_FORM *base)
{
	Flognot(ARG(1));
	Flogand(ARG(0), 2);
}
