/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Flog(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 1:
		GEN_FLOAT(ARG(1), 2.7182817, ARG(1));
		case 2:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	log1(ARG(0));
}
