/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z135_lambda(CL_FORM *base);

void Fmaphash(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(2));
	LOAD_NIL(ARG(2));
	{
		GEN_CLOSURE(array, ARG(3), 4, Z135_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	COPY(ARG(1), ARG(4));
	hash_table_array(ARG(4));
	Fmap(ARG(2), 3);
	LOAD_NIL(ARG(0));
}

static void Z136_lambda(CL_FORM *base);

static void Z135_lambda(CL_FORM *base)
{
	GEN_CLOSURE(array, ARG(2), 4, Z136_lambda, 1);
	COPY(GET_FORM(ARG(0)) + 3, &array[3]);
	LOAD_CLOSURE(array, ARG(2));
	COPY(ARG(2), ARG(2));
	COPY(ARG(1), ARG(3));
	Fmapc(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}

static void Z136_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	if(CL_CONSP(ARG(1)))
	{
		COPY(GET_CAR(ARG(1)), ARG(3));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(3));	/* ~a is not a list */
			COPY(ARG(1), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
			COPY(ARG(1), ARG(3));
		}
	}
	if(CL_CONSP(ARG(1)))
	{
		COPY(GET_CDR(ARG(1)), ARG(4));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(4));	/* ~a is not a list */
			COPY(ARG(1), ARG(5));
			Ferror(ARG(4), 2);
		}
		else
		{
			COPY(ARG(1), ARG(4));
		}
	}
	Ffuncall(ARG(2), 3);
	COPY(ARG(2), ARG(0));
}
