/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z123_get_rest_args(CL_FORM *base, CL_FORM *display[]);

void Fmapl(CL_FORM *base, int nargs)
{
	CL_FORM *display[1];
	Flist(ARG(2), nargs - 2);
	{
		CONTENV new_cont;
		CL_FORM *caller_base;
		new_cont.bind_top = bind_top;
		new_cont.last = last_cont;
		LOAD_UNIQUE_TAG(ARG(3));
		caller_base = (CL_FORM *)SETJMP(new_cont.jmp_buf);
		if(caller_base == NULL)
		{
			last_cont = &new_cont;
			M1_1:;
			if(CL_ATOMP(ARG(1)))
			{
				goto RETURN1;
			}
			else
			{
				COPY(ARG(0), ARG(4));
				COPY(ARG(1), ARG(5));
				COPY(ARG(2), ARG(6));
				display[0] = ARG(0);
				Z123_get_rest_args(ARG(6), display);
				Fapply(ARG(4), 3);
				mv_count = 1;
			}
			COPY(GET_CAR(ARG(1)), ARG(4));
			COPY(ARG(1), ARG(5));
			COPY(ARG(5), ARG(6));
			COPY(GET_CDR(ARG(6)), ARG(1));
			goto M1_1;
			RETURN1:;
			last_cont = new_cont.last;
		}
		else
		{
			last_cont = new_cont.last;
			if(EQ(STACK(caller_base, 0), ARG(3)))
			{
			}
			else
			{
				call_cont(caller_base);
			}
		}
	}
	COPY(ARG(1), ARG(0));
}

static void Z123_get_rest_args(CL_FORM *base, CL_FORM *display[])
{
	if(CL_ATOMP(ARG(0)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(GET_CAR(ARG(0)), ARG(1));
		if(CL_ATOMP(ARG(1)))
		{
			COPY(&display[0][3], ARG(1));
			LOAD_NIL(ARG(2));
			call_cont(ARG(1));
		}
		COPY(GET_CAR(ARG(0)), ARG(1));
		COPY(GET_CAR(ARG(0)), ARG(2));
		if(CL_CONSP(ARG(2)))
		{
			COPY(GET_CAR(ARG(2)), ARG(3));
		}
		else
		{
			if(CL_TRUEP(ARG(2)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(3));	/* ~a is not a list */
				COPY(ARG(2), ARG(4));
				Ferror(ARG(3), 2);
			}
			else
			{
				COPY(ARG(2), ARG(3));
			}
		}
		COPY(ARG(2), ARG(4));
		COPY(ARG(4), ARG(5));
		if(CL_CONSP(ARG(5)))
		{
			COPY(GET_CDR(ARG(5)), ARG(2));
		}
		else
		{
			if(CL_TRUEP(ARG(5)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(6));	/* ~a is not a list */
				COPY(ARG(5), ARG(7));
				Ferror(ARG(6), 2);
			}
			else
			{
				COPY(ARG(5), ARG(2));
			}
		}
		COPY(ARG(2), GET_CAR(ARG(0)));
		COPY(GET_CDR(ARG(0)), ARG(2));
		Z123_get_rest_args(ARG(2), display);
		ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(0));
	}
}
