/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFnconc, Fnconc, -1);

void Fnconc(CL_FORM *base, int nargs)
{
	CL_FORM *rest_0;
	CL_FORM *local;
	rest_0 = ARG(0);
	local = ARG(nargs);
	if(REST_NOT_EMPTY(rest_0))
	{
		REST_CAR(rest_0, LOCAL(0));
		{
			CL_FORM *rest_1;
			CL_FORM *rest_2;
			rest_1 = rest_0;
			rest_2 = rest_1;
			rest_0 = REST_CDR(rest_2);
		}
		if(CL_TRUEP(LOCAL(0)))
		{
			COPY(LOCAL(0), LOCAL(1));
			LOAD_NIL(LOCAL(2));
			M1_1:;
			if(REST_NOT_EMPTY(rest_0))
			{
			}
			else
			{
				COPY(LOCAL(1), ARG(0));
				goto RETURN1;
			}
			{
				CL_FORM *rest_3;
				CL_FORM *rest_4;
				rest_3 = rest_0;
				rest_4 = rest_3;
				REST_CAR(rest_4, LOCAL(3));
				{
					CL_FORM *rest_5;
					CL_FORM *rest_6;
					rest_5 = rest_0;
					rest_6 = rest_5;
					rest_0 = REST_CDR(rest_6);
				}
				COPY(LOCAL(3), LOCAL(2));
			}
			if(CL_TRUEP(LOCAL(2)))
			{
				COPY(LOCAL(0), LOCAL(3));
				LOAD_FIXNUM(LOCAL(4), 1, LOCAL(4));
				last1(LOCAL(3));
				if(CL_CONSP(LOCAL(3)))
				{
					COPY(LOCAL(2), GET_CDR(LOCAL(3)));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[258], LOCAL(4));	/* ~a is not a cons */
					COPY(LOCAL(3), LOCAL(5));
					Ferror(LOCAL(4), 2);
				}
				COPY(LOCAL(2), LOCAL(0));
			}
			goto M1_1;
			RETURN1:;
		}
		else
		{
			LOAD_GLOBFUN(&CFnconc, LOCAL(1));
			REST_APPLY(LOCAL(1), 1, rest_0);
			COPY(LOCAL(1), ARG(0));
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
