/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fninth(CL_FORM *base)
{
	LOAD_FIXNUM(ARG(1), 8, ARG(1));
	COPY(ARG(0), ARG(2));
	Fnth(ARG(1));
	COPY(ARG(1), ARG(0));
}
