/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fopen(CL_FORM *base, int nargs)
{
	BOOL supl_flags[3];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 219),	/* DIRECTION */
		SYMBOL(Slisp, 221),	/* IF-EXISTS */
		SYMBOL(Slisp, 228),	/* IF-DOES-NOT-EXIST */
	};
	keysort(ARG(1), nargs - 1, 3, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 218), ARG(1));	/* INPUT */
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 220), ARG(2));	/* ERROR */
	}
	if(NOT(supl_flags[2]))
	{
		if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 218))	/* INPUT */
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 220), ARG(3));	/* ERROR */
		}
		else
		{
			LOAD_BOOL(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 222), ARG(4));	/* OUTPUT */
			if(CL_TRUEP(ARG(4)))
			{
				goto THEN1;
			}
			else
			{
			}	/* IO */
			if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 223))
			{
				THEN1:;
				LOAD_BOOL(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 224), ARG(4));	/* OVERWRITE */
				if(CL_TRUEP(ARG(4)))
				{
					goto THEN2;
				}
				else
				{
				}	/* APPEND */
				if(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 225))
				{
					THEN2:;
					LOAD_SYMBOL(SYMBOL(Slisp, 220), ARG(3));	/* ERROR */
				}
				else
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 226), ARG(3));	/* CREATE */
				}
			}
			else
			{
				if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 227))	/* PROBE */
				{
					LOAD_NIL(ARG(3));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[132], ARG(4));	/* illegal option ~s */
					COPY(ARG(1), ARG(5));
					Ferror(ARG(4), 2);
				}
			}
		}
	}
	open1(ARG(0));
}
