/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kformat21[] =
{
	MAKE_STRING(31, "Not enough arguments for format"),	/* 0 */
	MAKE_STRING(41, "Syntax error at end of control-string: ~s"),	/* 2 */
	MAKE_STRING(27, "Too many at-signs supplied."),	/* 4 */
	MAKE_STRING(25, "Too many colons supplied."),	/* 6 */
	MAKE_STRING(41, "Syntax error at end of control-string: ~s"),	/* 8 */
	MAKE_STRING(31, "~~~A expected in control-string"),	/* 10 */
	MAKE_STRING(13, "~~~A expected"),	/* 12 */
	MAKE_STRING(2, "()"),	/* 14 */
	MAKE_STRING(2, "()"),	/* 16 */
	MAKE_STRING(2, "()"),	/* 18 */
	MAKE_STRING(2, "()"),	/* 20 */
	MAKE_STRING(3, "ies"),	/* 22 */
	MAKE_STRING(23, "illegal directive ~~:@p"),	/* 24 */
	MAKE_STRING(23, "illegal directive ~~:@*"),	/* 26 */
	MAKE_STRING(40, "~~~a:* will skip to nonexistant argument"),	/* 28 */
	MAKE_STRING(32, "unexpected ~~; in control-string"),	/* 30 */
	MAKE_STRING(23, "Illegal directive ~~:@["),	/* 32 */
	MAKE_STRING(32, "unexpected ~~} in control-string"),	/* 34 */
	MAKE_STRING(32, "unexpected ~~} in control-string"),	/* 36 */
	MAKE_STRING(84, "illegal / unimplemented directive (~A) in ~\n                          control-string"),	/* 38 */
	MAKE_STRING(32, "unexpected end of control-string"),	/* 40 */
};

static void Z36_goto(CL_FORM *base, CL_FORM *display[]);
static void Z37_get_arg(CL_FORM *base, CL_FORM *display[]);
static void Z38_get_ctrl(CL_FORM *base, CL_FORM *display[]);
static void Z39_get_params(CL_FORM *base, CL_FORM *display[]);
static void Z40_get_at_sign_or_colon(CL_FORM *base, CL_FORM *display[]);
static void Z41_get_directive(CL_FORM *base, CL_FORM *display[]);
static void Z42_skip(CL_FORM *base, CL_FORM *display[], int nargs);
static void Z43_insert_space(CL_FORM *base, CL_FORM *display[]);
static void Z44_tabbing(CL_FORM *base, CL_FORM *display[], int nargs);
static void Z45_padding(CL_FORM *base, CL_FORM *display[], int nargs);

void format21(CL_FORM *base)
{
	CL_FORM *display[1];
	COPY(ARG(2), ARG(6));
	LOAD_FIXNUM(ARG(7), 0, ARG(7));
	LOAD_NIL(ARG(8));
	COPY(ARG(1), ARG(9));
	Flength(ARG(9));
	LOAD_NIL(ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_NIL(ARG(12));
	LOAD_NIL(ARG(13));
	LOAD_NIL(ARG(14));
	M1_1:;
	display[0] = ARG(0);
	Z38_get_ctrl(ARG(15), display);
	COPY(ARG(15), ARG(10));
	if(CL_TRUEP(ARG(10)))
	{
	}
	else
	{
		if(CL_TRUEP(ARG(4)))
		{
			LOAD_SMSTR((CL_FORM *)&Kformat21[12], ARG(15));	/* ~~~A expected */
			COPY(ARG(4), ARG(16));
			Ferror(ARG(15), 2);
		}
		goto RETURN2;
	}
	if(CL_CHARP(ARG(10)) && GET_CHAR(ARG(10)) == '~')
	{
		display[0] = ARG(0);
		Z39_get_params(ARG(15), display);
		COPY(ARG(11), ARG(15));
		COPY(ARG(15), ARG(16));
		if(CL_CONSP(ARG(16)))
		{
			COPY(GET_CAR(ARG(16)), ARG(12));
		}
		else
		{
			if(CL_TRUEP(ARG(16)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(17));	/* ~a is not a list */
				COPY(ARG(16), ARG(18));
				Ferror(ARG(17), 2);
			}
			else
			{
				COPY(ARG(16), ARG(12));
			}
		}
		display[0] = ARG(0);
		Z40_get_at_sign_or_colon(ARG(15), display);
		display[0] = ARG(0);
		Z41_get_directive(ARG(15), display);
		COPY(ARG(15), ARG(10));
		if(CL_CHARP(ARG(10)))
		{
			COPY(ARG(10), ARG(15));
		}
		else
		{
			COPY(SYMVAL(Slisp, 58), ARG(15));	/* WRONG_TYPE */
			COPY(ARG(10), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(17));	/* CHARACTER */
			Ferror(ARG(15), 3);
		}
		rt_char_upcase(ARG(15));
		if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'A')
		{
			if(CL_TRUEP(ARG(11)))
			{
				display[0] = ARG(0);
				Z37_get_arg(ARG(16), display);
				if(CL_TRUEP(ARG(14)))
				{
					if(CL_TRUEP(ARG(16)))
					{
						goto ELSE1;
					}
					else
					{
						goto THEN2;
					}
				}
				else
				{
					goto ELSE1;
				}
				{
					THEN2:;
					LOAD_SMSTR((CL_FORM *)&Kformat21[14], ARG(17));	/* () */
				}
				goto ENDIF3;
				{
					ELSE1:;
					LOAD_FIXNUM(ARG(17), 10, ARG(17));
					LOAD_SYMBOL(SYMBOL(Slisp, 99), ARG(18));	/* ELEMENT-TYPE */
					LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(19));	/* CHARACTER */
					LOAD_SYMBOL(SYMBOL(Slisp, 100), ARG(20));	/* ADJUSTABLE */
					LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(21));	/* T */
					LOAD_SYMBOL(SYMBOL(Slisp, 101), ARG(22));	/* FILL-POINTER */
					LOAD_FIXNUM(ARG(23), 0, ARG(23));
					Fmake_array(ARG(17), 7);
					COPY(ARG(17), ARG(18));
					make_string_output_stream1(ARG(18));
					COPY(ARG(18), ARG(17));
					COPY(ARG(16), ARG(18));
					COPY(ARG(17), ARG(19));
					princ1(ARG(18));
					COPY(ARG(17), ARG(18));
					Fget_output_stream_string(ARG(18));
					mv_count = 1;
					COPY(ARG(18), ARG(17));
				}
				ENDIF3:;
				COPY(ARG(17), ARG(18));
				Flength(ARG(18));
				if(CL_TRUEP(ARG(13)))
				{
					DOWN_FUNARG downfun1;
					INIT_DOWN_FUNARG(downfun1, Z45_padding, -2, display);
					LOAD_DOWNFUN(&downfun1, ARG(19));
					COPY(ARG(18), ARG(20));
					COPY(ARG(11), ARG(21));
					display[0] = ARG(0);
					Fapply(ARG(19), 3);
					mv_count = 1;
					COPY(ARG(17), ARG(19));
					COPY(ARG(0), ARG(20));
					princ1(ARG(19));
				}
				else
				{
					COPY(ARG(17), ARG(19));
					COPY(ARG(0), ARG(20));
					princ1(ARG(19));
					{
						DOWN_FUNARG downfun1;
						INIT_DOWN_FUNARG(downfun1, Z45_padding, -2, display);
						LOAD_DOWNFUN(&downfun1, ARG(19));
						COPY(ARG(18), ARG(20));
						COPY(ARG(11), ARG(21));
						display[0] = ARG(0);
						Fapply(ARG(19), 3);
						mv_count = 1;
					}
				}
			}
			else
			{
				if(CL_TRUEP(ARG(14)))
				{
					display[0] = ARG(0);
					Z37_get_arg(ARG(16), display);
					if(CL_TRUEP(ARG(16)))
					{
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kformat21[16], ARG(16));	/* () */
					}
				}
				else
				{
					display[0] = ARG(0);
					Z37_get_arg(ARG(16), display);
				}
				COPY(ARG(16), ARG(17));
				COPY(ARG(0), ARG(18));
				princ1(ARG(17));
			}
		}
		else
		{
			if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'S')
			{
				if(CL_TRUEP(ARG(11)))
				{
					display[0] = ARG(0);
					Z37_get_arg(ARG(16), display);
					if(CL_TRUEP(ARG(14)))
					{
						if(CL_TRUEP(ARG(16)))
						{
							goto ELSE4;
						}
						else
						{
							goto THEN5;
						}
					}
					else
					{
						goto ELSE4;
					}
					{
						THEN5:;
						LOAD_SMSTR((CL_FORM *)&Kformat21[18], ARG(17));	/* () */
					}
					goto ENDIF6;
					{
						ELSE4:;
						LOAD_FIXNUM(ARG(17), 10, ARG(17));
						LOAD_SYMBOL(SYMBOL(Slisp, 99), ARG(18));	/* ELEMENT-TYPE */
						LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(19));	/* CHARACTER */
						LOAD_SYMBOL(SYMBOL(Slisp, 100), ARG(20));	/* ADJUSTABLE */
						LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(21));	/* T */
						LOAD_SYMBOL(SYMBOL(Slisp, 101), ARG(22));	/* FILL-POINTER */
						LOAD_FIXNUM(ARG(23), 0, ARG(23));
						Fmake_array(ARG(17), 7);
						COPY(ARG(17), ARG(18));
						make_string_output_stream1(ARG(18));
						COPY(ARG(18), ARG(17));
						COPY(ARG(16), ARG(18));
						COPY(ARG(17), ARG(19));
						prin11(ARG(18));
						COPY(ARG(17), ARG(18));
						Fget_output_stream_string(ARG(18));
						mv_count = 1;
						COPY(ARG(18), ARG(17));
					}
					ENDIF6:;
					COPY(ARG(17), ARG(18));
					Flength(ARG(18));
					if(CL_TRUEP(ARG(13)))
					{
						DOWN_FUNARG downfun1;
						INIT_DOWN_FUNARG(downfun1, Z45_padding, -2, display);
						LOAD_DOWNFUN(&downfun1, ARG(19));
						COPY(ARG(18), ARG(20));
						COPY(ARG(11), ARG(21));
						display[0] = ARG(0);
						Fapply(ARG(19), 3);
						mv_count = 1;
						COPY(ARG(17), ARG(19));
						COPY(ARG(0), ARG(20));
						princ1(ARG(19));
					}
					else
					{
						COPY(ARG(17), ARG(19));
						COPY(ARG(0), ARG(20));
						princ1(ARG(19));
						{
							DOWN_FUNARG downfun1;
							INIT_DOWN_FUNARG(downfun1, Z45_padding, -2, display);
							LOAD_DOWNFUN(&downfun1, ARG(19));
							COPY(ARG(18), ARG(20));
							COPY(ARG(11), ARG(21));
							display[0] = ARG(0);
							Fapply(ARG(19), 3);
							mv_count = 1;
						}
					}
				}
				else
				{
					if(CL_TRUEP(ARG(14)))
					{
						display[0] = ARG(0);
						Z37_get_arg(ARG(16), display);
						if(CL_TRUEP(ARG(16)))
						{
							COPY(ARG(16), ARG(17));
							COPY(ARG(0), ARG(18));
							prin11(ARG(17));
						}
						else
						{
							LOAD_SMSTR((CL_FORM *)&Kformat21[20], ARG(17));	/* () */
							COPY(ARG(0), ARG(18));
							princ1(ARG(17));
						}
					}
					else
					{
						display[0] = ARG(0);
						Z37_get_arg(ARG(16), display);
						COPY(ARG(16), ARG(17));
						COPY(ARG(0), ARG(18));
						prin11(ARG(17));
					}
				}
			}
			else
			{
				if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'D')
				{
					COPY(ARG(0), ARG(16));
					COPY(ARG(16), ARG(17));
					COPY(ARG(17), ARG(18));
					LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(19));	/* STREAM */
					rt_struct_typep(ARG(18));
					if(CL_TRUEP(ARG(18)))
					{
						COPY(OFFSET(AR_BASE(GET_FORM(ARG(17))), 5 + 1), ARG(16));
					}
					else
					{
						COPY(SYMVAL(Slisp, 352), ARG(18));	/* NO_STRUCT */
						COPY(ARG(17), ARG(19));
						LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(20));	/* STREAM */
						Ferror(ARG(18), 3);
					}
					Ffuncall(ARG(16), 1);
					mv_count = 1;
					display[0] = ARG(0);
					Z37_get_arg(ARG(17), display);
					LOAD_NIL(ARG(18));
					BIND_SPECIAL(SYMBOL(Slisp, 479), ARG(18));	/* *PRINT-RADIX* */
					LOAD_FIXNUM(ARG(19), 10, ARG(19));
					BIND_SPECIAL(SYMBOL(Slisp, 471), ARG(19));	/* *PRINT-BASE* */
					if(CL_FIXNUMP(ARG(17)))
					{
						if(CL_TRUEP(ARG(13)))
						{
							COPY(ARG(17), ARG(20));
							Fplusp(ARG(20));
						}
						else
						{
							goto ELSE7;
						}
					}
					else
					{
						goto ELSE7;
					}
					if(CL_TRUEP(ARG(20)))
					{
						LOAD_CHAR(ARG(20), '+', ARG(20));
						COPY(ARG(0), ARG(21));
						write_char1(ARG(20));
						mv_count = 1;
					}
					ELSE7:;
					COPY(ARG(17), ARG(20));
					COPY(ARG(0), ARG(21));
					princ1(ARG(20));
					COPY(ARG(12), ARG(20));
					COPY(ARG(16), ARG(21));
					display[0] = ARG(0);
					Z43_insert_space(ARG(20), display);
					RESTORE_SPECIAL;
					RESTORE_SPECIAL;
				}
				else
				{
					if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'B')
					{
						COPY(ARG(0), ARG(16));
						COPY(ARG(16), ARG(17));
						COPY(ARG(17), ARG(18));
						LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(19));	/* STREAM */
						rt_struct_typep(ARG(18));
						if(CL_TRUEP(ARG(18)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(17))), 5 + 1), ARG(16));
						}
						else
						{
							COPY(SYMVAL(Slisp, 352), ARG(18));	/* NO_STRUCT */
							COPY(ARG(17), ARG(19));
							LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(20));	/* STREAM */
							Ferror(ARG(18), 3);
						}
						Ffuncall(ARG(16), 1);
						mv_count = 1;
						LOAD_NIL(ARG(17));
						BIND_SPECIAL(SYMBOL(Slisp, 479), ARG(17));	/* *PRINT-RADIX* */
						LOAD_FIXNUM(ARG(18), 2, ARG(18));
						BIND_SPECIAL(SYMBOL(Slisp, 471), ARG(18));	/* *PRINT-BASE* */
						display[0] = ARG(0);
						Z37_get_arg(ARG(19), display);
						COPY(ARG(19), ARG(20));
						COPY(ARG(0), ARG(21));
						princ1(ARG(20));
						COPY(ARG(12), ARG(19));
						COPY(ARG(16), ARG(20));
						display[0] = ARG(0);
						Z43_insert_space(ARG(19), display);
						RESTORE_SPECIAL;
						RESTORE_SPECIAL;
					}
					else
					{
						if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'O')
						{
							COPY(ARG(0), ARG(16));
							COPY(ARG(16), ARG(17));
							COPY(ARG(17), ARG(18));
							LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(19));	/* STREAM */
							rt_struct_typep(ARG(18));
							if(CL_TRUEP(ARG(18)))
							{
								COPY(OFFSET(AR_BASE(GET_FORM(ARG(17))), 5 + 1), ARG(16));
							}
							else
							{
								COPY(SYMVAL(Slisp, 352), ARG(18));	/* NO_STRUCT */
								COPY(ARG(17), ARG(19));
								LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(20));	/* STREAM */
								Ferror(ARG(18), 3);
							}
							Ffuncall(ARG(16), 1);
							mv_count = 1;
							LOAD_NIL(ARG(17));
							BIND_SPECIAL(SYMBOL(Slisp, 479), ARG(17));	/* *PRINT-RADIX* */
							LOAD_FIXNUM(ARG(18), 8, ARG(18));
							BIND_SPECIAL(SYMBOL(Slisp, 471), ARG(18));	/* *PRINT-BASE* */
							display[0] = ARG(0);
							Z37_get_arg(ARG(19), display);
							COPY(ARG(19), ARG(20));
							COPY(ARG(0), ARG(21));
							princ1(ARG(20));
							COPY(ARG(12), ARG(19));
							COPY(ARG(16), ARG(20));
							display[0] = ARG(0);
							Z43_insert_space(ARG(19), display);
							RESTORE_SPECIAL;
							RESTORE_SPECIAL;
						}
						else
						{
							if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'P')
							{
								if(CL_TRUEP(ARG(14)))
								{
									COPY(ARG(8), ARG(16));
								}
								else
								{
									display[0] = ARG(0);
									Z37_get_arg(ARG(16), display);
								}
								if(CL_FIXNUMP(ARG(16)) && GET_FIXNUM(ARG(16)) == 1)
								{
									if(CL_TRUEP(ARG(13)))
									{
										LOAD_CHAR(ARG(17), 'y', ARG(17));
										COPY(ARG(0), ARG(18));
										write_char1(ARG(17));
										mv_count = 1;
									}
								}
								else
								{
									if(CL_TRUEP(ARG(13)))
									{
										LOAD_SMSTR((CL_FORM *)&Kformat21[22], ARG(17));	/* ies */
										COPY(ARG(0), ARG(18));
										princ1(ARG(17));
									}
									else
									{
										LOAD_CHAR(ARG(17), 's', ARG(17));
										COPY(ARG(0), ARG(18));
										write_char1(ARG(17));
										mv_count = 1;
									}
								}
							}
							else
							{
								if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'F')
								{
									COPY(ARG(0), ARG(16));
									COPY(ARG(16), ARG(17));
									COPY(ARG(17), ARG(18));
									LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(19));	/* STREAM */
									rt_struct_typep(ARG(18));
									if(CL_TRUEP(ARG(18)))
									{
										COPY(OFFSET(AR_BASE(GET_FORM(ARG(17))), 5 + 1), ARG(16));
									}
									else
									{
										COPY(SYMVAL(Slisp, 352), ARG(18));	/* NO_STRUCT */
										COPY(ARG(17), ARG(19));
										LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(20));	/* STREAM */
										Ferror(ARG(18), 3);
									}
									Ffuncall(ARG(16), 1);
									mv_count = 1;
									display[0] = ARG(0);
									Z37_get_arg(ARG(17), display);
									COPY(ARG(17), ARG(18));
									COPY(ARG(0), ARG(19));
									princ1(ARG(18));
									COPY(ARG(12), ARG(17));
									COPY(ARG(16), ARG(18));
									display[0] = ARG(0);
									Z43_insert_space(ARG(17), display);
								}
								else
								{
									if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '%')
									{
										if(CL_NUMBERP(ARG(12)))
										{
											LOAD_FIXNUM(ARG(16), 0, ARG(16));
											M2_1:;
											COPY(ARG(16), ARG(17));
											COPY(ARG(12), ARG(18));
											Fge(ARG(17), 2);
											if(CL_TRUEP(ARG(17)))
											{
												goto RETURN3;
											}
											COPY(ARG(0), ARG(17));
											terpri1(ARG(17));
											COPY(ARG(16), ARG(17));
											F1plus(ARG(17));
											COPY(ARG(17), ARG(16));
											goto M2_1;
											RETURN3:;
										}
										else
										{
											COPY(ARG(0), ARG(16));
											terpri1(ARG(16));
										}
									}
									else
									{
										if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '&')
										{
											if(CL_NUMBERP(ARG(12)))
											{
												COPY(ARG(12), ARG(16));
												Fzerop(ARG(16));
												if(CL_TRUEP(ARG(16)))
												{
												}
												else
												{
													COPY(ARG(0), ARG(16));
													fresh_line1(ARG(16));
													mv_count = 1;
													LOAD_FIXNUM(ARG(16), 0, ARG(16));
													M3_1:;
													COPY(ARG(16), ARG(17));
													COPY(ARG(12), ARG(18));
													F1minus(ARG(18));
													Fge(ARG(17), 2);
													if(CL_TRUEP(ARG(17)))
													{
														goto RETURN4;
													}
													COPY(ARG(0), ARG(17));
													terpri1(ARG(17));
													COPY(ARG(16), ARG(17));
													F1plus(ARG(17));
													COPY(ARG(17), ARG(16));
													goto M3_1;
													RETURN4:;
												}
											}
											else
											{
												COPY(ARG(0), ARG(16));
												fresh_line1(ARG(16));
												mv_count = 1;
											}
										}
										else
										{
											if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '|')
											{
												if(CL_NUMBERP(ARG(12)))
												{
													LOAD_FIXNUM(ARG(16), 0, ARG(16));
													M4_1:;
													COPY(ARG(16), ARG(17));
													COPY(ARG(12), ARG(18));
													Fge(ARG(17), 2);
													if(CL_TRUEP(ARG(17)))
													{
														goto RETURN5;
													}
													LOAD_CHAR(ARG(17), '\f', ARG(17));
													COPY(ARG(0), ARG(18));
													write_char1(ARG(17));
													mv_count = 1;
													COPY(ARG(16), ARG(17));
													F1plus(ARG(17));
													COPY(ARG(17), ARG(16));
													goto M4_1;
													RETURN5:;
												}
												else
												{
													LOAD_CHAR(ARG(16), '\f', ARG(16));
													COPY(ARG(0), ARG(17));
													write_char1(ARG(16));
													mv_count = 1;
												}
											}
											else
											{
												if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '~')
												{
													if(CL_NUMBERP(ARG(12)))
													{
														LOAD_FIXNUM(ARG(16), 0, ARG(16));
														M5_1:;
														COPY(ARG(16), ARG(17));
														COPY(ARG(12), ARG(18));
														Fge(ARG(17), 2);
														if(CL_TRUEP(ARG(17)))
														{
															goto RETURN6;
														}
														LOAD_CHAR(ARG(17), '~', ARG(17));
														COPY(ARG(0), ARG(18));
														write_char1(ARG(17));
														mv_count = 1;
														COPY(ARG(16), ARG(17));
														F1plus(ARG(17));
														COPY(ARG(17), ARG(16));
														goto M5_1;
														RETURN6:;
													}
													else
													{
														LOAD_CHAR(ARG(16), '~', ARG(16));
														COPY(ARG(0), ARG(17));
														write_char1(ARG(16));
														mv_count = 1;
													}
												}
												else
												{
													if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '\n')
													{
														if(CL_TRUEP(ARG(13)))
														{
															if(CL_TRUEP(ARG(14)))
															{
																LOAD_SMSTR((CL_FORM *)&Kformat21[24], ARG(16));	/* illegal directive ~~:@p */
																Ferror(ARG(16), 1);
															}
															COPY(ARG(0), ARG(16));
															terpri1(ARG(16));
														}
														if(CL_TRUEP(ARG(14)))
														{
														}
														else
														{
															M6_1:;
															display[0] = ARG(0);
															Z38_get_ctrl(ARG(16), display);
															COPY(ARG(16), ARG(10));
															if(CL_TRUEP(ARG(10)))
															{
															}
															else
															{
																goto RETURN7;
															}
															if(CL_CHARP(ARG(10)) && GET_CHAR(ARG(10)) == ' ')
															{
															}
															else
															{
																COPY(ARG(3), ARG(16));
																F1minus(ARG(16));
																COPY(ARG(16), ARG(3));
																goto RETURN7;
															}
															goto M6_1;
															RETURN7:;
														}
													}
													else
													{
														if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == 'T')
														{
															DOWN_FUNARG downfun1;
															INIT_DOWN_FUNARG(downfun1, Z44_tabbing, -2, display);
															LOAD_DOWNFUN(&downfun1, ARG(16));
															COPY(ARG(13), ARG(17));
															COPY(ARG(11), ARG(18));
															display[0] = ARG(0);
															Fapply(ARG(16), 3);
															mv_count = 1;
														}
														else
														{
															if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '*')
															{
																if(CL_TRUEP(ARG(13)))
																{
																	if(CL_TRUEP(ARG(14)))
																	{
																		LOAD_SMSTR((CL_FORM *)&Kformat21[26], ARG(16));	/* illegal directive ~~:@* */
																		Ferror(ARG(16), 1);
																	}
																	if(CL_NUMBERP(ARG(12)))
																	{
																	}
																	else
																	{
																		LOAD_FIXNUM(ARG(16), 0, ARG(12));
																	}
																	COPY(ARG(12), ARG(16));
																	display[0] = ARG(0);
																	Z36_goto(ARG(16), display);
																}
																else
																{
																	if(CL_TRUEP(ARG(14)))
																	{
																		if(CL_NUMBERP(ARG(12)))
																		{
																		}
																		else
																		{
																			LOAD_FIXNUM(ARG(16), 1, ARG(12));
																		}
																		COPY(ARG(12), ARG(16));
																		COPY(ARG(7), ARG(17));
																		Fgt(ARG(16), 2);
																		if(CL_TRUEP(ARG(16)))
																		{
																			LOAD_SMSTR((CL_FORM *)&Kformat21[28], ARG(16));	/* ~~~a:* will skip to nonexistant argument */
																			COPY(ARG(12), ARG(17));
																			Ferror(ARG(16), 2);
																		}
																		COPY(ARG(7), ARG(16));
																		COPY(ARG(12), ARG(17));
																		Fminus(ARG(16), 2);
																		display[0] = ARG(0);
																		Z36_goto(ARG(16), display);
																	}
																	else
																	{
																		if(CL_NUMBERP(ARG(12)))
																		{
																		}
																		else
																		{
																			LOAD_FIXNUM(ARG(16), 1, ARG(12));
																		}
																		LOAD_FIXNUM(ARG(16), 0, ARG(16));
																		M7_1:;
																		COPY(ARG(16), ARG(17));
																		COPY(ARG(12), ARG(18));
																		Fge(ARG(17), 2);
																		if(CL_TRUEP(ARG(17)))
																		{
																			goto RETURN8;
																		}
																		display[0] = ARG(0);
																		Z37_get_arg(ARG(17), display);
																		COPY(ARG(16), ARG(17));
																		F1plus(ARG(17));
																		COPY(ARG(17), ARG(16));
																		goto M7_1;
																		RETURN8:;
																	}
																}
															}
															else
															{
																if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '?')
																{
																	COPY(ARG(0), ARG(16));
																	display[0] = ARG(0);
																	Z37_get_arg(ARG(17), display);
																	display[0] = ARG(0);
																	Z37_get_arg(ARG(18), display);
																	format2(ARG(16), 3);
																	mv_count = 1;
																}
																else
																{
																	if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == ';')
																	{
																		LOAD_BOOL(CL_CHARP(ARG(5)) && GET_CHAR(ARG(5)) == ';', ARG(16));
																		if(CL_TRUEP(ARG(16)))
																		{
																			goto THEN8;
																		}
																		else
																		{
																		}
																		if(CL_CHARP(ARG(4)) && GET_CHAR(ARG(4)) == ';')
																		{
																			THEN8:;
																			COPY(ARG(6), ARG(16));
																			COPY(ARG(3), ARG(17));
																			LOAD_CHAR(ARG(18), ';', ARG(18));
																			COPY(ARG(16), ARG(0));
																			COPY(ARG(17), &mv_buf[0]);
																			COPY(ARG(18), &mv_buf[1]);
																			mv_count = 3;
																			goto RETURN1;
																		}
																		else
																		{
																			LOAD_SMSTR((CL_FORM *)&Kformat21[30], ARG(16));	/* unexpected ~~; in control-string */
																			Ferror(ARG(16), 1);
																		}
																	}
																	else
																	{
																		if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '[')
																		{
																			if(CL_TRUEP(ARG(14)))
																			{
																			}
																			else
																			{
																				goto ELSE9;
																			}
																			if(CL_TRUEP(ARG(13)))
																			{
																				LOAD_SMSTR((CL_FORM *)&Kformat21[32], ARG(16));	/* Illegal directive ~~:@[ */
																				Ferror(ARG(16), 1);
																			}
																			else
																			{
																				ELSE9:;
																				if(CL_TRUEP(ARG(14)))
																				{
																					display[0] = ARG(0);
																					Z37_get_arg(ARG(16), display);
																					if(CL_TRUEP(ARG(16)))
																					{
																						LOAD_CHAR(ARG(16), ';', ARG(16));
																						display[0] = ARG(0);
																						Z42_skip(ARG(16), display, 1);
																						COPY(ARG(0), ARG(16));
																						COPY(ARG(1), ARG(17));
																						COPY(ARG(6), ARG(18));
																						COPY(ARG(3), ARG(19));
																						LOAD_CHAR(ARG(20), ']', ARG(20));
																						LOAD_NIL(ARG(21));
																						format21(ARG(16));
																						MV_TO_STACK(mv_count, 17);
																						{
																							int nargs;
																							nargs = mv_count;
																							mv_count = 1;
																							{
																								switch(nargs)
																								{
																									case 0:
																									LOAD_NIL(ARG(16));
																									case 1:
																									LOAD_NIL(ARG(17));
																									nargs = 2;
																								}
																								COPY(ARG(16), ARG(6));
																								COPY(ARG(17), ARG(3));
																							}
																						}
																					}
																					else
																					{
																						COPY(ARG(0), ARG(16));
																						COPY(ARG(1), ARG(17));
																						COPY(ARG(6), ARG(18));
																						COPY(ARG(3), ARG(19));
																						LOAD_CHAR(ARG(20), ';', ARG(20));
																						LOAD_NIL(ARG(21));
																						format21(ARG(16));
																						MV_TO_STACK(mv_count, 17);
																						{
																							int nargs;
																							nargs = mv_count;
																							mv_count = 1;
																							{
																								switch(nargs)
																								{
																									case 0:
																									LOAD_NIL(ARG(16));
																									case 1:
																									LOAD_NIL(ARG(17));
																									nargs = 2;
																								}
																								COPY(ARG(16), ARG(6));
																								COPY(ARG(17), ARG(3));
																							}
																						}
																						LOAD_CHAR(ARG(16), ']', ARG(16));
																						display[0] = ARG(0);
																						Z42_skip(ARG(16), display, 1);
																					}
																				}
																				else
																				{
																					if(CL_TRUEP(ARG(13)))
																					{
																						COPY(ARG(6), ARG(16));
																						display[0] = ARG(0);
																						Z37_get_arg(ARG(17), display);
																						if(CL_TRUEP(ARG(17)))
																						{
																							COPY(ARG(0), ARG(17));
																							COPY(ARG(1), ARG(18));
																							COPY(ARG(16), ARG(19));
																							COPY(ARG(3), ARG(20));
																							LOAD_CHAR(ARG(21), ']', ARG(21));
																							LOAD_NIL(ARG(22));
																							format21(ARG(17));
																							MV_TO_STACK(mv_count, 18);
																							{
																								int nargs;
																								nargs = mv_count;
																								mv_count = 1;
																								{
																									switch(nargs)
																									{
																										case 0:
																										LOAD_NIL(ARG(17));
																										case 1:
																										LOAD_NIL(ARG(18));
																										nargs = 2;
																									}
																									COPY(ARG(17), ARG(6));
																									COPY(ARG(18), ARG(3));
																								}
																							}
																						}
																					}
																					else
																					{
																						if(CL_TRUEP(ARG(12)))
																						{
																							COPY(ARG(12), ARG(16));
																						}
																						else
																						{
																							display[0] = ARG(0);
																							Z37_get_arg(ARG(16), display);
																						}
																						M8_1:;
																						if(CL_FIXNUMP(ARG(16)) && GET_FIXNUM(ARG(16)) == 0)
																						{
																							LOAD_NIL(ARG(17));
																							COPY(ARG(0), ARG(18));
																							COPY(ARG(1), ARG(19));
																							COPY(ARG(6), ARG(20));
																							COPY(ARG(3), ARG(21));
																							LOAD_CHAR(ARG(22), ']', ARG(22));
																							LOAD_CHAR(ARG(23), ';', ARG(23));
																							format21(ARG(18));
																							MV_TO_STACK(mv_count, 19);
																							{
																								int nargs;
																								nargs = mv_count;
																								mv_count = 1;
																								{
																									switch(nargs)
																									{
																										case 0:
																										LOAD_NIL(ARG(18));
																										case 1:
																										LOAD_NIL(ARG(19));
																										case 2:
																										LOAD_NIL(ARG(20));
																										nargs = 3;
																									}
																									COPY(ARG(18), ARG(6));
																									COPY(ARG(19), ARG(3));
																									COPY(ARG(20), ARG(17));
																								}
																							}
																							if(CL_CHARP(ARG(17)) && GET_CHAR(ARG(17)) == ';')
																							{
																								LOAD_CHAR(ARG(18), ']', ARG(18));
																								display[0] = ARG(0);
																								Z42_skip(ARG(18), display, 1);
																							}
																							goto RETURN9;
																						}
																						LOAD_CHAR(ARG(17), ']', ARG(17));
																						LOAD_CHAR(ARG(18), ';', ARG(18));
																						display[0] = ARG(0);
																						Z42_skip(ARG(17), display, 2);
																						if(CL_CHARP(ARG(17)) && GET_CHAR(ARG(17)) == ';')
																						{
																							if(CL_TRUEP(ARG(14)))
																							{
																								COPY(ARG(0), ARG(17));
																								COPY(ARG(1), ARG(18));
																								COPY(ARG(6), ARG(19));
																								COPY(ARG(3), ARG(20));
																								LOAD_CHAR(ARG(21), ']', ARG(21));
																								LOAD_NIL(ARG(22));
																								format21(ARG(17));
																								MV_TO_STACK(mv_count, 18);
																								{
																									int nargs;
																									nargs = mv_count;
																									mv_count = 1;
																									{
																										switch(nargs)
																										{
																											case 0:
																											LOAD_NIL(ARG(17));
																											case 1:
																											LOAD_NIL(ARG(18));
																											nargs = 2;
																										}
																										COPY(ARG(17), ARG(6));
																										COPY(ARG(18), ARG(3));
																									}
																								}
																								goto RETURN9;
																							}
																							else
																							{
																								COPY(ARG(16), ARG(17));
																								F1minus(ARG(17));
																								COPY(ARG(17), ARG(16));
																							}
																						}
																						else
																						{
																							goto RETURN9;
																						}
																						goto M8_1;
																						RETURN9:;
																					}
																				}
																			}
																		}
																		else
																		{
																			if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == ']')
																			{
																				if(CL_CHARP(ARG(4)) && GET_CHAR(ARG(4)) == ']')
																				{
																					COPY(ARG(6), ARG(16));
																					COPY(ARG(3), ARG(17));
																					LOAD_CHAR(ARG(18), ']', ARG(18));
																					COPY(ARG(16), ARG(0));
																					COPY(ARG(17), &mv_buf[0]);
																					COPY(ARG(18), &mv_buf[1]);
																					mv_count = 3;
																					goto RETURN1;
																				}
																				else
																				{
																					LOAD_SMSTR((CL_FORM *)&Kformat21[34], ARG(16));	/* unexpected ~~} in control-string */
																					Ferror(ARG(16), 1);
																				}
																			}
																			else
																			{
																				if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '{')
																				{
																					display[0] = ARG(0);
																					Z37_get_arg(ARG(16), display);
																					LOAD_NIL(ARG(17));
																					if(CL_TRUEP(ARG(12)))
																					{
																					}
																					else
																					{
																						LOAD_FIXNUM(ARG(18), -1, ARG(12));
																					}
																					M9_1:;
																					if(CL_TRUEP(ARG(16)))
																					{
																					}
																					else
																					{
																						goto RETURN10;
																					}
																					if(CL_FIXNUMP(ARG(12)) && GET_FIXNUM(ARG(12)) == 0)
																					{
																						goto RETURN10;
																					}
																					COPY(ARG(0), ARG(18));
																					COPY(ARG(1), ARG(19));
																					COPY(ARG(16), ARG(20));
																					COPY(ARG(3), ARG(21));
																					LOAD_CHAR(ARG(22), '}', ARG(22));
																					LOAD_NIL(ARG(23));
																					format21(ARG(18));
																					MV_TO_STACK(mv_count, 19);
																					{
																						int nargs;
																						nargs = mv_count;
																						mv_count = 1;
																						{
																							switch(nargs)
																							{
																								case 0:
																								LOAD_NIL(ARG(18));
																								case 1:
																								LOAD_NIL(ARG(19));
																								nargs = 2;
																							}
																							COPY(ARG(18), ARG(16));
																							COPY(ARG(19), ARG(17));
																						}
																					}
																					COPY(ARG(12), ARG(18));
																					F1minus(ARG(18));
																					COPY(ARG(18), ARG(12));
																					goto M9_1;
																					RETURN10:;
																					if(CL_TRUEP(ARG(17)))
																					{
																						COPY(ARG(17), ARG(3));
																					}
																					else
																					{
																						COPY(ARG(3), ARG(18));
																						LOAD_CHAR(ARG(19), '}', ARG(19));
																						display[0] = ARG(0);
																						Z42_skip(ARG(19), display, 1);
																						if(CL_TRUEP(ARG(14)))
																						{
																							if(CL_FIXNUMP(ARG(12)) && GET_FIXNUM(ARG(12)) == 0)
																							{
																								goto ELSE10;
																							}
																							else
																							{
																								goto THEN11;
																							}
																						}
																						else
																						{
																							goto ELSE10;
																						}
																						{
																							THEN11:;
																							COPY(ARG(0), ARG(19));
																							COPY(ARG(1), ARG(20));
																							COPY(ARG(16), ARG(21));
																							COPY(ARG(18), ARG(22));
																							LOAD_CHAR(ARG(23), '}', ARG(23));
																							LOAD_NIL(ARG(24));
																							format21(ARG(19));
																							MV_TO_STACK(mv_count, 20);
																							{
																								int nargs;
																								nargs = mv_count;
																								mv_count = 1;
																								{
																									switch(nargs)
																									{
																										case 0:
																										LOAD_NIL(ARG(19));
																										case 1:
																										LOAD_NIL(ARG(20));
																										nargs = 2;
																									}
																									COPY(ARG(19), ARG(16));
																									COPY(ARG(20), ARG(17));
																								}
																							}
																						}
																						ELSE10:;
																					}
																				}
																				else
																				{
																					if(CL_CHARP(ARG(15)) && GET_CHAR(ARG(15)) == '}')
																					{
																						if(CL_CHARP(ARG(4)) && GET_CHAR(ARG(4)) == '}')
																						{
																							COPY(ARG(6), ARG(16));
																							COPY(ARG(3), ARG(17));
																							COPY(ARG(16), ARG(0));
																							COPY(ARG(17), &mv_buf[0]);
																							mv_count = 2;
																							goto RETURN1;
																						}
																						else
																						{
																							LOAD_SMSTR((CL_FORM *)&Kformat21[36], ARG(16));	/* unexpected ~~} in control-string */
																							Ferror(ARG(16), 1);
																						}
																					}
																					else
																					{
																						LOAD_SMSTR((CL_FORM *)&Kformat21[38], ARG(16));	/* illegal / unimplemented directive (~A) in ~
                          control-string */
																						COPY(ARG(10), ARG(17));
																						Ferror(ARG(16), 2);
																					}
																				}
																			}
																		}
																	}
																}
															}
														}
													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	else
	{
		COPY(ARG(10), ARG(15));
		COPY(ARG(0), ARG(16));
		write_char1(ARG(15));
		mv_count = 1;
	}
	goto M1_1;
	RETURN2:;
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_SMSTR((CL_FORM *)&Kformat21[40], ARG(6));	/* unexpected end of control-string */
		Ferror(ARG(6), 1);
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
	RETURN1:;
}

static void Z36_goto(CL_FORM *base, CL_FORM *display[])
{
	if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 0)
	{
		COPY(&display[0][2], &display[0][6]);
		LOAD_FIXNUM(ARG(1), 0, &display[0][7]);
		LOAD_NIL(&display[0][8]);
		COPY(&display[0][8], ARG(0));
	}
	else
	{
		COPY(&display[0][2], ARG(1));
		COPY(ARG(0), ARG(2));
		F1minus(ARG(2));
		Fnthcdr(ARG(1));
		COPY(ARG(1), &display[0][6]);
		COPY(ARG(0), &display[0][7]);
		Z37_get_arg(ARG(0), display);
	}
}

static void Z37_get_arg(CL_FORM *base, CL_FORM *display[])
{
	if(CL_TRUEP(&display[0][6]))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kformat21[0], ARG(0));	/* Not enough arguments for format */
		Ferror(ARG(0), 1);
	}
	COPY(&display[0][7], ARG(0));
	F1plus(ARG(0));
	COPY(ARG(0), &display[0][7]);
	COPY(&display[0][6], ARG(0));
	COPY(ARG(0), ARG(1));
	if(CL_CONSP(ARG(1)))
	{
		COPY(GET_CAR(ARG(1)), ARG(0));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(0));	/* ~a is not a list */
			Ferror(ARG(0), 2);
		}
		else
		{
			COPY(ARG(1), ARG(0));
		}
	}
	COPY(&display[0][6], ARG(1));
	COPY(ARG(1), ARG(2));
	if(CL_CONSP(ARG(2)))
	{
		COPY(GET_CDR(ARG(2)), &display[0][6]);
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(3));	/* ~a is not a list */
			COPY(ARG(2), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
			COPY(ARG(2), &display[0][6]);
		}
	}
	COPY(ARG(0), &display[0][8]);
}

static void Z38_get_ctrl(CL_FORM *base, CL_FORM *display[])
{
	COPY(&display[0][3], ARG(0));
	COPY(&display[0][9], ARG(1));
	Fge(ARG(0), 2);
	if(CL_TRUEP(ARG(0)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(&display[0][1], ARG(0));
		COPY(&display[0][3], ARG(1));
		Fchar(ARG(0));
		COPY(&display[0][3], ARG(1));
		F1plus(ARG(1));
		COPY(ARG(1), &display[0][3]);
	}
}

static void Z39_get_params(CL_FORM *base, CL_FORM *display[])
{
	LOAD_NIL(ARG(0));
	LOAD_NIL(ARG(1));
	LOAD_NIL(ARG(2));
	LOAD_NIL(ARG(3));
	LOAD_NIL(ARG(4));
	ALLOC_CONS(ARG(5), ARG(3), ARG(4), &display[0][11]);
	M1_1:;
	COPY(&display[0][3], ARG(3));
	COPY(&display[0][9], ARG(4));
	Fge(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		goto RETURN1;
	}
	COPY(&display[0][1], ARG(3));
	COPY(&display[0][3], ARG(4));
	Fchar(ARG(3));
	COPY(ARG(3), ARG(0));
	if(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == '#')
	{
		COPY(&display[0][6], ARG(3));
		Flength(ARG(3));
		COPY(&display[0][11], ARG(4));
		add_q(ARG(3));
		COPY(&display[0][3], ARG(3));
		F1plus(ARG(3));
		COPY(ARG(3), &display[0][3]);
	}
	else
	{
		LOAD_BOOL(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == 'V', ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			goto THEN1;
		}
		else
		{
		}
		if(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == 'v')
		{
			THEN1:;
			Z37_get_arg(ARG(3), display);
			COPY(&display[0][11], ARG(4));
			add_q(ARG(3));
			COPY(&display[0][3], ARG(3));
			F1plus(ARG(3));
			COPY(ARG(3), &display[0][3]);
		}
		else
		{
			if(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == ',')
			{
				LOAD_NIL(ARG(3));
				COPY(&display[0][11], ARG(4));
				add_q(ARG(3));
			}
			else
			{
				COPY(ARG(0), ARG(3));
				COPY(ARG(3), ARG(4));
				LOAD_FIXNUM(ARG(5), 10, ARG(5));
				digit_char_p1(ARG(4));
				COPY(ARG(4), ARG(1));
				if(CL_TRUEP(ARG(1)))
				{
					M2_1:;
					COPY(&display[0][3], ARG(3));
					F1plus(ARG(3));
					COPY(ARG(3), &display[0][3]);
					COPY(&display[0][9], ARG(4));
					Fge(ARG(3), 2);
					if(CL_TRUEP(ARG(3)))
					{
						COPY(ARG(1), ARG(3));
						COPY(&display[0][11], ARG(4));
						add_q(ARG(3));
						goto RETURN2;
					}
					COPY(&display[0][1], ARG(3));
					COPY(&display[0][3], ARG(4));
					Fchar(ARG(3));
					COPY(ARG(3), ARG(0));
					COPY(ARG(3), ARG(2));
					LOAD_FIXNUM(ARG(3), 10, ARG(3));
					digit_char_p1(ARG(2));
					if(CL_TRUEP(ARG(2)))
					{
					}
					else
					{
						COPY(ARG(1), ARG(3));
						COPY(&display[0][11], ARG(4));
						add_q(ARG(3));
						goto RETURN2;
					}
					LOAD_FIXNUM(ARG(3), 10, ARG(3));
					COPY(ARG(1), ARG(4));
					Fmult(ARG(3), 2);
					COPY(ARG(2), ARG(4));
					Fplus(ARG(3), 2);
					COPY(ARG(3), ARG(1));
					goto M2_1;
					RETURN2:;
				}
			}
		}
	}
	COPY(&display[0][3], ARG(3));
	COPY(&display[0][9], ARG(4));
	Flt(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		COPY(&display[0][1], ARG(3));
		COPY(&display[0][3], ARG(4));
		Fchar(ARG(3));
	}
	else
	{
		goto ELSE2;
	}
	if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == ',')
	{
		COPY(&display[0][3], ARG(3));
		F1plus(ARG(3));
		COPY(ARG(3), &display[0][3]);
	}
	else
	{
		ELSE2:;
		goto RETURN1;
	}
	goto M1_1;
	RETURN1:;
	COPY(&display[0][11], ARG(3));
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), &display[0][11]);
	COPY(&display[0][11], ARG(0));
}

static void Z40_get_at_sign_or_colon(CL_FORM *base, CL_FORM *display[])
{
	LOAD_NIL(&display[0][13]);
	LOAD_NIL(&display[0][14]);
	M1_1:;
	COPY(&display[0][3], ARG(0));
	COPY(&display[0][9], ARG(1));
	Fge(ARG(0), 2);
	if(CL_TRUEP(ARG(0)))
	{
		LOAD_SMSTR((CL_FORM *)&Kformat21[2], ARG(0));	/* Syntax error at end of control-string: ~s */
		COPY(&display[0][1], ARG(1));
		Ferror(ARG(0), 2);
	}
	else
	{
		COPY(&display[0][1], ARG(0));
		COPY(&display[0][3], ARG(1));
		Fchar(ARG(0));
		if(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == '@')
		{
			if(CL_TRUEP(&display[0][13]))
			{
				LOAD_SMSTR((CL_FORM *)&Kformat21[4], ARG(0));	/* Too many at-signs supplied. */
				Ferror(ARG(0), 1);
			}
			LOAD_SYMBOL(SYMBOL(Slisp, 48), &display[0][13]);	/* T */
			COPY(&display[0][3], ARG(0));
			F1plus(ARG(0));
			COPY(ARG(0), &display[0][3]);
		}
		else
		{
			COPY(&display[0][1], ARG(0));
			COPY(&display[0][3], ARG(1));
			Fchar(ARG(0));
			if(CL_CHARP(ARG(0)) && GET_CHAR(ARG(0)) == ':')
			{
				if(CL_TRUEP(&display[0][14]))
				{
					LOAD_SMSTR((CL_FORM *)&Kformat21[6], ARG(0));	/* Too many colons supplied. */
					Ferror(ARG(0), 1);
				}
				LOAD_SYMBOL(SYMBOL(Slisp, 48), &display[0][14]);	/* T */
				COPY(&display[0][3], ARG(0));
				F1plus(ARG(0));
				COPY(ARG(0), &display[0][3]);
			}
			else
			{
				LOAD_NIL(ARG(0));
				goto RETURN1;
			}
		}
	}
	goto M1_1;
	RETURN1:;
}

static void Z41_get_directive(CL_FORM *base, CL_FORM *display[])
{
	COPY(&display[0][3], ARG(0));
	COPY(&display[0][9], ARG(1));
	Fge(ARG(0), 2);
	if(CL_TRUEP(ARG(0)))
	{
		LOAD_SMSTR((CL_FORM *)&Kformat21[8], ARG(0));	/* Syntax error at end of control-string: ~s */
		COPY(&display[0][1], ARG(1));
		Ferror(ARG(0), 2);
	}
	else
	{
		COPY(&display[0][1], ARG(0));
		COPY(&display[0][3], ARG(1));
		Fchar(ARG(0));
		COPY(&display[0][3], ARG(1));
		F1plus(ARG(1));
		COPY(ARG(1), &display[0][3]);
	}
}

static void Z42_skip(CL_FORM *base, CL_FORM *display[], int nargs)
{
	switch(nargs)
	{
		case 1:
		LOAD_NIL(ARG(1));
		case 2:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	M1_1:;
	Z38_get_ctrl(ARG(2), display);
	if(CL_TRUEP(ARG(2)))
	{
		if(CL_CHARP(ARG(2)) && GET_CHAR(ARG(2)) == '~')
		{
			Z39_get_params(ARG(3), display);
			Z40_get_at_sign_or_colon(ARG(3), display);
			Z41_get_directive(ARG(3), display);
			if(EQL(ARG(3), ARG(0)))
			{
				COPY(ARG(3), ARG(0));
				goto RETURN1;
			}
			else
			{
				if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == '(')
				{
					LOAD_CHAR(ARG(4), ')', ARG(4));
					Z42_skip(ARG(4), display, 1);
				}
				else
				{
					if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == '[')
					{
						LOAD_CHAR(ARG(4), ']', ARG(4));
						Z42_skip(ARG(4), display, 1);
					}
					else
					{
						if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == '{')
						{
							LOAD_CHAR(ARG(4), '}', ARG(4));
							Z42_skip(ARG(4), display, 1);
						}
						else
						{
							if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == '<')
							{
								LOAD_CHAR(ARG(4), '>', ARG(4));
								Z42_skip(ARG(4), display, 1);
							}
							else
							{
								if(CL_CHARP(ARG(3)) && GET_CHAR(ARG(3)) == '~')
								{
									if(CL_TRUEP(ARG(1)))
									{
										COPY(ARG(3), ARG(0));
										goto RETURN1;
									}
								}
							}
						}
					}
				}
			}
		}
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kformat21[10], ARG(3));	/* ~~~A expected in control-string */
		COPY(ARG(0), ARG(4));
		Ferror(ARG(3), 2);
	}
	goto M1_1;
	RETURN1:;
}

static void Z43_insert_space(CL_FORM *base, CL_FORM *display[])
{
	if(CL_NUMBERP(ARG(0)))
	{
		COPY(&display[0][0], ARG(2));
		COPY(ARG(2), ARG(3));
		COPY(ARG(3), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
		rt_struct_typep(ARG(4));
		if(CL_TRUEP(ARG(4)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(3))), 5 + 1), ARG(2));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(2));	/* NO_STRUCT */
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(4));	/* STREAM */
			Ferror(ARG(2), 3);
		}
		Ffuncall(ARG(2), 1);
		mv_count = 1;
		COPY(ARG(1), ARG(3));
		Fminus(ARG(2), 2);
		COPY(ARG(2), ARG(1));
		M1_1:;
		COPY(ARG(1), ARG(2));
		COPY(ARG(0), ARG(3));
		Fge(ARG(2), 2);
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_NIL(ARG(0));
			goto RETURN1;
		}
		LOAD_CHAR(ARG(2), ' ', ARG(2));
		COPY(&display[0][0], ARG(3));
		write_char1(ARG(2));
		mv_count = 1;
		F1plus(ARG(1));
		goto M1_1;
		RETURN1:;
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}

static void Z44_tabbing(CL_FORM *base, CL_FORM *display[], int nargs)
{
	switch(nargs)
	{
		case 1:
		LOAD_FIXNUM(ARG(1), 1, ARG(1));
		case 2:
		LOAD_FIXNUM(ARG(2), 1, ARG(2));
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	if(CL_TRUEP(ARG(0)))
	{
		LOAD_FIXNUM(ARG(3), 0, ARG(3));
		M1_1:;
		COPY(ARG(3), ARG(4));
		COPY(ARG(1), ARG(5));
		Fge(ARG(4), 2);
		if(CL_TRUEP(ARG(4)))
		{
			goto RETURN1;
		}
		LOAD_CHAR(ARG(4), ' ', ARG(4));
		COPY(&display[0][0], ARG(5));
		write_char1(ARG(4));
		mv_count = 1;
		F1plus(ARG(3));
		goto M1_1;
		RETURN1:;
		COPY(ARG(2), ARG(3));
		LOAD_FIXNUM(ARG(4), 1, ARG(4));
		Fgt(ARG(3), 2);
		if(CL_TRUEP(ARG(3)))
		{
			COPY(&display[0][0], ARG(3));
			COPY(ARG(3), ARG(4));
			COPY(ARG(4), ARG(5));
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(6));	/* STREAM */
			rt_struct_typep(ARG(5));
			if(CL_TRUEP(ARG(5)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 5 + 1), ARG(3));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
				Ferror(ARG(3), 3);
			}
			Ffuncall(ARG(3), 1);
			mv_count = 1;
			if(CL_TRUEP(ARG(3)))
			{
				LOAD_FIXNUM(ARG(4), 0, ARG(4));
				M2_1:;
				COPY(ARG(4), ARG(5));
				COPY(ARG(2), ARG(6));
				COPY(ARG(3), ARG(7));
				COPY(ARG(2), ARG(8));
				rt_floor(ARG(7));
				COPY(&mv_buf[0], ARG(8));
				mv_count = 1;
				{
					COPY(ARG(8), ARG(7));
				}
				Fminus(ARG(6), 2);
				Fge(ARG(5), 2);
				if(CL_TRUEP(ARG(5)))
				{
					LOAD_NIL(ARG(0));
					goto RETURN2;
				}
				LOAD_CHAR(ARG(5), ' ', ARG(5));
				COPY(&display[0][0], ARG(6));
				write_char1(ARG(5));
				mv_count = 1;
				F1plus(ARG(4));
				goto M2_1;
				RETURN2:;
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		COPY(&display[0][0], ARG(3));
		COPY(ARG(3), ARG(4));
		COPY(ARG(4), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(6));	/* STREAM */
		rt_struct_typep(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(4))), 5 + 1), ARG(3));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(5));	/* STREAM */
			Ferror(ARG(3), 3);
		}
		Ffuncall(ARG(3), 1);
		mv_count = 1;
		if(CL_TRUEP(ARG(3)))
		{
			COPY(ARG(1), ARG(4));
			COPY(ARG(3), ARG(5));
			Fgt(ARG(4), 2);
			if(CL_TRUEP(ARG(4)))
			{
				LOAD_FIXNUM(ARG(4), 0, ARG(4));
				M3_1:;
				COPY(ARG(4), ARG(5));
				COPY(ARG(1), ARG(6));
				COPY(ARG(3), ARG(7));
				Fminus(ARG(6), 2);
				Fge(ARG(5), 2);
				if(CL_TRUEP(ARG(5)))
				{
					LOAD_NIL(ARG(0));
					goto RETURN3;
				}
				LOAD_CHAR(ARG(5), ' ', ARG(5));
				COPY(&display[0][0], ARG(6));
				write_char1(ARG(5));
				mv_count = 1;
				F1plus(ARG(4));
				goto M3_1;
				RETURN3:;
			}
			else
			{
				COPY(ARG(2), ARG(4));
				LOAD_FIXNUM(ARG(5), 1, ARG(5));
				Fgt(ARG(4), 2);
				if(CL_TRUEP(ARG(4)))
				{
					COPY(ARG(3), ARG(4));
					COPY(ARG(1), ARG(5));
					Fminus(ARG(4), 2);
					LOAD_FIXNUM(ARG(5), 0, ARG(5));
					M4_1:;
					COPY(ARG(5), ARG(6));
					COPY(ARG(2), ARG(7));
					COPY(ARG(4), ARG(8));
					COPY(ARG(2), ARG(9));
					rt_floor(ARG(8));
					COPY(&mv_buf[0], ARG(9));
					mv_count = 1;
					{
						COPY(ARG(9), ARG(8));
					}
					Fminus(ARG(7), 2);
					Fge(ARG(6), 2);
					if(CL_TRUEP(ARG(6)))
					{
						LOAD_NIL(ARG(0));
						goto RETURN4;
					}
					LOAD_CHAR(ARG(6), ' ', ARG(6));
					COPY(&display[0][0], ARG(7));
					write_char1(ARG(6));
					mv_count = 1;
					F1plus(ARG(5));
					goto M4_1;
					RETURN4:;
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
		}
		else
		{
			LOAD_CHAR(ARG(4), ' ', ARG(4));
			COPY(&display[0][0], ARG(5));
			write_char1(ARG(4));
			mv_count = 1;
			LOAD_CHAR(ARG(0), ' ', ARG(0));
			COPY(&display[0][0], ARG(1));
			write_char1(ARG(0));
		}
	}
}

static void Z45_padding(CL_FORM *base, CL_FORM *display[], int nargs)
{
	switch(nargs)
	{
		case 1:
		LOAD_FIXNUM(ARG(1), 0, ARG(1));
		case 2:
		LOAD_FIXNUM(ARG(2), 1, ARG(2));
		case 3:
		LOAD_FIXNUM(ARG(3), 0, ARG(3));
		case 4:
		LOAD_CHAR(ARG(4), ' ', ARG(4));
		case 5:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	LOAD_FIXNUM(ARG(5), 0, ARG(5));
	M1_1:;
	COPY(ARG(5), ARG(6));
	COPY(ARG(3), ARG(7));
	Fge(ARG(6), 2);
	if(CL_TRUEP(ARG(6)))
	{
		goto RETURN1;
	}
	COPY(ARG(4), ARG(6));
	COPY(&display[0][0], ARG(7));
	write_char1(ARG(6));
	mv_count = 1;
	F1plus(ARG(5));
	goto M1_1;
	RETURN1:;
	COPY(ARG(0), ARG(5));
	COPY(ARG(3), ARG(6));
	Fplus(ARG(5), 2);
	COPY(ARG(5), ARG(0));
	M2_1:;
	COPY(ARG(0), ARG(5));
	COPY(ARG(1), ARG(6));
	Fge(ARG(5), 2);
	if(CL_TRUEP(ARG(5)))
	{
		LOAD_NIL(ARG(0));
		goto RETURN2;
	}
	LOAD_FIXNUM(ARG(5), 0, ARG(5));
	M3_1:;
	COPY(ARG(5), ARG(6));
	COPY(ARG(2), ARG(7));
	Fge(ARG(6), 2);
	if(CL_TRUEP(ARG(6)))
	{
		goto RETURN3;
	}
	COPY(ARG(4), ARG(6));
	COPY(&display[0][0], ARG(7));
	write_char1(ARG(6));
	mv_count = 1;
	F1plus(ARG(5));
	goto M3_1;
	RETURN3:;
	COPY(ARG(0), ARG(5));
	COPY(ARG(2), ARG(6));
	Fplus(ARG(5), 2);
	COPY(ARG(5), ARG(0));
	goto M2_1;
	RETURN2:;
}
