/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void format2(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 3:
		LOAD_FIXNUM(ARG(3), 0, ARG(3));
		case 4:
		LOAD_NIL(ARG(4));
		case 5:
		LOAD_NIL(ARG(5));
		case 6:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	format21(ARG(0));
}
