/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fprobe_file(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
	unix_namestring1(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(1), ARG(2));
		LOAD_NIL(ARG(3));
		unix_file_kind1(ARG(2));
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(1), ARG(2));
		Flength(ARG(2));
		Fplusp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			if(CL_SMSTRP(ARG(1)))
			{
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(2));	/* WRONG_TYPE */
				COPY(ARG(1), ARG(3));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(4));	/* SIMPLE-STRING */
				Ferror(ARG(2), 3);
			}
			COPY(ARG(1), ARG(2));
			LOAD_FIXNUM(ARG(3), 0, ARG(3));
			pvref(ARG(2));
			LOAD_CHAR(ARG(3), '/', ARG(3));
			rt_charE(ARG(2));
		}
		else
		{
			goto ELSE2;
		}
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(1), ARG(2));
		}
		else
		{
			ELSE2:;
			unix_current_directory(ARG(2));
			COPY(&mv_buf[0], ARG(3));
			{
				int nargs;
				nargs = 2;
				mv_count = 1;
				{
					switch(nargs)
					{
						case 0:
						LOAD_NIL(ARG(2));
						case 1:
						LOAD_NIL(ARG(3));
						nargs = 2;
					}
					if(CL_TRUEP(ARG(2)))
					{
						LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(2));	/* SIMPLE-STRING */
						LOAD_SMSTR((CL_FORM *)&KClisp[106], ARG(4));	/* / */
						COPY(ARG(1), ARG(5));
						Fconcatenate(ARG(2), 4);
					}
					else
					{
						COPY(ARG(1), ARG(2));
					}
				}
			}
		}
		COPY(ARG(2), ARG(3));
		Flength(ARG(3));
		COPY(ARG(2), ARG(4));
		COPY(ARG(3), ARG(5));
		Fzerop(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
		}
		else
		{
			LOAD_FIXNUM(ARG(5), 1024, ARG(5));
			LOAD_FIXNUM(ARG(6), 0, ARG(6));
			LOAD_FIXNUM(ARG(7), 0, ARG(7));
			LOAD_FIXNUM(ARG(8), 0, ARG(8));
			LOAD_FIXNUM(ARG(9), 256, ARG(9));
			Fle(ARG(7), 3);
			if(CL_TRUEP(ARG(7)))
			{
				LOAD_FIXNUM(ARG(6), 0, ARG(6));
				rt_code_char(ARG(6));
			}
			else
			{
				LOAD_NIL(ARG(6));
			}
			make_string1(ARG(5));
			LOAD_FIXNUM(ARG(6), 0, ARG(6));
			LOAD_FIXNUM(ARG(7), 0, ARG(7));
			M1_1:;
			LOAD_CHAR(ARG(8), '/', ARG(8));
			COPY(ARG(4), ARG(9));
			LOAD_SYMBOL(SYMBOL(Slisp, 231), ARG(10));	/* START */
			COPY(ARG(7), ARG(11));
			Fposition(ARG(8), 4);
			if(CL_TRUEP(ARG(8)))
			{
			}
			else
			{
				COPY(ARG(3), ARG(8));
			}
			COPY(ARG(6), ARG(9));
			COPY(ARG(8), ARG(10));
			COPY(ARG(7), ARG(11));
			Fminus(ARG(10), 2);
			Fplus(ARG(9), 2);
			COPY(ARG(5), ARG(10));
			COPY(ARG(4), ARG(11));
			COPY(ARG(6), ARG(12));
			COPY(ARG(9), ARG(13));
			COPY(ARG(7), ARG(14));
			COPY(ARG(8), ARG(15));
			replace1(ARG(10));
			COPY(ARG(8), ARG(10));
			Fzerop(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[104], ARG(10));	/* / */
			}
			else
			{
				COPY(ARG(5), ARG(10));
			}
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(11));	/* T */
			unix_file_kind1(ARG(10));
			if(CL_TRUEP(ARG(10)))
			{
			}
			else
			{
				LOAD_NIL(ARG(2));
				goto RETURN1;
			}
			if(CL_SYMBOLP(ARG(10)) && GET_SYMBOL(ARG(10)) == SYMBOL(Slisp, 300))	/* LINK */
			{
				COPY(ARG(5), ARG(11));
				unix_readlink(ARG(11));
				MV_TO_STACK(mv_count, 12);
				{
					int nargs;
					nargs = mv_count;
					mv_count = 1;
					{
						switch(nargs)
						{
							case 0:
							LOAD_NIL(ARG(11));
							case 1:
							LOAD_NIL(ARG(12));
							nargs = 2;
						}
						if(CL_TRUEP(ARG(11)))
						{
						}
						else
						{
							LOAD_SMSTR((CL_FORM *)&KClisp[102], ARG(13));	/* Error reading link ~S: ~S */
							COPY(ARG(5), ARG(14));
							LOAD_FIXNUM(ARG(15), 0, ARG(15));
							COPY(ARG(6), ARG(16));
							subseq1(ARG(14));
							COPY(SYMVAL(Slisp, 293), ARG(15));	/* *UNIX-ERRORS* */
							COPY(ARG(12), ARG(16));
							Farray_in_bounds_p(ARG(15), 2);
							if(CL_TRUEP(ARG(15)))
							{
								COPY(SYMVAL(Slisp, 293), ARG(15));	/* *UNIX-ERRORS* */
								COPY(ARG(12), ARG(16));
								Fsvref(ARG(15));
							}
							else
							{
								LOAD_NIL(ARG(15));
								LOAD_SMSTR((CL_FORM *)&KClisp[100], ARG(16));	/* Unknown error [~d] */
								COPY(ARG(12), ARG(17));
								Fformat(ARG(15), 3);
								mv_count = 1;
							}
							Ferror(ARG(13), 3);
						}
						COPY(ARG(11), ARG(13));
						Flength(ARG(13));
						Fzerop(ARG(13));
						if(CL_TRUEP(ARG(13)))
						{
							goto THEN3;
						}
						else
						{
							if(CL_SMSTRP(ARG(11)))
							{
							}
							else
							{
								COPY(SYMVAL(Slisp, 58), ARG(14));	/* WRONG_TYPE */
								COPY(ARG(11), ARG(15));
								LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(16));	/* SIMPLE-STRING */
								Ferror(ARG(14), 3);
							}
							COPY(ARG(11), ARG(14));
							LOAD_FIXNUM(ARG(15), 0, ARG(15));
							pvref(ARG(14));
							LOAD_CHAR(ARG(15), '/', ARG(15));
							rt_charNE(ARG(14));
						}
						if(CL_TRUEP(ARG(14)))
						{
							THEN3:;
							COPY(ARG(5), ARG(13));
							LOAD_FIXNUM(ARG(14), 0, ARG(14));
							LOAD_FIXNUM(ARG(15), 0, ARG(15));
							LOAD_FIXNUM(ARG(16), 0, ARG(16));
							LOAD_FIXNUM(ARG(17), 256, ARG(17));
							Fle(ARG(15), 3);
							if(CL_TRUEP(ARG(15)))
							{
								LOAD_FIXNUM(ARG(14), 0, ARG(14));
								rt_code_char(ARG(14));
							}
							else
							{
								LOAD_NIL(ARG(14));
							}
							COPY(ARG(6), ARG(15));
							COPY(ARG(9), ARG(16));
							fill1(ARG(13));
						}
						else
						{
							COPY(ARG(5), ARG(13));
							LOAD_SMSTR((CL_FORM *)&KClisp[98], ARG(14));	/* /../ */
							LOAD_FIXNUM(ARG(15), 0, ARG(15));
							LOAD_FIXNUM(ARG(16), 4, ARG(16));
							LOAD_FIXNUM(ARG(17), 0, ARG(17));
							LOAD_NIL(ARG(18));
							stringE1(ARG(13));
							if(CL_TRUEP(ARG(13)))
							{
								LOAD_CHAR(ARG(13), '/', ARG(13));
								COPY(ARG(5), ARG(14));
								LOAD_SYMBOL(SYMBOL(Slisp, 231), ARG(15));	/* START */
								LOAD_FIXNUM(ARG(16), 4, ARG(16));
								Fposition(ARG(13), 4);
								if(CL_TRUEP(ARG(13)))
								{
								}
								else
								{
									LOAD_FIXNUM(ARG(14), 0, ARG(13));
								}
								COPY(ARG(5), ARG(14));
								LOAD_FIXNUM(ARG(15), 0, ARG(15));
								LOAD_FIXNUM(ARG(16), 0, ARG(16));
								LOAD_FIXNUM(ARG(17), 0, ARG(17));
								LOAD_FIXNUM(ARG(18), 256, ARG(18));
								Fle(ARG(16), 3);
								if(CL_TRUEP(ARG(16)))
								{
									LOAD_FIXNUM(ARG(15), 0, ARG(15));
									rt_code_char(ARG(15));
								}
								else
								{
									LOAD_NIL(ARG(15));
								}
								COPY(ARG(13), ARG(16));
								COPY(ARG(9), ARG(17));
								fill1(ARG(14));
								COPY(ARG(13), ARG(6));
							}
							else
							{
								COPY(ARG(11), ARG(13));
								Flength(ARG(13));
								Fplusp(ARG(13));
								if(CL_TRUEP(ARG(13)))
								{
									if(CL_SMSTRP(ARG(11)))
									{
									}
									else
									{
										COPY(SYMVAL(Slisp, 58), ARG(13));	/* WRONG_TYPE */
										COPY(ARG(11), ARG(14));
										LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(15));	/* SIMPLE-STRING */
										Ferror(ARG(13), 3);
									}
									COPY(ARG(11), ARG(13));
									LOAD_FIXNUM(ARG(14), 0, ARG(14));
									pvref(ARG(13));
									LOAD_CHAR(ARG(14), '/', ARG(14));
									rt_charE(ARG(13));
								}
								COPY(ARG(5), ARG(13));
								LOAD_FIXNUM(ARG(14), 0, ARG(14));
								LOAD_FIXNUM(ARG(15), 0, ARG(15));
								LOAD_FIXNUM(ARG(16), 0, ARG(16));
								LOAD_FIXNUM(ARG(17), 256, ARG(17));
								Fle(ARG(15), 3);
								if(CL_TRUEP(ARG(15)))
								{
									LOAD_FIXNUM(ARG(14), 0, ARG(14));
									rt_code_char(ARG(14));
								}
								else
								{
									LOAD_NIL(ARG(14));
								}
								LOAD_FIXNUM(ARG(15), 0, ARG(15));
								COPY(ARG(9), ARG(16));
								fill1(ARG(13));
								LOAD_FIXNUM(ARG(13), 0, ARG(6));
							}
						}
						COPY(ARG(8), ARG(13));
						COPY(ARG(3), ARG(14));
						Fnumeql(ARG(13), 2);
						if(CL_TRUEP(ARG(13)))
						{
							COPY(ARG(11), ARG(13));
						}
						else
						{
							LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(13));	/* SIMPLE-STRING */
							COPY(ARG(11), ARG(14));
							COPY(ARG(4), ARG(15));
							COPY(ARG(8), ARG(16));
							LOAD_NIL(ARG(17));
							subseq1(ARG(15));
							Fconcatenate(ARG(13), 3);
						}
						COPY(ARG(13), ARG(4));
						Flength(ARG(13));
						COPY(ARG(13), ARG(3));
						LOAD_FIXNUM(ARG(13), 0, ARG(7));
					}
				}
			}
			else
			{
				COPY(ARG(8), ARG(11));
				COPY(ARG(3), ARG(12));
				Fnumeql(ARG(11), 2);
				if(CL_TRUEP(ARG(11)))
				{
					COPY(ARG(5), ARG(2));
					LOAD_FIXNUM(ARG(3), 0, ARG(3));
					COPY(ARG(9), ARG(4));
					subseq1(ARG(2));
					goto RETURN1;
				}
				else
				{
					if(CL_SYMBOLP(ARG(10)) && GET_SYMBOL(ARG(10)) == SYMBOL(Slisp, 253))	/* DIRECTORY */
					{
						LOAD_CHAR(ARG(11), '/', ARG(11));
						COPY(ARG(5), ARG(12));
						COPY(ARG(9), ARG(13));
						Fset_schar(ARG(11));
						COPY(ARG(9), ARG(6));
						F1plus(ARG(6));
						COPY(ARG(8), ARG(7));
						F1plus(ARG(7));
					}
					else
					{
						LOAD_NIL(ARG(2));
						goto RETURN1;
					}
				}
			}
			goto M1_1;
			RETURN1:;
		}
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
			BIND_SPECIAL(SYMBOL(Slisp, 287), ARG(3));	/* *IGNORE-WILDCARDS* */
			COPY(ARG(2), ARG(4));
			Flength(ARG(4));
			COPY(ARG(4), ARG(5));
			LOAD_CHAR(ARG(6), ' ', ARG(6));
			make_string1(ARG(5));
			LOAD_FIXNUM(ARG(6), 0, ARG(6));
			LOAD_FIXNUM(ARG(7), 0, ARG(7));
			LOAD_NIL(ARG(8));
			LOAD_FIXNUM(ARG(9), 0, ARG(9));
			M2_1:;
			COPY(ARG(9), ARG(10));
			COPY(ARG(4), ARG(11));
			Fge(ARG(10), 2);
			if(CL_TRUEP(ARG(10)))
			{
				goto RETURN3;
			}
			if(CL_SMSTRP(ARG(2)))
			{
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(10));	/* WRONG_TYPE */
				COPY(ARG(2), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(12));	/* SIMPLE-STRING */
				Ferror(ARG(10), 3);
			}
			COPY(ARG(2), ARG(10));
			COPY(ARG(9), ARG(11));
			pvref(ARG(10));
			COPY(ARG(10), ARG(11));
			LOAD_CHAR(ARG(12), '.', ARG(12));
			rt_charE(ARG(11));
			if(CL_TRUEP(ARG(11)))
			{
				if(CL_TRUEP(ARG(7)))
				{
					F1plus(ARG(7));
				}
				COPY(ARG(10), ARG(11));
				COPY(ARG(5), ARG(12));
				COPY(ARG(6), ARG(13));
				Fset_schar(ARG(11));
				F1plus(ARG(6));
			}
			else
			{
				COPY(ARG(10), ARG(11));
				LOAD_CHAR(ARG(12), '/', ARG(12));
				rt_charE(ARG(11));
				if(CL_TRUEP(ARG(11)))
				{
					if(CL_FIXNUMP(ARG(7)) && GET_FIXNUM(ARG(7)) == 0)
					{
						if(CL_TRUEP(ARG(8)))
						{
						}
						else
						{
							COPY(ARG(6), ARG(8));
							COPY(ARG(10), ARG(11));
							COPY(ARG(5), ARG(12));
							COPY(ARG(6), ARG(13));
							Fset_schar(ARG(11));
							F1plus(ARG(6));
						}
					}
					else
					{
						if(CL_FIXNUMP(ARG(7)) && GET_FIXNUM(ARG(7)) == 1)
						{
							F1minus(ARG(6));
						}
						else
						{
							if(CL_FIXNUMP(ARG(7)) && GET_FIXNUM(ARG(7)) == 2)
							{
								if(CL_TRUEP(ARG(8)))
								{
									COPY(ARG(8), ARG(11));
									Fzerop(ARG(11));
									if(CL_TRUEP(ARG(11)))
									{
										goto ELSE4;
									}
									else
									{
										goto THEN5;
									}
								}
								else
								{
									goto ELSE4;
								}
								{
									THEN5:;
									LOAD_CHAR(ARG(11), '/', ARG(11));
									COPY(ARG(5), ARG(12));
									LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(13));	/* END */
									COPY(ARG(8), ARG(14));
									LOAD_SYMBOL(SYMBOL(Slisp, 294), ARG(15));	/* FROM-END */
									LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(16));	/* T */
									Fposition(ARG(11), 6);
									if(CL_TRUEP(ARG(11)))
									{
										COPY(ARG(11), ARG(12));
									}
									else
									{
										LOAD_FIXNUM(ARG(12), 0, ARG(12));
									}
									LOAD_FIXNUM(ARG(13), 2, ARG(13));
									Fplus(ARG(12), 2);
									COPY(ARG(8), ARG(13));
									Fnumeql(ARG(12), 2);
									if(CL_TRUEP(ARG(12)))
									{
										COPY(ARG(8), ARG(12));
										LOAD_FIXNUM(ARG(13), 2, ARG(13));
										Fminus(ARG(12), 2);
										if(CL_SMSTRP(ARG(5)))
										{
										}
										else
										{
											COPY(SYMVAL(Slisp, 58), ARG(13));	/* WRONG_TYPE */
											COPY(ARG(5), ARG(14));
											LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(15));	/* SIMPLE-STRING */
											Ferror(ARG(13), 3);
										}
										COPY(ARG(5), ARG(13));
										COPY(ARG(12), ARG(14));
										pvref(ARG(13));
										COPY(ARG(13), ARG(12));
										LOAD_CHAR(ARG(13), '.', ARG(13));
										rt_charE(ARG(12));
										if(CL_TRUEP(ARG(12)))
										{
											COPY(ARG(8), ARG(12));
											F1minus(ARG(12));
											if(CL_SMSTRP(ARG(5)))
											{
											}
											else
											{
												COPY(SYMVAL(Slisp, 58), ARG(13));	/* WRONG_TYPE */
												COPY(ARG(5), ARG(14));
												LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(15));	/* SIMPLE-STRING */
												Ferror(ARG(13), 3);
											}
											COPY(ARG(5), ARG(13));
											COPY(ARG(12), ARG(14));
											pvref(ARG(13));
											COPY(ARG(13), ARG(12));
											LOAD_CHAR(ARG(13), '.', ARG(13));
											rt_charE(ARG(12));
										}
										else
										{
											goto ELSE6;
										}
									}
									else
									{
										goto ELSE6;
									}
									if(CL_TRUEP(ARG(12)))
									{
										COPY(ARG(10), ARG(12));
										COPY(ARG(5), ARG(13));
										COPY(ARG(6), ARG(14));
										Fset_schar(ARG(12));
										F1plus(ARG(6));
										COPY(ARG(6), ARG(8));
									}
									else
									{
										ELSE6:;
										if(CL_TRUEP(ARG(11)))
										{
											COPY(ARG(11), ARG(6));
											F1plus(ARG(6));
										}
										else
										{
											LOAD_FIXNUM(ARG(12), 0, ARG(6));
										}
										COPY(ARG(11), ARG(8));
									}
								}
								goto ENDIF7;
								{
									ELSE4:;
									COPY(ARG(6), ARG(8));
									COPY(ARG(10), ARG(11));
									COPY(ARG(5), ARG(12));
									COPY(ARG(6), ARG(13));
									Fset_schar(ARG(11));
									F1plus(ARG(6));
								}
								ENDIF7:;
							}
							else
							{
								COPY(ARG(6), ARG(8));
								COPY(ARG(10), ARG(11));
								COPY(ARG(5), ARG(12));
								COPY(ARG(6), ARG(13));
								Fset_schar(ARG(11));
								F1plus(ARG(6));
							}
						}
					}
					LOAD_FIXNUM(ARG(11), 0, ARG(7));
				}
				else
				{
					LOAD_NIL(ARG(7));
					COPY(ARG(10), ARG(11));
					COPY(ARG(5), ARG(12));
					COPY(ARG(6), ARG(13));
					Fset_schar(ARG(11));
					F1plus(ARG(6));
				}
			}
			F1plus(ARG(9));
			goto M2_1;
			RETURN3:;
			if(CL_TRUEP(ARG(8)))
			{
				COPY(ARG(8), ARG(9));
				Fzerop(ARG(9));
				if(CL_TRUEP(ARG(9)))
				{
					goto ELSE8;
				}
				else
				{
					goto THEN9;
				}
			}
			else
			{
				goto ELSE8;
			}
			{
				THEN9:;
				if(CL_FIXNUMP(ARG(7)) && GET_FIXNUM(ARG(7)) == 1)
				{
					F1minus(ARG(6));
				}
				else
				{
					if(CL_FIXNUMP(ARG(7)) && GET_FIXNUM(ARG(7)) == 2)
					{
						COPY(ARG(8), ARG(9));
						LOAD_FIXNUM(ARG(10), 2, ARG(10));
						Fge(ARG(9), 2);
						if(CL_TRUEP(ARG(9)))
						{
							COPY(ARG(8), ARG(9));
							F1minus(ARG(9));
							if(CL_SMSTRP(ARG(5)))
							{
							}
							else
							{
								COPY(SYMVAL(Slisp, 58), ARG(10));	/* WRONG_TYPE */
								COPY(ARG(5), ARG(11));
								LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(12));	/* SIMPLE-STRING */
								Ferror(ARG(10), 3);
							}
							COPY(ARG(5), ARG(10));
							COPY(ARG(9), ARG(11));
							pvref(ARG(10));
							COPY(ARG(10), ARG(9));
							LOAD_CHAR(ARG(10), '.', ARG(10));
							rt_charE(ARG(9));
							if(CL_TRUEP(ARG(9)))
							{
								COPY(ARG(8), ARG(9));
								LOAD_FIXNUM(ARG(10), 2, ARG(10));
								Fminus(ARG(9), 2);
								if(CL_SMSTRP(ARG(5)))
								{
								}
								else
								{
									COPY(SYMVAL(Slisp, 58), ARG(10));	/* WRONG_TYPE */
									COPY(ARG(5), ARG(11));
									LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(12));	/* SIMPLE-STRING */
									Ferror(ARG(10), 3);
								}
								COPY(ARG(5), ARG(10));
								COPY(ARG(9), ARG(11));
								pvref(ARG(10));
								COPY(ARG(10), ARG(9));
								LOAD_CHAR(ARG(10), '.', ARG(10));
								rt_charE(ARG(9));
								if(CL_TRUEP(ARG(9)))
								{
									COPY(ARG(8), ARG(9));
									LOAD_FIXNUM(ARG(10), 2, ARG(10));
									Fnumeql(ARG(9), 2);
									if(CL_TRUEP(ARG(9)))
									{
										goto THEN10;
									}
									else
									{
										COPY(ARG(8), ARG(10));
										LOAD_FIXNUM(ARG(11), 3, ARG(11));
										Fminus(ARG(10), 2);
										if(CL_SMSTRP(ARG(5)))
										{
										}
										else
										{
											COPY(SYMVAL(Slisp, 58), ARG(11));	/* WRONG_TYPE */
											COPY(ARG(5), ARG(12));
											LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(13));	/* SIMPLE-STRING */
											Ferror(ARG(11), 3);
										}
										COPY(ARG(5), ARG(11));
										COPY(ARG(10), ARG(12));
										pvref(ARG(11));
										COPY(ARG(11), ARG(10));
										LOAD_CHAR(ARG(11), '/', ARG(11));
										rt_charE(ARG(10));
									}
								}
								else
								{
									goto ELSE11;
								}
							}
							else
							{
								goto ELSE11;
							}
						}
						else
						{
							goto ELSE11;
						}
						if(CL_TRUEP(ARG(10)))
						{
							THEN10:;
						}
						else
						{
							ELSE11:;
							LOAD_CHAR(ARG(9), '/', ARG(9));
							COPY(ARG(5), ARG(10));
							LOAD_SYMBOL(SYMBOL(Slisp, 232), ARG(11));	/* END */
							COPY(ARG(8), ARG(12));
							LOAD_SYMBOL(SYMBOL(Slisp, 294), ARG(13));	/* FROM-END */
							LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(14));	/* T */
							Fposition(ARG(9), 6);
							if(CL_TRUEP(ARG(9)))
							{
								COPY(ARG(9), ARG(6));
								F1plus(ARG(6));
							}
							else
							{
								LOAD_SMSTR((CL_FORM *)&KClisp[96], ARG(4));	/* ./ */
								goto RETURN2;
							}
						}
					}
				}
			}
			ELSE8:;
			COPY(ARG(6), ARG(9));
			Fzerop(ARG(9));
			if(CL_TRUEP(ARG(9)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[94], ARG(4));	/* ./ */
			}
			else
			{
				COPY(ARG(6), ARG(9));
				COPY(ARG(4), ARG(10));
				Fnumeql(ARG(9), 2);
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(5), ARG(4));
				}
				else
				{
					COPY(ARG(5), ARG(4));
					LOAD_FIXNUM(ARG(5), 0, ARG(5));
					subseq1(ARG(4));
				}
			}
			RETURN2:;
			Fpathname(ARG(4));
			COPY(ARG(4), ARG(0));
			RESTORE_SPECIAL;
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		ELSE1:;
		LOAD_NIL(ARG(0));
	}
}
