/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fremprop(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)))
	{
		COPY(SYM_PLIST(ARG(0)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(0), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			COPY(SYMVAL(Slisp, 678), ARG(2));	/* *NIL-PLIST* */
		}
	}
	COPY(ARG(1), ARG(3));
	rt_remf_internal(ARG(2));
	COPY(&mv_buf[0], ARG(3));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(2));
				case 1:
				LOAD_NIL(ARG(3));
				nargs = 2;
			}
			if(CL_TRUEP(ARG(3)))
			{
				COPY(ARG(2), ARG(4));
				COPY(ARG(0), ARG(5));
				Fset_symbol_plist(ARG(4));
				LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
	}
}
