/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Freverse(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			LOAD_NIL(ARG(1));
			LOAD_NIL(ARG(2));
			COPY(ARG(0), ARG(3));
			M1_1:;
			if(CL_ATOMP(ARG(3)))
			{
				LOAD_NIL(ARG(2));
				goto RETURN1;
			}
			COPY(ARG(3), ARG(4));
			COPY(GET_CAR(ARG(4)), ARG(2));
			ALLOC_CONS(ARG(6), ARG(2), ARG(1), ARG(1));
			COPY(ARG(3), ARG(4));
			COPY(GET_CDR(ARG(4)), ARG(3));
			goto M1_1;
			RETURN1:;
			COPY(ARG(1), ARG(0));
		}
		else
		{
			LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(1));
			if(CL_TRUEP(ARG(1)))
			{
				goto THEN1;
			}
			else
			{
				COPY(ARG(0), ARG(2));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(2));
			}
			if(CL_TRUEP(ARG(2)))
			{
				THEN1:;
				COPY(ARG(0), ARG(1));
				Flength(ARG(1));
				LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(2));	/* VECTOR */
				COPY(ARG(0), ARG(3));
				array_element_type_internal(ARG(3));
				to_element_type(ARG(3));
				Flist(ARG(2), 2);
				COPY(ARG(1), ARG(3));
				LOAD_NIL(ARG(4));
				LOAD_NIL(ARG(5));
				make_sequence1(ARG(2));
				LOAD_FIXNUM(ARG(3), 0, ARG(3));
				COPY(ARG(1), ARG(4));
				F1minus(ARG(4));
				M2_1:;
				COPY(ARG(3), ARG(5));
				COPY(ARG(1), ARG(6));
				Fnumeql(ARG(5), 2);
				if(CL_TRUEP(ARG(5)))
				{
					COPY(ARG(2), ARG(0));
					goto RETURN2;
				}
				COPY(ARG(0), ARG(5));
				COPY(ARG(3), ARG(6));
				Felt(ARG(5));
				COPY(ARG(2), ARG(6));
				COPY(ARG(4), ARG(7));
				Fset_elt(ARG(5));
				COPY(ARG(3), ARG(5));
				F1plus(ARG(5));
				F1minus(ARG(4));
				COPY(ARG(5), ARG(3));
				goto M2_1;
				RETURN2:;
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(1));	/* WRONG_TYPE */
				COPY(ARG(0), ARG(2));
				LOAD_SYMBOL(SYMBOL(Slisp, 36), ARG(3));	/* SEQUENCE */
				Ferror(ARG(1), 3);
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
