/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Frplaca(CL_FORM *base)
{
	if(CL_CONSP(ARG(0)))
	{
		COPY(ARG(1), GET_CAR(ARG(0)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[260], ARG(2));	/* ~a is not a cons */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
}
