/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fset_elt(CL_FORM *base)
{
	if(CL_CONSP(ARG(1)))
	{
		COPY(ARG(2), ARG(3));
		COPY(ARG(1), ARG(4));
		Fnthcdr(ARG(3));
		if(CL_CONSP(ARG(3)))
		{
			COPY(ARG(0), GET_CAR(ARG(3)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[252], ARG(0));	/* ~a is not a cons */
			COPY(ARG(3), ARG(1));
			Ferror(ARG(0), 2);
		}
	}
	else
	{
		LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(1), ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(5));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(4));
		}
		if(CL_TRUEP(ARG(4)))
		{
			THEN1:;
			Fset_row_major_aref(ARG(0));
		}
		else
		{
			COPY(SYMVAL(Slisp, 58), ARG(0));	/* WRONG_TYPE */
			LOAD_SYMBOL(SYMBOL(Slisp, 36), ARG(2));	/* SEQUENCE */
			Ferror(ARG(0), 3);
		}
	}
}
