/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fset_aref(CL_FORM *base, int nargs)
{
	CL_FORM *rest_0;
	CL_FORM *local;
	rest_0 = ARG(2);
	local = ARG(nargs);
	COPY(ARG(0), LOCAL(0));
	COPY(ARG(1), LOCAL(1));
	LOAD_GLOBFUN(&CFarray_row_major_index, LOCAL(2));
	COPY(ARG(1), LOCAL(3));
	REST_APPLY(LOCAL(2), 2, rest_0);
	mv_count = 1;
	Fset_row_major_aref(LOCAL(0));
	COPY(LOCAL(0), ARG(0));
}
