/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fset_cdr(CL_FORM *base)
{
	if(CL_CONSP(ARG(1)))
	{
		COPY(ARG(0), GET_CDR(ARG(1)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[254], ARG(0));	/* ~a is not a cons */
		Ferror(ARG(0), 2);
	}
}
