/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fstring(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Fstringp(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
	}
	else
	{
		if(CL_SYMBOLP(ARG(0)) || CL_NILP(ARG(0)))
		{
			if(CL_SYMBOLP(ARG(0)))
			{
				LOAD_SMSTR(SYM_NAME(ARG(0)), ARG(0));
			}
			else
			{
				if(CL_TRUEP(ARG(0)))
				{
					COPY(SYMVAL(Slisp, 676), ARG(1));	/* SYM_EXPECTED */
					COPY(ARG(0), ARG(2));
					Ferror(ARG(1), 2);
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(0));	/* NIL */
				}
			}
		}
		else
		{
			if(CL_CHARP(ARG(0)))
			{
				LOAD_FIXNUM(ARG(1), 1, ARG(1));
				COPY(ARG(0), ARG(2));
				make_string1(ARG(1));
				COPY(ARG(1), ARG(0));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[66], ARG(1));	/* It could not be generated a string from ~S */
				COPY(ARG(0), ARG(2));
				Ferror(ARG(1), 2);
			}
		}
	}
}
