/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CFthird, Fthird, 1);

void Fthird(CL_FORM *base)
{
	Fcaddr(ARG(0));
}
