/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fvector_push(CL_FORM *base)
{
	COPY(ARG(1), ARG(2));
	Farray_has_fill_pointer_p(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 154), ARG(2));	/* NO_FILL_PTR */
		COPY(ARG(1), ARG(3));
		Ferror(ARG(2), 2);
	}
	COPY(ARG(1), ARG(2));
	complex_vector_fillptr(ARG(2));
	COPY(ARG(2), ARG(3));
	COPY(ARG(1), ARG(4));
	LOAD_FIXNUM(ARG(5), 0, ARG(5));
	Farray_dimension(ARG(4));
	Flt(ARG(3), 2);
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(0), ARG(3));
		COPY(ARG(1), ARG(4));
		COPY(ARG(2), ARG(5));
		rt_set_vref(ARG(3));
		COPY(ARG(2), ARG(3));
		F1plus(ARG(3));
		COPY(ARG(1), ARG(4));
		Fset_fill_pointer(ARG(3));
		COPY(ARG(2), ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
