/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fvector_pop(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Farray_has_fill_pointer_p(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
	}
	else
	{
		COPY(SYMVAL(Slisp, 154), ARG(1));	/* NO_FILL_PTR */
		COPY(ARG(0), ARG(2));
		Ferror(ARG(1), 2);
	}
	COPY(ARG(0), ARG(1));
	complex_vector_fillptr(ARG(1));
	COPY(ARG(1), ARG(2));
	Fzerop(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[184], ARG(2));	/* The fill pointer of the vector ~A is zero. */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
	F1minus(ARG(1));
	COPY(ARG(1), ARG(2));
	COPY(ARG(0), ARG(3));
	Fset_fill_pointer(ARG(2));
	LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(4));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(3));
	}
	if(CL_TRUEP(ARG(3)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(2));	/* WRONG_TYPE */
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(4));	/* VECTOR */
		Ferror(ARG(2), 3);
	}
	Frow_major_aref(ARG(0));
}
