/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fwarn(CL_FORM *base, int nargs)
{
	Flist(ARG(1), nargs - 1);
	COPY(SYMVAL(Slisp, 506), ARG(2));	/* *ERROR-PRINT-LENGTH* */
	BIND_SPECIAL(SYMBOL(Slisp, 476), ARG(2));	/* *PRINT-LENGTH* */
	COPY(SYMVAL(Slisp, 507), ARG(3));	/* *ERROR-PRINT-LEVEL* */
	BIND_SPECIAL(SYMBOL(Slisp, 477), ARG(3));	/* *PRINT-LEVEL* */
	COPY(SYMVAL(Slisp, 62), ARG(4));	/* *ERROR-OUTPUT* */
	LOAD_SMSTR((CL_FORM *)&KClisp[78], ARG(5));	/* ~&Warning: ~?~% */
	COPY(ARG(0), ARG(6));
	COPY(ARG(1), ARG(7));
	Fformat(ARG(4), 4);
	COPY(ARG(4), ARG(0));
	RESTORE_SPECIAL;
	RESTORE_SPECIAL;
}
