/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kgentemp1[] =
{
	MAKE_STRING(15, "string expected"),	/* 0 */
};

void gentemp1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	Fstringp(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kgentemp1[0], ARG(2));	/* string expected */
		Ferror(ARG(2), 1);
	}
	M1_1:;
	COPY(SYMVAL(Slisp, 675), ARG(2));	/* *GENTEMP-COUNTER* */
	F1plus(ARG(2));
	COPY(ARG(2), SYMVAL(Slisp, 675));	/* *GENTEMP-COUNTER* */
	LOAD_SYMBOL(SYMBOL(Slisp, 44), ARG(2));	/* STRING */
	COPY(ARG(0), ARG(3));
	COPY(SYMVAL(Slisp, 675), ARG(4));	/* *GENTEMP-COUNTER* */
	LOAD_FIXNUM(ARG(5), 10, ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(6));	/* CHARACTER */
	LOAD_NIL(ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(9));	/* T */
	LOAD_FIXNUM(ARG(10), 0, ARG(10));
	LOAD_NIL(ARG(11));
	LOAD_FIXNUM(ARG(12), 0, ARG(12));
	LOAD_NIL(ARG(13));
	LOAD_NIL(ARG(14));
	LOAD_NIL(ARG(15));
	make_array1(ARG(5));
	make_string_output_stream1(ARG(5));
	COPY(ARG(4), ARG(6));
	COPY(ARG(5), ARG(7));
	prin11(ARG(6));
	COPY(ARG(5), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(7));	/* STREAM */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(5))), 0 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
		COPY(ARG(5), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(8));	/* STREAM */
		Ferror(ARG(6), 3);
	}
	if(CL_SYMBOLP(ARG(6)) && GET_SYMBOL(ARG(6)) == SYMBOL(Slisp, 102))	/* STRING-OUTPUT */
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[268], ARG(6));	/* string-output-stream expected */
		Ferror(ARG(6), 1);
	}
	COPY(ARG(5), ARG(6));
	COPY(ARG(6), ARG(7));
	COPY(ARG(7), ARG(8));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(9));	/* STREAM */
	rt_struct_typep(ARG(8));
	if(CL_TRUEP(ARG(8)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(7))), 1 + 1), ARG(6));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
		LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(8));	/* STREAM */
		Ferror(ARG(6), 3);
	}
	Ffuncall(ARG(6), 1);
	mv_count = 1;
	COPY(ARG(6), ARG(4));
	Fconcatenate(ARG(2), 3);
	COPY(ARG(2), ARG(3));
	COPY(ARG(1), ARG(4));
	intern1(ARG(3));
	COPY(&mv_buf[0], ARG(4));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(3));
				case 1:
				LOAD_NIL(ARG(4));
				nargs = 2;
			}
			if(CL_TRUEP(ARG(4)))
			{
			}
			else
			{
				COPY(ARG(3), ARG(0));
				goto RETURN1;
			}
		}
	}
	goto M1_1;
	RETURN1:;
}
