/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void gethash1(CL_FORM *base)
{
	COPY(ARG(0), ARG(3));
	LOAD_FIXNUM(ARG(4), 0, ARG(4));
	internal_sxhash(ARG(3));
	mv_count = 1;
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(5));	/* HASH-TABLE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 0 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(6));	/* HASH-TABLE */
		Ferror(ARG(4), 3);
	}
	COPY(ARG(3), ARG(5));
	COPY(ARG(4), ARG(6));
	rt_floor(ARG(5));
	COPY(&mv_buf[0], ARG(6));
	mv_count = 1;
	{
		COPY(ARG(6), ARG(3));
	}
	COPY(ARG(0), ARG(4));
	COPY(ARG(1), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(6));	/* HASH-TABLE */
	rt_struct_typep(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(5));	/* NO_STRUCT */
		COPY(ARG(1), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(7));	/* HASH-TABLE */
		Ferror(ARG(5), 3);
	}
	LOAD_BOOL(CL_SMVECP(ARG(5)), ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(5), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(8));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(7));
	}
	if(CL_TRUEP(ARG(7)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(6));	/* WRONG_TYPE */
		COPY(ARG(5), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(8));	/* VECTOR */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(3), ARG(6));
	Frow_major_aref(ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 282), ARG(6));	/* TEST */
	COPY(ARG(1), ARG(7));
	LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(8));	/* HASH-TABLE */
	rt_struct_typep(ARG(7));
	if(CL_TRUEP(ARG(7)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 4 + 1), ARG(7));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(7));	/* NO_STRUCT */
		COPY(ARG(1), ARG(8));
		LOAD_SYMBOL(SYMBOL(Slisp, 399), ARG(9));	/* HASH-TABLE */
		Ferror(ARG(7), 3);
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 209), ARG(8));	/* KEY */
	LOAD_GLOBFUN(&CFcar, ARG(9));
	Ffind(ARG(4), 6);
	if(CL_TRUEP(ARG(4)))
	{
		if(CL_CONSP(ARG(4)))
		{
			COPY(GET_CDR(ARG(4)), ARG(5));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(6));	/* T */
		COPY(ARG(5), ARG(0));
		COPY(ARG(6), &mv_buf[0]);
		mv_count = 2;
	}
	else
	{
		COPY(ARG(2), ARG(0));
		LOAD_NIL(ARG(1));
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
	}
}
