/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void intern1(CL_FORM *base)
{
	coerce_to_package(ARG(1));
	COPY(ARG(0), ARG(2));
	COPY(ARG(1), ARG(3));
	find_symbol1(ARG(2));
	COPY(&mv_buf[0], ARG(3));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(2));
				case 1:
				LOAD_NIL(ARG(3));
				nargs = 2;
			}
			if(CL_TRUEP(ARG(3)))
			{
				COPY(ARG(2), ARG(0));
				COPY(ARG(3), ARG(1));
				COPY(ARG(1), &mv_buf[0]);
				mv_count = 2;
			}
			else
			{
				COPY(ARG(0), ARG(4));
				Fmake_symbol(ARG(4));
				COPY(ARG(4), ARG(2));
				COPY(ARG(1), ARG(5));
				internal_import(ARG(4));
				COPY(ARG(2), ARG(0));
				LOAD_NIL(ARG(1));
				COPY(ARG(1), &mv_buf[0]);
				mv_count = 2;
			}
		}
	}
}
