/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Farray_dimension(CL_FORM *base)
{
	LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(4));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(3));
	}
	if(CL_TRUEP(ARG(3)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 152), ARG(2));	/* NO_ARRAY */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
	if(CL_FIXNUMP(ARG(1)))
	{
		LOAD_FIXNUM(ARG(2), 0, ARG(2));
		COPY(ARG(1), ARG(3));
		COPY(ARG(0), ARG(4));
		Farray_rank(ARG(4));
		F1minus(ARG(4));
		Fle(ARG(2), 3);
	}
	else
	{
		goto ELSE2;
	}
	if(CL_TRUEP(ARG(2)))
	{
	}
	else
	{
		ELSE2:;
		LOAD_SMSTR((CL_FORM *)&KClisp[192], ARG(2));	/* The value ~A is not suitable as an axis-number ~
            for an array with rank ~A */
		COPY(ARG(1), ARG(3));
		COPY(ARG(0), ARG(4));
		Farray_rank(ARG(4));
		Ferror(ARG(2), 3);
	}
	if(CL_SMVECP(ARG(0)))
	{
		LOAD_FIXNUM(ARG(3), AR_SIZE(GET_FORM(ARG(0))), ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			complex_vector_length(ARG(0));
		}
		else
		{
			COPY(ARG(0), ARG(2));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(3));	/* COMPLEX-ARRAY */
			rt_struct_typep(ARG(2));
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(0), ARG(2));
				complex_array_dims(ARG(2));
				COPY(ARG(1), ARG(3));
				Felt(ARG(2));
				COPY(ARG(2), ARG(0));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[190], ARG(0));	/* Unexpected error */
				Ferror(ARG(0), 1);
			}
		}
	}
}
