/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void unuse_package1(CL_FORM *base)
{
	coerce_to_package(ARG(1));
	if(CL_LISTP(ARG(0)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Flist(ARG(2), 1);
		COPY(ARG(2), ARG(0));
	}
	LOAD_NIL(ARG(2));
	COPY(ARG(0), ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(ARG(2));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), ARG(2));
	COPY(ARG(2), ARG(4));
	coerce_to_package(ARG(4));
	COPY(ARG(4), ARG(2));
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(1), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 392), ARG(5));	/* COUNT */
	LOAD_FIXNUM(ARG(6), 1, ARG(6));
	Flist(ARG(5), 2);
	LOAD_GLOBFUN(&CFremove, ARG(6));
	COPY(ARG(2), ARG(7));
	COPY(ARG(4), ARG(8));
	COPY(ARG(5), ARG(9));
	Fapply(ARG(6), 4);
	mv_count = 1;
	COPY(ARG(6), ARG(4));
	LOAD_FIXNUM(ARG(5), 5, ARG(5));
	COPY(ARG(1), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(ARG(1))), 5 + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
		COPY(ARG(1), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(2), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
	rt_struct_typep(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 5 + 1), ARG(4));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
		COPY(ARG(2), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		Ferror(ARG(4), 3);
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 392), ARG(5));	/* COUNT */
	LOAD_FIXNUM(ARG(6), 1, ARG(6));
	Flist(ARG(5), 2);
	LOAD_GLOBFUN(&CFremove, ARG(6));
	COPY(ARG(1), ARG(7));
	COPY(ARG(4), ARG(8));
	COPY(ARG(5), ARG(9));
	Fapply(ARG(6), 4);
	mv_count = 1;
	COPY(ARG(6), ARG(4));
	LOAD_FIXNUM(ARG(5), 6, ARG(5));
	COPY(ARG(2), ARG(6));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
	rt_struct_typep(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(ARG(2))), 6 + 1));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
		COPY(ARG(2), ARG(7));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(8));	/* PACKAGE */
		Ferror(ARG(6), 3);
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}
