/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(CPmake_pathname, Pmake_pathname, -1);

void Pmake_pathname(CL_FORM *base, int nargs)
{
	BOOL supl_flags[6];
	static CL_FORM * keylist[] =
	{
		SYMBOL(Slisp, 251),	/* HOST */
		SYMBOL(Slisp, 252),	/* DEVICE */
		SYMBOL(Slisp, 253),	/* DIRECTORY */
		SYMBOL(Slisp, 254),	/* NAME */
		SYMBOL(Slisp, 80),	/* TYPE */
		SYMBOL(Slisp, 255),	/* VERSION */
	};
	keysort(ARG(0), nargs - 0, 6, keylist, supl_flags, FALSE);
	if(NOT(supl_flags[0]))
	{
		LOAD_NIL(ARG(0));
	}
	if(NOT(supl_flags[1]))
	{
		LOAD_NIL(ARG(1));
	}
	if(NOT(supl_flags[2]))
	{
		LOAD_NIL(ARG(2));
	}
	if(NOT(supl_flags[3]))
	{
		LOAD_NIL(ARG(3));
	}
	if(NOT(supl_flags[4]))
	{
		LOAD_NIL(ARG(4));
	}
	if(NOT(supl_flags[5]))
	{
		LOAD_NIL(ARG(5));
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(6));	/* PATHNAME */
	COPY(ARG(0), ARG(7));
	COPY(ARG(1), ARG(8));
	COPY(ARG(2), ARG(9));
	COPY(ARG(3), ARG(10));
	COPY(ARG(4), ARG(11));
	COPY(ARG(5), ARG(12));
	rt_make_struct(ARG(6), 7);
	COPY(ARG(6), ARG(0));
}
