/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z80_lambda(CL_FORM *base);
static void Z81_readc(CL_FORM *base);

void Fmake_concatenated_stream(CL_FORM *base, int nargs)
{
	Flist(ARG(0), nargs - 0);
	GEN_HEAPVAR(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 95), ARG(1));	/* CONCATENATED */
	{
		GEN_CLOSURE(array, ARG(2), 4, Z81_readc, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(2));
	}
	COPY(ARG(2), ARG(2));
	{
		GEN_CLOSURE(array, ARG(3), 4, Z80_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	LOAD_GLOBFUN(&Cclose1, ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(6));
	LOAD_GLOBFUN(&Cnil_fun, ARG(7));
	LOAD_GLOBFUN(&Cnil_fun, ARG(8));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(9));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(11));	/* STREAM */
	COPY(ARG(1), ARG(12));
	LOAD_NIL(ARG(13));
	COPY(ARG(2), ARG(14));
	COPY(ARG(3), ARG(15));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(16));
	LOAD_GLOBFUN(&Cnil_fun, ARG(17));
	LOAD_GLOBFUN(&Cnil_fun, ARG(18));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(19));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(20));
	LOAD_GLOBFUN(&Cclose1, ARG(21));
	rt_make_struct(ARG(11), 11);
	COPY(ARG(11), ARG(0));
}

static void Z80_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	if(CL_CONSP(ARG(2)))
	{
		COPY(GET_CAR(ARG(2)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(3));	/* ~a is not a list */
			COPY(ARG(2), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
		}
	}
	stream_unreadc(ARG(2));
	COPY(ARG(1), ARG(3));
	Ffuncall(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}

static void Z81_readc(CL_FORM *base)
{
	M1_1:;
	if(CL_TRUEP(INDIRECT(GET_FORM(ARG(0)) + 3)))
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CAR(ARG(1)), ARG(1));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		stream_readc(ARG(1));
		Ffuncall(ARG(1), 1);
		mv_count = 1;
		if(CL_TRUEP(ARG(1)))
		{
			COPY(ARG(1), ARG(0));
		}
		else
		{
			if(CL_CONSP(INDIRECT(GET_FORM(ARG(0)) + 3)))
			{
				COPY(GET_CAR(INDIRECT(GET_FORM(ARG(0)) + 3)), ARG(2));
			}
			else
			{
				if(CL_TRUEP(INDIRECT(GET_FORM(ARG(0)) + 3)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
					COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
					Ferror(ARG(2), 2);
				}
				else
				{
					COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
				}
			}
			COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
			COPY(ARG(3), ARG(4));
			if(CL_CONSP(ARG(4)))
			{
				COPY(GET_CDR(ARG(4)), INDIRECT(GET_FORM(ARG(0)) + 3));
			}
			else
			{
				if(CL_TRUEP(ARG(4)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
					COPY(ARG(4), ARG(6));
					Ferror(ARG(5), 2);
				}
				else
				{
					COPY(ARG(4), INDIRECT(GET_FORM(ARG(0)) + 3));
				}
			}
			goto M1_1;
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
	goto RETURN1;
	RETURN1:;
}
