/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kwild_pathname_p1[] =
{
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 0 */
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 2 */
};

void wild_pathname_p1(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(3));	/* PATHNAME */
	rt_struct_typep(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(0), ARG(2));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Fstringp(ARG(2));
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(0), ARG(2));
			LOAD_NIL(ARG(3));
			COPY(SYMVAL(Slisp, 233), ARG(4));	/* *DEFAULT-PATHNAME-DEFAULTS* */
			LOAD_FIXNUM(ARG(5), 0, ARG(5));
			LOAD_NIL(ARG(6));
			LOAD_NIL(ARG(7));
			parse_namestring1(ARG(2));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(0), ARG(2));
			LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(3));	/* STREAM */
			rt_struct_typep(ARG(2));
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(0), ARG(2));
				LOAD_NIL(ARG(3));
				file_name1(ARG(2));
				COPY(SYMVAL(Slisp, 233), ARG(3));	/* *DEFAULT-PATHNAME-DEFAULTS* */
				COPY(ARG(2), ARG(4));
				LOAD_NIL(ARG(5));
				COPY(ARG(3), ARG(6));
				LOAD_FIXNUM(ARG(7), 0, ARG(7));
				LOAD_NIL(ARG(8));
				LOAD_NIL(ARG(9));
				parse_namestring1(ARG(4));
				mv_count = 1;
				COPY(ARG(4), ARG(2));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kwild_pathname_p1[0], ARG(2));	/* etypecase: the value ~a is not a legal value */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
		}
	}
	if(CL_TRUEP(ARG(1)))
	{
		if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 251))	/* HOST */
		{
			COPY(ARG(2), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(4));	/* PATHNAME */
			rt_struct_typep(ARG(3));
			if(CL_TRUEP(ARG(3)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 0 + 1), ARG(3));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
				COPY(ARG(2), ARG(4));
				LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
				Ferror(ARG(3), 3);
			}
			COPY(ARG(3), ARG(0));
			LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(1));	/* PATTERN */
			rt_struct_typep(ARG(0));
		}
		else
		{
			if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 252))	/* DEVICE */
			{
				COPY(ARG(2), ARG(3));
				LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(4));	/* PATHNAME */
				rt_struct_typep(ARG(3));
				if(CL_TRUEP(ARG(3)))
				{
					COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 0 + 1), ARG(3));
				}
				else
				{
					COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
					COPY(ARG(2), ARG(4));
					LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
					Ferror(ARG(3), 3);
				}
				COPY(ARG(3), ARG(0));
				LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(1));	/* PATTERN */
				rt_struct_typep(ARG(0));
			}
			else
			{
				if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 253))	/* DIRECTORY */
				{
					LOAD_GLOBFUN(&Cpattern_p, ARG(3));
					COPY(ARG(2), ARG(4));
					LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
					rt_struct_typep(ARG(4));
					if(CL_TRUEP(ARG(4)))
					{
						COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 2 + 1), ARG(4));
					}
					else
					{
						COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
						COPY(ARG(2), ARG(5));
						LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(6));	/* PATHNAME */
						Ferror(ARG(4), 3);
					}
					Fsome(ARG(3), 2);
					COPY(ARG(3), ARG(0));
				}
				else
				{
					if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 254))	/* NAME */
					{
						COPY(ARG(2), ARG(3));
						LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(4));	/* PATHNAME */
						rt_struct_typep(ARG(3));
						if(CL_TRUEP(ARG(3)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 3 + 1), ARG(3));
						}
						else
						{
							COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
							COPY(ARG(2), ARG(4));
							LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
							Ferror(ARG(3), 3);
						}
						COPY(ARG(3), ARG(0));
						LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(1));	/* PATTERN */
						rt_struct_typep(ARG(0));
					}
					else
					{
						if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 80))	/* TYPE */
						{
							COPY(ARG(2), ARG(3));
							LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(4));	/* PATHNAME */
							rt_struct_typep(ARG(3));
							if(CL_TRUEP(ARG(3)))
							{
								COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 4 + 1), ARG(3));
							}
							else
							{
								COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
								COPY(ARG(2), ARG(4));
								LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
								Ferror(ARG(3), 3);
							}
							COPY(ARG(3), ARG(0));
							LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(1));	/* PATTERN */
							rt_struct_typep(ARG(0));
						}
						else
						{
							if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 255))	/* VERSION */
							{
								COPY(ARG(2), ARG(3));
								LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(4));	/* PATHNAME */
								rt_struct_typep(ARG(3));
								if(CL_TRUEP(ARG(3)))
								{
									COPY(OFFSET(AR_BASE(GET_FORM(ARG(2))), 5 + 1), ARG(3));
								}
								else
								{
									COPY(SYMVAL(Slisp, 352), ARG(3));	/* NO_STRUCT */
									COPY(ARG(2), ARG(4));
									LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(5));	/* PATHNAME */
									Ferror(ARG(3), 3);
								}
								LOAD_BOOL(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 271), ARG(0));	/* WILD */
							}
							else
							{
								LOAD_SMSTR((CL_FORM *)&Kwild_pathname_p1[2], ARG(0));	/* ecase: the value ~a is not a legal value */
								Ferror(ARG(0), 2);
							}
						}
					}
				}
			}
		}
	}
	else
	{
		COPY(ARG(2), ARG(3));
		LOAD_SYMBOL(SYMBOL(Slisp, 251), ARG(4));	/* HOST */
		wild_pathname_p1(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			COPY(ARG(3), ARG(0));
		}
		else
		{
			COPY(ARG(2), ARG(4));
			LOAD_SYMBOL(SYMBOL(Slisp, 252), ARG(5));	/* DEVICE */
			wild_pathname_p1(ARG(4));
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(0));
			}
			else
			{
				COPY(ARG(2), ARG(5));
				LOAD_SYMBOL(SYMBOL(Slisp, 253), ARG(6));	/* DIRECTORY */
				wild_pathname_p1(ARG(5));
				if(CL_TRUEP(ARG(5)))
				{
					COPY(ARG(5), ARG(0));
				}
				else
				{
					COPY(ARG(2), ARG(6));
					LOAD_SYMBOL(SYMBOL(Slisp, 254), ARG(7));	/* NAME */
					wild_pathname_p1(ARG(6));
					if(CL_TRUEP(ARG(6)))
					{
						COPY(ARG(6), ARG(0));
					}
					else
					{
						COPY(ARG(2), ARG(7));
						LOAD_SYMBOL(SYMBOL(Slisp, 80), ARG(8));	/* TYPE */
						wild_pathname_p1(ARG(7));
						if(CL_TRUEP(ARG(7)))
						{
							COPY(ARG(7), ARG(0));
						}
						else
						{
							COPY(ARG(2), ARG(0));
							LOAD_SYMBOL(SYMBOL(Slisp, 255), ARG(1));	/* VERSION */
							wild_pathname_p1(ARG(0));
						}
					}
				}
			}
		}
	}
}
