/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fset_symbol_plist(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(ARG(0), SYM_PLIST(ARG(1)));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(0));	/* SYM_EXPECTED */
			Ferror(ARG(0), 2);
		}
		else
		{
			COPY(ARG(0), SYMVAL(Slisp, 678));	/* *NIL-PLIST* */
		}
	}
}
