/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void array_element_type_internal(CL_FORM *base)
{
	if(CL_SMVECP(ARG(0)))
	{
		rt_plain_vector_element_code(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(2));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			COPY(ARG(0), ARG(1));
			M1_1:;
			complex_base_array_data(ARG(1));
			if(CL_SMVECP(ARG(1)))
			{
			}
			else
			{
				goto M1_1;
			}
			goto RETURN1;
			RETURN1:;
			rt_plain_vector_element_code(ARG(1));
			COPY(ARG(1), ARG(0));
		}
		else
		{
			COPY(SYMVAL(Slisp, 152), ARG(1));	/* NO_ARRAY */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
	}
}
