/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Frow_major_aref(CL_FORM *base)
{
	M1_1:;
	if(CL_SMVEC_T_P(ARG(0)))
	{
		Fsvref(ARG(0));
	}
	else
	{
		if(CL_SMVECP(ARG(0)))
		{
			pvref(ARG(0));
		}
		else
		{
			COPY(ARG(0), ARG(2));
			LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(3));	/* COMPLEX-BASE-ARRAY */
			rt_struct_typep(ARG(2));
			if(CL_TRUEP(ARG(2)))
			{
				COPY(ARG(0), ARG(2));
				complex_base_array_displaced(ARG(2));
				Fminusp(ARG(2));
				if(CL_TRUEP(ARG(2)))
				{
					COPY(ARG(0), ARG(2));
					complex_base_array_data(ARG(2));
					COPY(ARG(1), ARG(3));
					pvref(ARG(2));
					COPY(ARG(2), ARG(0));
				}
				else
				{
					COPY(ARG(1), ARG(2));
					COPY(ARG(0), ARG(3));
					complex_base_array_displaced(ARG(3));
					Fplus(ARG(2), 2);
					COPY(ARG(0), ARG(3));
					complex_base_array_data(ARG(3));
					COPY(ARG(3), ARG(0));
					COPY(ARG(2), ARG(1));
					goto M1_1;
				}
			}
			else
			{
				COPY(SYMVAL(Slisp, 152), ARG(2));	/* NO_ARRAY */
				COPY(ARG(0), ARG(3));
				Ferror(ARG(2), 2);
			}
		}
	}
	goto RETURN1;
	RETURN1:;
}
