/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Finteger_decode_float(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Fdecode_float(ARG(1));
	COPY(&mv_buf[0], ARG(2));
	COPY(&mv_buf[1], ARG(3));
	{
		int nargs;
		nargs = 3;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(1));
				case 1:
				LOAD_NIL(ARG(2));
				case 2:
				LOAD_NIL(ARG(3));
				nargs = 3;
			}
			COPY(SYMVAL(Slisp, 343), ARG(4));	/* I-D-F-FAKTOR */
			COPY(ARG(1), ARG(5));
			Fmult(ARG(4), 2);
			LOAD_FIXNUM(ARG(5), 1, ARG(5));
			LOAD_FIXNUM(ARG(5), 1, ARG(5));
			rt_floor(ARG(4));
			mv_count = 1;
			COPY(ARG(2), ARG(5));
			COPY(SYMVAL(Slisp, 342), ARG(6));	/* FLOAT-SIGNIFICAND-LENGTH */
			Fminus(ARG(5), 2);
			LOAD_FIXNUM(ARG(6), 1, ARG(6));
			COPY(ARG(3), ARG(6));
			LOAD_FIXNUM(ARG(7), 1, ARG(7));
			rt_floor(ARG(6));
			mv_count = 1;
			COPY(ARG(4), ARG(0));
			COPY(ARG(5), &mv_buf[0]);
			COPY(ARG(6), &mv_buf[1]);
			mv_count = 3;
		}
	}
}
