/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void rt_check_array(CL_FORM *base)
{
	COPY(ARG(0), ARG(3));
	Farrayp(ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		check_array_internal(ARG(0));
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
