/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z133_lambda(CL_FORM *base);

void Ffind_all_symbols(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(1));
	LOAD_NIL(ARG(1));
	GEN_HEAPVAR(ARG(1), ARG(2));
	if(CL_SYMBOLP(INDIRECT(ARG(0))) || CL_NILP(INDIRECT(ARG(0))))
	{
		COPY(INDIRECT(ARG(0)), ARG(2));
		if(CL_SYMBOLP(ARG(2)))
		{
			LOAD_SMSTR(SYM_NAME(ARG(2)), INDIRECT(ARG(0)));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], INDIRECT(ARG(0)));	/* NIL */
		}
	}
	LOAD_NIL(ARG(2));
	{
		GEN_CLOSURE(array, ARG(3), 5, Z133_lambda, 1);
		COPY(ARG(1), &array[3]);
		COPY(ARG(0), &array[4]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	COPY(SYMVAL(Slisp, 389), ARG(4));	/* *PACKAGE-ARRAY* */
	Fmap(ARG(2), 3);
	COPY(INDIRECT(ARG(1)), ARG(0));
}

static void Z133_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
	COPY(ARG(1), ARG(3));
	find_symbol1(ARG(2));
	COPY(&mv_buf[0], ARG(3));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(2));
				case 1:
				LOAD_NIL(ARG(3));
				nargs = 2;
			}
			LOAD_CONS((CL_FORM *)&KClisp[88], ARG(4));
			COPY(ARG(3), ARG(5));
			COPY(ARG(4), ARG(6));
			LOAD_NIL(ARG(7));
			LOAD_NIL(ARG(8));
			LOAD_NIL(ARG(9));
			member1(ARG(5));
			if(CL_TRUEP(ARG(5)))
			{
				COPY(ARG(2), ARG(4));
				COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(5));
				COPY(ARG(4), ARG(6));
				COPY(ARG(5), ARG(7));
				LOAD_NIL(ARG(8));
				LOAD_NIL(ARG(9));
				LOAD_NIL(ARG(10));
				adjoin1(ARG(6));
				COPY(ARG(6), INDIRECT(GET_FORM(ARG(0)) + 3));
				COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
	}
}
