/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kmake_pathname1[] =
{
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 0 */
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 2 */
	MAKE_STRING(30, ":WILD-INFERIORS not supported."),	/* 4 */
	MAKE_SYMREF(SYMBOL(Slisp, 274)),	/* 6 CONS(6) UP */
	MAKE_CONSREF(&Kmake_pathname1[8]),
	MAKE_SYMREF(SYMBOL(Slisp, 268)),	/* CONS(8) BACK */
	MAKE_NIL,
	MAKE_STRING(43, "~S is not allowed as a directory component."),	/* 10 */
	MAKE_STRING(44, "etypecase: the value ~a is not a legal value"),	/* 12 */
};

void make_pathname1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(6)))
	{
		COPY(ARG(6), ARG(14));
		LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(15));	/* PATHNAME */
		rt_struct_typep(ARG(14));
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(6), ARG(14));
		}
		else
		{
			COPY(ARG(6), ARG(14));
			Fstringp(ARG(14));
			if(CL_TRUEP(ARG(14)))
			{
				COPY(ARG(6), ARG(14));
				LOAD_NIL(ARG(15));
				COPY(SYMVAL(Slisp, 233), ARG(16));	/* *DEFAULT-PATHNAME-DEFAULTS* */
				LOAD_FIXNUM(ARG(17), 0, ARG(17));
				LOAD_NIL(ARG(18));
				LOAD_NIL(ARG(19));
				parse_namestring1(ARG(14));
				mv_count = 1;
			}
			else
			{
				COPY(ARG(6), ARG(14));
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(15));	/* STREAM */
				rt_struct_typep(ARG(14));
				if(CL_TRUEP(ARG(14)))
				{
					COPY(ARG(6), ARG(14));
					LOAD_NIL(ARG(15));
					file_name1(ARG(14));
					COPY(SYMVAL(Slisp, 233), ARG(15));	/* *DEFAULT-PATHNAME-DEFAULTS* */
					COPY(ARG(14), ARG(16));
					LOAD_NIL(ARG(17));
					COPY(ARG(15), ARG(18));
					LOAD_FIXNUM(ARG(19), 0, ARG(19));
					LOAD_NIL(ARG(20));
					LOAD_NIL(ARG(21));
					parse_namestring1(ARG(16));
					mv_count = 1;
					COPY(ARG(16), ARG(14));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[0], ARG(14));	/* etypecase: the value ~a is not a legal value */
					COPY(ARG(6), ARG(15));
					Ferror(ARG(14), 2);
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(14));
	}
	if(CL_TRUEP(ARG(14)))
	{
		COPY(ARG(14), ARG(15));
		LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(16));	/* PATHNAME */
		rt_struct_typep(ARG(15));
		if(CL_TRUEP(ARG(15)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 0 + 1), ARG(15));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(15));	/* NO_STRUCT */
			COPY(ARG(14), ARG(16));
			LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(17));	/* PATHNAME */
			Ferror(ARG(15), 3);
		}
	}
	else
	{
		COPY(SYMVAL(Slisp, 233), ARG(15));	/* *DEFAULT-PATHNAME-DEFAULTS* */
		LOAD_SYMBOL(SYMBOL(Slisp, 276), ARG(16));	/* LOCAL */
		pathname_host1(ARG(15));
	}
	if(CL_TRUEP(ARG(8)))
	{
		COPY(ARG(0), ARG(16));
	}
	else
	{
		COPY(ARG(15), ARG(16));
	}
	if(CL_SYMBOLP(ARG(7)) && GET_SYMBOL(ARG(7)) == SYMBOL(Slisp, 278))	/* COMMON */
	{
		COPY(ARG(16), ARG(17));
		LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(18));	/* HOST */
		rt_struct_typep(ARG(17));
		if(CL_TRUEP(ARG(17)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(16))), 6 + 1), ARG(17));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(17));	/* NO_STRUCT */
			COPY(ARG(16), ARG(18));
			LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(19));	/* HOST */
			Ferror(ARG(17), 3);
		}
		LOAD_BOOL(CL_SYMBOLP(ARG(17)) && GET_SYMBOL(ARG(17)) == SYMBOL(Slisp, 279), ARG(17));	/* LOWER */
	}
	else
	{
		LOAD_NIL(ARG(17));
	}
	COPY(ARG(16), ARG(18));
	LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(19));	/* HOST */
	rt_struct_typep(ARG(18));
	if(CL_TRUEP(ARG(18)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(16))), 6 + 1), ARG(18));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(18));	/* NO_STRUCT */
		COPY(ARG(16), ARG(19));
		LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(20));	/* HOST */
		Ferror(ARG(18), 3);
	}
	COPY(ARG(15), ARG(19));
	LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(20));	/* HOST */
	rt_struct_typep(ARG(19));
	if(CL_TRUEP(ARG(19)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(ARG(15))), 6 + 1), ARG(19));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(19));	/* NO_STRUCT */
		COPY(ARG(15), ARG(20));
		LOAD_SYMBOL(SYMBOL(Slisp, 263), ARG(21));	/* HOST */
		Ferror(ARG(19), 3);
	}
	LOAD_BOOL(EQ(ARG(18), ARG(19)), ARG(18));
	if(CL_TRUEP(ARG(18)))
	{
		LOAD_NIL(ARG(18));
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(18));	/* T */
	}
	COPY(ARG(16), ARG(19));
	if(CL_TRUEP(ARG(9)))
	{
		COPY(ARG(1), ARG(20));
	}
	else
	{
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(14), ARG(20));
			LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(21));	/* PATHNAME */
			rt_struct_typep(ARG(20));
			if(CL_TRUEP(ARG(20)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 1 + 1), ARG(20));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(20));	/* NO_STRUCT */
				COPY(ARG(14), ARG(21));
				LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(22));	/* PATHNAME */
				Ferror(ARG(20), 3);
			}
		}
		else
		{
			LOAD_NIL(ARG(20));
		}
	}
	COPY(ARG(2), ARG(21));
	COPY(ARG(17), ARG(22));
	if(CL_TRUEP(ARG(21)))
	{
		if(CL_LISTP(ARG(21)))
		{
			LOAD_NIL(ARG(23));
			LOAD_NIL(ARG(24));
			ALLOC_CONS(ARG(25), ARG(23), ARG(24), ARG(23));
			COPY(GET_CAR(ARG(21)), ARG(24));
			COPY(ARG(21), ARG(25));
			COPY(ARG(25), ARG(26));
			COPY(GET_CDR(ARG(26)), ARG(21));
			if(CL_SYMBOLP(ARG(24)) && GET_SYMBOL(ARG(24)) == SYMBOL(Slisp, 267))	/* ABSOLUTE */
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 267), ARG(25));	/* ABSOLUTE */
				COPY(ARG(23), ARG(26));
				add_q(ARG(25));
			}
			else
			{
				if(CL_SYMBOLP(ARG(24)) && GET_SYMBOL(ARG(24)) == SYMBOL(Slisp, 270))	/* RELATIVE */
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 270), ARG(25));	/* RELATIVE */
					COPY(ARG(23), ARG(26));
					add_q(ARG(25));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[2], ARG(25));	/* ecase: the value ~a is not a legal value */
					COPY(ARG(24), ARG(26));
					Ferror(ARG(25), 2);
				}
			}
			LOAD_NIL(ARG(24));
			COPY(ARG(21), ARG(25));
			M1_1:;
			if(CL_ATOMP(ARG(25)))
			{
				LOAD_NIL(ARG(24));
				goto RETURN1;
			}
			COPY(ARG(25), ARG(26));
			COPY(GET_CAR(ARG(26)), ARG(24));
			if(CL_SYMBOLP(ARG(24)) && GET_SYMBOL(ARG(24)) == SYMBOL(Slisp, 271))	/* WILD */
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(26));	/* PATTERN */
				LOAD_SYMBOL(SYMBOL(Slisp, 272), ARG(27));	/* MULTI-CHAR-WILD */
				Flist(ARG(27), 1);
				rt_make_struct(ARG(26), 2);
				COPY(ARG(23), ARG(27));
				add_q(ARG(26));
			}
			else
			{
				if(CL_SYMBOLP(ARG(24)) && GET_SYMBOL(ARG(24)) == SYMBOL(Slisp, 273))	/* WILD-INFERIORS */
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[4], ARG(26));	/* :WILD-INFERIORS not supported. */
					Ferror(ARG(26), 1);
				}
				else
				{
					LOAD_CONS((CL_FORM *)&Kmake_pathname1[6], ARG(26));
					COPY(ARG(24), ARG(27));
					COPY(ARG(26), ARG(28));
					LOAD_NIL(ARG(29));
					LOAD_NIL(ARG(30));
					LOAD_NIL(ARG(31));
					member1(ARG(27));
					if(CL_TRUEP(ARG(27)))
					{
						COPY(ARG(24), ARG(26));
						COPY(ARG(23), ARG(27));
						add_q(ARG(26));
					}
					else
					{
						LOAD_BOOL(CL_SMSTRP(ARG(24)), ARG(26));
						if(CL_TRUEP(ARG(26)))
						{
							goto THEN1;
						}
						else
						{
							COPY(ARG(24), ARG(27));
							LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(28));	/* PATTERN */
							rt_struct_typep(ARG(27));
						}
						if(CL_TRUEP(ARG(27)))
						{
							THEN1:;
							COPY(ARG(24), ARG(26));
							COPY(ARG(22), ARG(27));
							maybe_diddle_case(ARG(26));
							mv_count = 1;
							COPY(ARG(23), ARG(27));
							add_q(ARG(26));
						}
						else
						{
							COPY(ARG(24), ARG(26));
							Fstringp(ARG(26));
							if(CL_TRUEP(ARG(26)))
							{
								COPY(ARG(24), ARG(26));
								LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(27));	/* SIMPLE-STRING */
								Fcoerce(ARG(26));
								COPY(ARG(22), ARG(27));
								maybe_diddle_case(ARG(26));
								mv_count = 1;
								COPY(ARG(23), ARG(27));
								add_q(ARG(26));
							}
							else
							{
								LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[10], ARG(26));	/* ~S is not allowed as a directory component. */
								COPY(ARG(24), ARG(27));
								Ferror(ARG(26), 2);
							}
						}
					}
				}
			}
			COPY(ARG(25), ARG(26));
			COPY(GET_CDR(ARG(26)), ARG(25));
			goto M1_1;
			RETURN1:;
			COPY(GET_CAR(ARG(23)), ARG(21));
		}
		else
		{
			if(CL_SMSTRP(ARG(21)))
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 267), ARG(23));	/* ABSOLUTE */
				COPY(ARG(21), ARG(24));
				COPY(ARG(22), ARG(25));
				maybe_diddle_case(ARG(24));
				mv_count = 1;
				Flist(ARG(23), 2);
				COPY(ARG(23), ARG(21));
			}
			else
			{
				COPY(ARG(21), ARG(23));
				Fstringp(ARG(23));
				if(CL_TRUEP(ARG(23)))
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 267), ARG(23));	/* ABSOLUTE */
					COPY(ARG(21), ARG(24));
					LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(25));	/* SIMPLE-STRING */
					Fcoerce(ARG(24));
					COPY(ARG(22), ARG(25));
					maybe_diddle_case(ARG(24));
					mv_count = 1;
					Flist(ARG(23), 2);
					COPY(ARG(23), ARG(21));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kmake_pathname1[12], ARG(23));	/* etypecase: the value ~a is not a legal value */
					COPY(ARG(21), ARG(24));
					Ferror(ARG(23), 2);
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(21));
	}
	if(CL_TRUEP(ARG(14)))
	{
		if(CL_TRUEP(ARG(10)))
		{
			goto ELSE2;
		}
		else
		{
			goto THEN3;
		}
	}
	else
	{
		goto ELSE2;
	}
	{
		THEN3:;
		COPY(ARG(21), ARG(22));
		COPY(ARG(14), ARG(23));
		LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(24));	/* PATHNAME */
		rt_struct_typep(ARG(23));
		if(CL_TRUEP(ARG(23)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 2 + 1), ARG(23));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(23));	/* NO_STRUCT */
			COPY(ARG(14), ARG(24));
			LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(25));	/* PATHNAME */
			Ferror(ARG(23), 3);
		}
		COPY(ARG(18), ARG(24));
		merge_directories(ARG(22));
		COPY(ARG(22), ARG(21));
	}
	goto ENDIF4;
	{
		ELSE2:;
	}
	ENDIF4:;
	if(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 271))	/* WILD */
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(22));	/* PATTERN */
		LOAD_SYMBOL(SYMBOL(Slisp, 272), ARG(23));	/* MULTI-CHAR-WILD */
		Flist(ARG(23), 1);
		rt_make_struct(ARG(22), 2);
	}
	else
	{
		LOAD_BOOL(CL_SMSTRP(ARG(3)), ARG(22));
		if(CL_TRUEP(ARG(22)))
		{
			goto THEN5;
		}
		else
		{
			COPY(ARG(3), ARG(23));
			LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(24));	/* PATTERN */
			rt_struct_typep(ARG(23));
		}
		if(CL_TRUEP(ARG(23)))
		{
			THEN5:;
			COPY(ARG(3), ARG(22));
			COPY(ARG(17), ARG(23));
			maybe_diddle_case(ARG(22));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(3), ARG(22));
			Fstringp(ARG(22));
			if(CL_TRUEP(ARG(22)))
			{
				COPY(ARG(3), ARG(22));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(23));	/* SIMPLE-STRING */
				Fcoerce(ARG(22));
				COPY(ARG(17), ARG(23));
				maybe_diddle_case(ARG(22));
				mv_count = 1;
			}
			else
			{
				if(CL_TRUEP(ARG(11)))
				{
					COPY(ARG(3), ARG(22));
					COPY(ARG(17), ARG(23));
					maybe_diddle_case(ARG(22));
					mv_count = 1;
				}
				else
				{
					if(CL_TRUEP(ARG(14)))
					{
						COPY(ARG(14), ARG(22));
						LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(23));	/* PATHNAME */
						rt_struct_typep(ARG(22));
						if(CL_TRUEP(ARG(22)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 3 + 1), ARG(22));
						}
						else
						{
							COPY(SYMVAL(Slisp, 352), ARG(22));	/* NO_STRUCT */
							COPY(ARG(14), ARG(23));
							LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(24));	/* PATHNAME */
							Ferror(ARG(22), 3);
						}
						COPY(ARG(18), ARG(23));
						maybe_diddle_case(ARG(22));
						mv_count = 1;
					}
					else
					{
						LOAD_NIL(ARG(22));
					}
				}
			}
		}
	}
	if(CL_SYMBOLP(ARG(4)) && GET_SYMBOL(ARG(4)) == SYMBOL(Slisp, 271))	/* WILD */
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(23));	/* PATTERN */
		LOAD_SYMBOL(SYMBOL(Slisp, 272), ARG(24));	/* MULTI-CHAR-WILD */
		Flist(ARG(24), 1);
		rt_make_struct(ARG(23), 2);
	}
	else
	{
		LOAD_BOOL(CL_SMSTRP(ARG(4)), ARG(23));
		if(CL_TRUEP(ARG(23)))
		{
			goto THEN6;
		}
		else
		{
			COPY(ARG(4), ARG(24));
			LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(25));	/* PATTERN */
			rt_struct_typep(ARG(24));
		}
		if(CL_TRUEP(ARG(24)))
		{
			THEN6:;
			COPY(ARG(4), ARG(23));
			COPY(ARG(17), ARG(24));
			maybe_diddle_case(ARG(23));
			mv_count = 1;
		}
		else
		{
			COPY(ARG(4), ARG(23));
			Fstringp(ARG(23));
			if(CL_TRUEP(ARG(23)))
			{
				COPY(ARG(4), ARG(23));
				LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(24));	/* SIMPLE-STRING */
				Fcoerce(ARG(23));
				COPY(ARG(17), ARG(24));
				maybe_diddle_case(ARG(23));
				mv_count = 1;
			}
			else
			{
				if(CL_TRUEP(ARG(12)))
				{
					COPY(ARG(4), ARG(23));
					COPY(ARG(17), ARG(24));
					maybe_diddle_case(ARG(23));
					mv_count = 1;
				}
				else
				{
					if(CL_TRUEP(ARG(14)))
					{
						COPY(ARG(14), ARG(23));
						LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(24));	/* PATHNAME */
						rt_struct_typep(ARG(23));
						if(CL_TRUEP(ARG(23)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 4 + 1), ARG(23));
						}
						else
						{
							COPY(SYMVAL(Slisp, 352), ARG(23));	/* NO_STRUCT */
							COPY(ARG(14), ARG(24));
							LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(25));	/* PATHNAME */
							Ferror(ARG(23), 3);
						}
						COPY(ARG(18), ARG(24));
						maybe_diddle_case(ARG(23));
						mv_count = 1;
					}
					else
					{
						LOAD_NIL(ARG(23));
					}
				}
			}
		}
	}
	if(CL_TRUEP(ARG(13)))
	{
		COPY(ARG(5), ARG(24));
	}
	else
	{
		if(CL_TRUEP(ARG(14)))
		{
			COPY(ARG(14), ARG(24));
			LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(25));	/* PATHNAME */
			rt_struct_typep(ARG(24));
			if(CL_TRUEP(ARG(24)))
			{
				COPY(OFFSET(AR_BASE(GET_FORM(ARG(14))), 5 + 1), ARG(24));
			}
			else
			{
				COPY(SYMVAL(Slisp, 352), ARG(24));	/* NO_STRUCT */
				COPY(ARG(14), ARG(25));
				LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(26));	/* PATHNAME */
				Ferror(ARG(24), 3);
			}
		}
		else
		{
			LOAD_NIL(ARG(24));
		}
	}
	LOAD_SYMBOL(SYMBOL(Slisp, 234), ARG(0));	/* PATHNAME */
	COPY(ARG(19), ARG(1));
	COPY(ARG(20), ARG(2));
	COPY(ARG(21), ARG(3));
	COPY(ARG(22), ARG(4));
	COPY(ARG(23), ARG(5));
	COPY(ARG(24), ARG(6));
	rt_make_struct(ARG(0), 7);
}
