/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fadjustable_array_p(CL_FORM *base)
{
	if(CL_SMVECP(ARG(0)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(1));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(2));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
		}
		else
		{
			COPY(SYMVAL(Slisp, 152), ARG(1));	/* NO_ARRAY */
			COPY(ARG(0), ARG(2));
			Ferror(ARG(1), 2);
		}
	}
}
