/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z82_lambda(CL_FORM *base);
static void Z83_lambda(CL_FORM *base);
static void Z84_lambda(CL_FORM *base);
static void Z85_lambda(CL_FORM *base);

void Fmake_two_way_stream(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(2));
	GEN_HEAPVAR(ARG(1), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 96), ARG(2));	/* TWO-WAY */
	{
		GEN_CLOSURE(array, ARG(3), 4, Z85_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	{
		GEN_CLOSURE(array, ARG(4), 4, Z84_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(4));
	}
	COPY(ARG(4), ARG(4));
	{
		GEN_CLOSURE(array, ARG(5), 4, Z83_lambda, 0);
		COPY(ARG(1), &array[3]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 4, Z82_lambda, 0);
		COPY(ARG(1), &array[3]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	LOAD_GLOBFUN(&Cclose1, ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_GLOBFUN(&Cnil_fun, ARG(9));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(10));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(11));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(0));	/* STREAM */
	COPY(ARG(2), ARG(1));
	LOAD_NIL(ARG(2));
	LOAD_GLOBFUN(&Cnil_fun, ARG(7));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(8));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(9));
	LOAD_GLOBFUN(&Cclose1, ARG(10));
	rt_make_struct(ARG(0), 11);
}

static void Z82_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	stream_column(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z83_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	stream_writec(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z84_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	stream_unreadc(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z85_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	stream_readc(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}
