/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void bq_attach_conses(CL_FORM *base)
{
	LOAD_GLOBFUN(&Cnull_or_quoted, ARG(2));
	COPY(ARG(0), ARG(3));
	Fevery(ARG(2), 2);
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(1), ARG(2));
		null_or_quoted(ARG(2));
	}
	else
	{
		goto ELSE1;
	}
	if(CL_TRUEP(ARG(2)))
	{
		COPY(SYMVAL(Slisp, 444), ARG(2));	/* *BQ-QUOTE* */
		LOAD_GLOBFUN(&CFcadr, ARG(3));
		COPY(ARG(0), ARG(4));
		Fmapcar(ARG(3), 2);
		if(CL_CONSP(ARG(1)))
		{
			COPY(GET_CDR(ARG(1)), ARG(4));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(4));	/* ~a is not a list */
				COPY(ARG(1), ARG(5));
				Ferror(ARG(4), 2);
			}
			else
			{
				COPY(ARG(1), ARG(4));
			}
		}
		if(CL_CONSP(ARG(4)))
		{
			COPY(GET_CAR(ARG(4)), ARG(4));
		}
		else
		{
			if(CL_TRUEP(ARG(4)))
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(5));	/* ~a is not a list */
				COPY(ARG(4), ARG(6));
				Ferror(ARG(5), 2);
			}
			else
			{
			}
		}
		Fappend(ARG(3), 2);
		Flist(ARG(2), 2);
		COPY(ARG(2), ARG(0));
	}
	else
	{
		ELSE1:;
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_NIL(ARG(2));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(2));	/* T */
		}
		if(CL_TRUEP(ARG(2)))
		{
			goto THEN2;
		}
		else
		{
			COPY(ARG(1), ARG(3));
			COPY(SYMVAL(Slisp, 445), ARG(4));	/* *BQ-QUOTE-NIL* */
			Fequal(ARG(3));
		}
		if(CL_TRUEP(ARG(3)))
		{
			THEN2:;
			ALLOC_CONS(ARG(3), SYMVAL(Slisp, 439), ARG(0), ARG(0));	/* *BQ-LIST* */
		}
		else
		{
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CAR(ARG(1)), ARG(2));
				LOAD_BOOL(EQ(ARG(2), SYMVAL(Slisp, 439)), ARG(2));	/* *BQ-LIST* */
				if(CL_TRUEP(ARG(2)))
				{
					goto THEN3;
				}
				else
				{
					COPY(GET_CAR(ARG(1)), ARG(3));
				}	/* *BQ-LIST** */
			}
			else
			{
				goto ELSE4;
			}
			if(EQ(ARG(3), SYMVAL(Slisp, 441)))
			{
				THEN3:;
				if(CL_CONSP(ARG(1)))
				{
					COPY(GET_CAR(ARG(1)), ARG(2));
				}
				else
				{
					if(CL_TRUEP(ARG(1)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
						COPY(ARG(1), ARG(3));
						Ferror(ARG(2), 2);
					}
					else
					{
						COPY(ARG(1), ARG(2));
					}
				}
				COPY(ARG(0), ARG(3));
				if(CL_CONSP(ARG(1)))
				{
					COPY(GET_CDR(ARG(1)), ARG(4));
				}
				else
				{
					if(CL_TRUEP(ARG(1)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(4));	/* ~a is not a list */
						COPY(ARG(1), ARG(5));
						Ferror(ARG(4), 2);
					}
					else
					{
						COPY(ARG(1), ARG(4));
					}
				}
				Fappend(ARG(3), 2);
				ALLOC_CONS(ARG(4), ARG(2), ARG(3), ARG(0));
			}
			else
			{
				ELSE4:;
				COPY(ARG(0), ARG(2));	/* *BQ-LIST** */
				COPY(ARG(1), ARG(3));
				Flist(ARG(3), 1);
				Fappend(ARG(2), 2);
				ALLOC_CONS(ARG(3), SYMVAL(Slisp, 441), ARG(2), ARG(0));
			}
		}
	}
}
