/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z72_lambda(CL_FORM *base);
static void Z73_lambda(CL_FORM *base);
static void Z74_lambda(CL_FORM *base);
static void Z75_lambda(CL_FORM *base);
static void Z76_lambda(CL_FORM *base);
static void Z77_lambda(CL_FORM *base);
static void Z78_lambda(CL_FORM *base);

void Fmake_synonym_stream(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 93), ARG(1));	/* SYNONYM */
	COPY(INDIRECT(ARG(0)), ARG(2));
	{
		GEN_CLOSURE(array, ARG(3), 4, Z78_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	{
		GEN_CLOSURE(array, ARG(4), 4, Z77_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(4));
	}
	COPY(ARG(4), ARG(4));
	{
		GEN_CLOSURE(array, ARG(5), 4, Z76_lambda, 1);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 4, Z75_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	{
		GEN_CLOSURE(array, ARG(7), 4, Z74_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(7));
	}
	COPY(ARG(7), ARG(7));
	{
		GEN_CLOSURE(array, ARG(8), 4, Z73_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(8));
	}
	COPY(ARG(8), ARG(8));
	{
		GEN_CLOSURE(array, ARG(9), 4, Z72_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(9));
	}
	COPY(ARG(9), ARG(9));
	LOAD_GLOBFUN(&Cclose1, ARG(10));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(0));	/* STREAM */
	LOAD_GLOBFUN(&Cclose1, ARG(10));
	rt_make_struct(ARG(0), 11);
}

static void Z72_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(SYM_VALUE(ARG(1)), ARG(1));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_NIL(ARG(1));
		}
	}
	stream_length(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z73_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(SYM_VALUE(ARG(1)), ARG(1));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_NIL(ARG(1));
		}
	}
	stream_seek(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z74_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(SYM_VALUE(ARG(1)), ARG(1));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_NIL(ARG(1));
		}
	}
	stream_tell(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z75_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(SYM_VALUE(ARG(1)), ARG(1));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_NIL(ARG(1));
		}
	}
	stream_column(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}

static void Z76_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	if(CL_SYMBOLP(ARG(2)))
	{
		COPY(SYM_VALUE(ARG(2)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(3));	/* SYM_EXPECTED */
			COPY(ARG(2), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
			LOAD_NIL(ARG(2));
		}
	}
	stream_writec(ARG(2));
	COPY(ARG(1), ARG(3));
	Ffuncall(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}

static void Z77_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(2));
	if(CL_SYMBOLP(ARG(2)))
	{
		COPY(SYM_VALUE(ARG(2)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(2)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(3));	/* SYM_EXPECTED */
			COPY(ARG(2), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
			LOAD_NIL(ARG(2));
		}
	}
	stream_unreadc(ARG(2));
	COPY(ARG(1), ARG(3));
	Ffuncall(ARG(2), 2);
	COPY(ARG(2), ARG(0));
}

static void Z78_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	if(CL_SYMBOLP(ARG(1)))
	{
		COPY(SYM_VALUE(ARG(1)), ARG(1));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_NIL(ARG(1));
		}
	}
	stream_readc(ARG(1));
	Ffuncall(ARG(1), 1);
	COPY(ARG(1), ARG(0));
}
