/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fget_dispatch_macro_character(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 2:
		COPY(SYMVAL(Slisp, 454), ARG(2));	/* *READTABLE* */
		case 3:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	get_dispatch_macro_character1(ARG(0));
}
