/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kcomponents_match[] =
{
	MAKE_SYMREF(SYMBOL(Slisp, 272)),	/* 0 CONS(0) MULTI-CHAR-WILD */
	MAKE_NIL,
};

void components_match(CL_FORM *base)
{
	M1_1:;
	LOAD_BOOL(EQ(ARG(0), ARG(1)), ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(2), ARG(0));
	}
	else
	{
		if(CL_SMSTRP(ARG(0)))
		{
			COPY(ARG(1), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(4));	/* PATTERN */
			rt_struct_typep(ARG(3));
			if(CL_TRUEP(ARG(3)))
			{
				COPY(ARG(1), ARG(3));
				COPY(ARG(0), ARG(4));
				pattern_matches(ARG(3));
				mv_count = 1;
				COPY(ARG(3), ARG(0));
			}
			else
			{
				if(CL_SMSTRP(ARG(1)))
				{
					LOAD_FIXNUM(ARG(2), 0, ARG(2));
					LOAD_NIL(ARG(3));
					LOAD_FIXNUM(ARG(4), 0, ARG(4));
					LOAD_NIL(ARG(5));
					stringE1(ARG(0));
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
		}
		else
		{
			COPY(ARG(0), ARG(3));
			LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(4));	/* PATTERN */
			rt_struct_typep(ARG(3));
			if(CL_TRUEP(ARG(3)))
			{
				COPY(ARG(1), ARG(3));
				LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(4));	/* PATTERN */
				rt_struct_typep(ARG(3));
				if(CL_TRUEP(ARG(3)))
				{
					patternE(ARG(0));
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
			else
			{
				if(CL_CONSP(ARG(0)))
				{
					if(CL_CONSP(ARG(1)))
					{
						COPY(GET_CAR(ARG(0)), ARG(3));
						COPY(GET_CAR(ARG(1)), ARG(4));
						components_match(ARG(3));
						if(CL_TRUEP(ARG(3)))
						{
							COPY(GET_CDR(ARG(0)), ARG(3));
							COPY(GET_CDR(ARG(1)), ARG(4));
							COPY(ARG(3), ARG(0));
							COPY(ARG(4), ARG(1));
							goto M1_1;
						}
						else
						{
							LOAD_NIL(ARG(0));
						}
					}
					else
					{
						LOAD_NIL(ARG(0));
					}
				}
				else
				{
					LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 268), ARG(3));	/* BACK */
					if(CL_TRUEP(ARG(3)))
					{
						goto THEN1;
					}
					else
					{
						LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 274), ARG(4));	/* UP */
						if(CL_TRUEP(ARG(4)))
						{
							goto THEN1;
						}
						else
						{
							LOAD_BOOL(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 266), ARG(5));	/* UNSPECIFIC */
							if(CL_TRUEP(ARG(5)))
							{
								goto THEN1;
							}
							else
							{
								if(CL_TRUEP(ARG(0)))
								{
									goto ELSE2;
								}
								else
								{
									goto THEN1;
								}
							}
						}
					}
					{
						THEN1:;
						COPY(ARG(1), ARG(3));
						LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(4));	/* PATTERN */
						rt_struct_typep(ARG(3));
						if(CL_TRUEP(ARG(3)))
						{
							COPY(ARG(1), ARG(0));
							pattern_pieces(ARG(0));
							LOAD_CONS((CL_FORM *)&Kcomponents_match[0], ARG(1));
							Fequal(ARG(0));
						}
						else
						{
							LOAD_NIL(ARG(0));
						}
					}
					goto ENDIF3;
					{
						ELSE2:;
						LOAD_NIL(ARG(0));
					}
					ENDIF3:;
				}
			}
		}
	}
	goto RETURN1;
	RETURN1:;
}
