/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Farray_element_type(CL_FORM *base)
{
	array_element_type_internal(ARG(0));
	to_element_type(ARG(0));
}
