/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void internal_import(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)))
	{
		LOAD_SMSTR(SYM_NAME(ARG(0)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(0), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(2));	/* NIL */
		}
	}
	LOAD_FIXNUM(ARG(3), 101, ARG(3));
	COPY(ARG(2), ARG(4));
	string_to_simple_string(ARG(4));
	rt_sxhash_string(ARG(4));
	COPY(ARG(4), ARG(5));
	LOAD_FIXNUM(ARG(6), 101, ARG(6));
	rt_floor(ARG(5));
	COPY(&mv_buf[0], ARG(6));
	mv_count = 1;
	{
		COPY(ARG(6), ARG(2));
	}
	if(CL_SYMBOLP(ARG(0)))
	{
		bool_result = CL_TRUEP(SYM_PACKAGE(ARG(0)));
	}
	else
	{
		if(CL_TRUEP(ARG(0)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(3));	/* SYM_EXPECTED */
			COPY(ARG(0), ARG(4));
			Ferror(ARG(3), 2);
		}
		else
		{
			bool_result = CL_TRUEP(SYMVAL(Slisp, 679));	/* *NIL-PACKAGE* */
		}
	}
	if(bool_result)
	{
	}
	else
	{
		COPY(ARG(0), ARG(3));
		COPY(ARG(1), ARG(4));
		set_symbol_package(ARG(3));
	}
	if(EQ(ARG(1), SYMVAL(Slisp, 390)))	/* *KEYWORD-PACKAGE* */
	{
		COPY(ARG(0), ARG(3));
		COPY(ARG(0), ARG(4));
		Fset(ARG(3));
		SYM_SET_CONST(ARG(0));
		COPY(ARG(1), ARG(3));
		Ppackage_external(ARG(3));
		COPY(ARG(3), ARG(5));
		COPY(ARG(2), ARG(6));
		Fsvref(ARG(5));
		ALLOC_CONS(ARG(6), ARG(0), ARG(5), ARG(4));
		COPY(ARG(3), ARG(5));
		COPY(ARG(2), ARG(6));
		Fset_svref(ARG(4));
		COPY(ARG(4), ARG(0));
	}
	else
	{
		COPY(ARG(1), ARG(3));
		Ppackage_internal(ARG(3));
		COPY(ARG(3), ARG(5));
		COPY(ARG(2), ARG(6));
		Fsvref(ARG(5));
		ALLOC_CONS(ARG(6), ARG(0), ARG(5), ARG(4));
		COPY(ARG(3), ARG(5));
		COPY(ARG(2), ARG(6));
		Fset_svref(ARG(4));
		COPY(ARG(4), ARG(0));
	}
}
