/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kcoerce_to_package[] =
{
	MAKE_STRING(32, "there is no Package with name ~S"),	/* 0 */
};

void coerce_to_package(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(0)) || CL_NILP(ARG(0)))
	{
		COPY(ARG(0), ARG(1));
		if(CL_SYMBOLP(ARG(1)))
		{
			LOAD_SMSTR(SYM_NAME(ARG(1)), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(0));	/* NIL */
		}
	}
	COPY(ARG(0), ARG(1));
	Fstringp(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		Ffind_package(ARG(0));
	}
	COPY(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(2));	/* PACKAGE */
	rt_struct_typep(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kcoerce_to_package[0], ARG(1));	/* there is no Package with name ~S */
		COPY(ARG(0), ARG(2));
		Ferror(ARG(1), 2);
	}
}
