/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kunparse_unix_directory_list[] =
{
	MAKE_STRING(1, "/"),	/* 0 */
	MAKE_STRING(40, "ecase: the value ~a is not a legal value"),	/* 2 */
	MAKE_STRING(3, "../"),	/* 4 */
	MAKE_STRING(43, ":BACK cannot be represented in namestrings."),	/* 6 */
	MAKE_STRING(1, "/"),	/* 8 */
	MAKE_STRING(31, "Invalid directory component: ~S"),	/* 10 */
};

void unparse_unix_directory_list(CL_FORM *base)
{
	LOAD_NIL(ARG(1));
	LOAD_NIL(ARG(2));
	ALLOC_CONS(ARG(3), ARG(1), ARG(2), ARG(1));
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(GET_CAR(ARG(0)), ARG(2));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(2));	/* ~a is not a list */
			COPY(ARG(0), ARG(3));
			Ferror(ARG(2), 2);
		}
		COPY(ARG(0), ARG(3));
		COPY(ARG(3), ARG(4));
		if(CL_CONSP(ARG(4)))
		{
			COPY(GET_CDR(ARG(4)), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
			COPY(ARG(4), ARG(6));
			Ferror(ARG(5), 2);
		}
		if(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 267))	/* ABSOLUTE */
		{
			LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[0], ARG(3));	/* / */
			COPY(ARG(1), ARG(4));
			add_q(ARG(3));
		}
		else
		{
			LOAD_BOOL(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 270), ARG(3));	/* RELATIVE */
			if(CL_TRUEP(ARG(3)))
			{
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[2], ARG(4));	/* ecase: the value ~a is not a legal value */
				COPY(ARG(2), ARG(5));
				Ferror(ARG(4), 2);
			}
		}
		LOAD_NIL(ARG(2));
		COPY(ARG(0), ARG(3));
		M1_1:;
		if(CL_ATOMP(ARG(3)))
		{
			LOAD_NIL(ARG(2));
			goto RETURN1;
		}
		COPY(ARG(3), ARG(4));
		COPY(GET_CAR(ARG(4)), ARG(2));
		if(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 274))	/* UP */
		{
			LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[4], ARG(4));	/* ../ */
			COPY(ARG(1), ARG(5));
			add_q(ARG(4));
		}
		else
		{
			if(CL_SYMBOLP(ARG(2)) && GET_SYMBOL(ARG(2)) == SYMBOL(Slisp, 268))	/* BACK */
			{
				LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[6], ARG(4));	/* :BACK cannot be represented in namestrings. */
				Ferror(ARG(4), 1);
			}
			else
			{
				LOAD_BOOL(CL_SMSTRP(ARG(2)), ARG(4));
				if(CL_TRUEP(ARG(4)))
				{
					goto THEN1;
				}
				else
				{
					COPY(ARG(2), ARG(5));
					LOAD_SYMBOL(SYMBOL(Slisp, 250), ARG(6));	/* PATTERN */
					rt_struct_typep(ARG(5));
				}
				if(CL_TRUEP(ARG(5)))
				{
					THEN1:;
					COPY(ARG(2), ARG(4));
					unparse_unix_piece(ARG(4));
					COPY(ARG(1), ARG(5));
					add_q(ARG(4));
					LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[8], ARG(4));	/* / */
					COPY(ARG(1), ARG(5));
					add_q(ARG(4));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&Kunparse_unix_directory_list[10], ARG(4));	/* Invalid directory component: ~S */
					COPY(ARG(2), ARG(5));
					Ferror(ARG(4), 2);
				}
			}
		}
		COPY(ARG(3), ARG(4));
		COPY(GET_CDR(ARG(4)), ARG(3));
		goto M1_1;
		RETURN1:;
	}
	LOAD_GLOBFUN(&CFconcatenate, ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 40), ARG(3));	/* SIMPLE-STRING */
	COPY(GET_CAR(ARG(1)), ARG(4));
	Fapply(ARG(2), 3);
	COPY(ARG(2), ARG(0));
}
