/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Farray_has_fill_pointer_p(CL_FORM *base)
{
	LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(0), ARG(2));
		LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(3));	/* COMPLEX-BASE-ARRAY */
		rt_struct_typep(ARG(2));
	}
	if(CL_TRUEP(ARG(2)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 152), ARG(1));	/* NO_ARRAY */
		COPY(ARG(0), ARG(2));
		Ferror(ARG(1), 2);
	}
	COPY(ARG(0), ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(2));	/* COMPLEX-VECTOR */
	rt_struct_typep(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(0), ARG(1));
		complex_vector_fillptr(ARG(1));
		Fminusp(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_NIL(ARG(0));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
