/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cundef_stream_op, undef_stream_op, -1);

void undef_stream_op(CL_FORM *base, int nargs)
{
	LOAD_SMSTR((CL_FORM *)&KClisp[2], ARG(0));	/* undefined Stream Operation */
	Ferror(ARG(0), 1);
}
