/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void unix_file_kind1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(0), ARG(2));
		unix_link_mode(ARG(2));
	}
	else
	{
		COPY(ARG(0), ARG(2));
		unix_file_mode(ARG(2));
	}
	if(CL_TRUEP(ARG(2)))
	{
		COPY(ARG(2), ARG(3));
		LOAD_FIXNUM(ARG(4), 61440, ARG(4));
		Flogand(ARG(3), 2);
		if(CL_FIXNUMP(ARG(3)) && GET_FIXNUM(ARG(3)) == 16384)
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 253), ARG(0));	/* DIRECTORY */
		}
		else
		{
			if(CL_FIXNUMP(ARG(3)) && GET_FIXNUM(ARG(3)) == 32768)
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 299), ARG(0));	/* FILE */
			}
			else
			{
				if(CL_FIXNUMP(ARG(3)) && GET_FIXNUM(ARG(3)) == 40960)
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 300), ARG(0));	/* LINK */
				}
				else
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 301), ARG(0));	/* SPECIAL */
				}
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
