/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fset_syntax_from_char(CL_FORM *base, int nargs)
{
	switch(nargs)
	{
		case 2:
		COPY(SYMVAL(Slisp, 454), ARG(2));	/* *READTABLE* */
		case 3:
		COPY(SYMVAL(Slisp, 453), ARG(3));	/* *STANDARD-READTABLE* */
		case 4:
		break;
		default:
		Labort(TOO_MANY_ARGS);
	}
	set_syntax_from_char1(ARG(0));
}
