/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Foutput_stream_p(CL_FORM *base)
{
	M1_1:;
	COPY(ARG(0), ARG(1));
	stream_type(ARG(1));
	if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 93))	/* SYNONYM */
	{
		COPY(ARG(0), ARG(1));
		stream_extra(ARG(1));
		if(CL_SYMBOLP(ARG(1)))
		{
			COPY(SYM_VALUE(ARG(1)), ARG(0));
		}
		else
		{
			if(CL_TRUEP(ARG(1)))
			{
				COPY(SYMVAL(Slisp, 676), ARG(0));	/* SYM_EXPECTED */
				Ferror(ARG(0), 2);
			}
			else
			{
				LOAD_NIL(ARG(0));
			}
		}
		goto M1_1;
	}
	else
	{
		COPY(ARG(0), ARG(1));
		stream_type(ARG(1));
		LOAD_CONS((CL_FORM *)&KClisp[196], ARG(2));
		COPY(ARG(1), ARG(0));
		COPY(ARG(2), ARG(1));
		LOAD_NIL(ARG(2));
		LOAD_NIL(ARG(3));
		LOAD_NIL(ARG(4));
		member1(ARG(0));
	}
	goto RETURN1;
	RETURN1:;
}
