/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Farray_dimensions(CL_FORM *base)
{
	if(CL_SMVECP(ARG(0)))
	{
		LOAD_FIXNUM(ARG(1), AR_SIZE(GET_FORM(ARG(0))), ARG(0));
		Flist(ARG(0), 1);
	}
	else
	{
		COPY(ARG(0), ARG(1));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(2));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			complex_vector_length(ARG(0));
			Flist(ARG(0), 1);
		}
		else
		{
			COPY(ARG(0), ARG(1));
			LOAD_SYMBOL(SYMBOL(Slisp, 147), ARG(2));	/* COMPLEX-ARRAY */
			rt_struct_typep(ARG(1));
			if(CL_TRUEP(ARG(1)))
			{
				complex_array_dims(ARG(0));
			}
			else
			{
				COPY(SYMVAL(Slisp, 152), ARG(1));	/* NO_ARRAY */
				COPY(ARG(0), ARG(2));
				Ferror(ARG(1), 2);
			}
		}
	}
}
