/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z61_lambda(CL_FORM *base);
static void Z62_lambda(CL_FORM *base);
static void Z63_lambda(CL_FORM *base);
static void Z64_lambda(CL_FORM *base);
static void Z65_lambda(CL_FORM *base);

void make_string_output_stream1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(0), ARG(1));
	LOAD_FIXNUM(ARG(1), 0, ARG(1));
	GEN_HEAPVAR(ARG(1), ARG(2));
	LOAD_SYMBOL(SYMBOL(Slisp, 102), ARG(2));	/* STRING-OUTPUT */
	{
		GEN_CLOSURE(array, ARG(3), 5, Z65_lambda, 1);
		COPY(ARG(0), &array[3]);
		COPY(ARG(1), &array[4]);
		LOAD_CLOSURE(array, ARG(3));
	}
	COPY(ARG(3), ARG(3));
	{
		GEN_CLOSURE(array, ARG(4), 4, Z64_lambda, 0);
		COPY(ARG(1), &array[3]);
		LOAD_CLOSURE(array, ARG(4));
	}
	COPY(ARG(4), ARG(4));
	{
		GEN_CLOSURE(array, ARG(5), 4, Z63_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(5));
	}
	COPY(ARG(5), ARG(5));
	{
		GEN_CLOSURE(array, ARG(6), 4, Z62_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(6));
	}
	COPY(ARG(6), ARG(6));
	{
		GEN_CLOSURE(array, ARG(7), 4, Z61_lambda, 0);
		COPY(ARG(0), &array[3]);
		LOAD_CLOSURE(array, ARG(7));
	}
	COPY(ARG(7), ARG(7));
	LOAD_GLOBFUN(&Cclose1, ARG(8));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(9));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(10));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(11));
	LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(12));	/* STREAM */
	COPY(ARG(2), ARG(13));
	COPY(ARG(7), ARG(14));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(15));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(16));
	COPY(ARG(3), ARG(17));
	COPY(ARG(4), ARG(18));
	COPY(ARG(5), ARG(19));
	LOAD_GLOBFUN(&Cundef_stream_op, ARG(20));
	COPY(ARG(6), ARG(21));
	LOAD_GLOBFUN(&Cclose1, ARG(22));
	rt_make_struct(ARG(12), 11);
	COPY(ARG(12), ARG(0));
}

static void Z61_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(2));	/* CHARACTER */
	LOAD_NIL(ARG(3));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	LOAD_FIXNUM(ARG(8), 0, ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(10));	/* T */
	LOAD_NIL(ARG(11));
	make_array1(ARG(1));
	LOAD_FIXNUM(ARG(2), 0, ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	Fset_fill_pointer(ARG(2));
	COPY(ARG(1), ARG(0));
}

static void Z62_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z63_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(1));
	Flength(ARG(1));
	COPY(ARG(1), ARG(0));
}

static void Z64_lambda(CL_FORM *base)
{
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(0));
}

static void Z65_lambda(CL_FORM *base)
{
	if(CL_CHARP(ARG(1)) && GET_CHAR(ARG(1)) == '\n')
	{
		LOAD_FIXNUM(ARG(2), 0, INDIRECT(GET_FORM(ARG(0)) + 4));
	}
	else
	{
		COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(2));
		F1plus(ARG(2));
		COPY(ARG(2), INDIRECT(GET_FORM(ARG(0)) + 4));
	}
	COPY(ARG(1), ARG(2));
	COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(3));
	LOAD_NIL(ARG(4));
	vector_push_extend1(ARG(2));
	COPY(ARG(2), ARG(0));
}
