/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Fdelete_duplicates(CL_FORM *base, int nargs)
{
	CL_FORM *rest_0;
	CL_FORM *local;
	rest_0 = ARG(1);
	local = ARG(nargs);
	LOAD_GLOBFUN(&CFremove_duplicates, LOCAL(0));
	COPY(ARG(0), LOCAL(1));
	REST_APPLY(LOCAL(0), 2, rest_0);
	COPY(LOCAL(0), ARG(0));
}
