/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void bq_attach_append(CL_FORM *base)
{
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_NIL(ARG(3));
	}
	else
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(3));	/* T */
	}
	if(CL_TRUEP(ARG(3)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(2), ARG(4));
		COPY(SYMVAL(Slisp, 445), ARG(5));	/* *BQ-QUOTE-NIL* */
		Fequal(ARG(4));
	}
	if(CL_TRUEP(ARG(4)))
	{
		THEN1:;
		COPY(ARG(1), ARG(3));
		bq_splicing_frob(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			Flist(ARG(0), 2);
		}
		else
		{
			COPY(ARG(1), ARG(0));
		}
	}
	else
	{
		COPY(ARG(1), ARG(3));
		null_or_quoted(ARG(3));
		if(CL_TRUEP(ARG(3)))
		{
			COPY(ARG(2), ARG(3));
			null_or_quoted(ARG(3));
		}
		else
		{
			goto ELSE2;
		}
		if(CL_TRUEP(ARG(3)))
		{
			COPY(SYMVAL(Slisp, 444), ARG(3));	/* *BQ-QUOTE* */
			if(CL_CONSP(ARG(1)))
			{
				COPY(GET_CDR(ARG(1)), ARG(4));
			}
			else
			{
				if(CL_TRUEP(ARG(1)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(4));	/* ~a is not a list */
					COPY(ARG(1), ARG(5));
					Ferror(ARG(4), 2);
				}
				else
				{
					COPY(ARG(1), ARG(4));
				}
			}
			if(CL_CONSP(ARG(4)))
			{
				COPY(GET_CAR(ARG(4)), ARG(4));
			}
			else
			{
				if(CL_TRUEP(ARG(4)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(5));	/* ~a is not a list */
					COPY(ARG(4), ARG(6));
					Ferror(ARG(5), 2);
				}
				else
				{
				}
			}
			if(CL_CONSP(ARG(2)))
			{
				COPY(GET_CDR(ARG(2)), ARG(5));
			}
			else
			{
				if(CL_TRUEP(ARG(2)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
					COPY(ARG(2), ARG(6));
					Ferror(ARG(5), 2);
				}
				else
				{
					COPY(ARG(2), ARG(5));
				}
			}
			if(CL_CONSP(ARG(5)))
			{
				COPY(GET_CAR(ARG(5)), ARG(5));
			}
			else
			{
				if(CL_TRUEP(ARG(5)))
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(6));	/* ~a is not a list */
					COPY(ARG(5), ARG(7));
					Ferror(ARG(6), 2);
				}
				else
				{
				}
			}
			Fappend(ARG(4), 2);
			Flist(ARG(3), 2);
			COPY(ARG(3), ARG(0));
		}
		else
		{
			ELSE2:;
			if(CL_CONSP(ARG(2)))
			{
				COPY(GET_CAR(ARG(2)), ARG(3));
			}
			else
			{
				goto ELSE3;
			}
			if(EQ(ARG(3), ARG(0)))
			{
				if(CL_CONSP(ARG(2)))
				{
					COPY(GET_CAR(ARG(2)), ARG(3));
				}
				else
				{
					if(CL_TRUEP(ARG(2)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(3));	/* ~a is not a list */
						COPY(ARG(2), ARG(4));
						Ferror(ARG(3), 2);
					}
					else
					{
						COPY(ARG(2), ARG(3));
					}
				}
				COPY(ARG(1), ARG(4));
				if(CL_CONSP(ARG(2)))
				{
					COPY(GET_CDR(ARG(2)), ARG(5));
				}
				else
				{
					if(CL_TRUEP(ARG(2)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(5));	/* ~a is not a list */
						COPY(ARG(2), ARG(6));
						Ferror(ARG(5), 2);
					}
					else
					{
						COPY(ARG(2), ARG(5));
					}
				}
				FlistX(ARG(3), 3);
				COPY(ARG(3), ARG(0));
			}
			else
			{
				ELSE3:;
				Flist(ARG(0), 3);
			}
		}
	}
}
