/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void rt_struct_printer(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 351), ARG(1));	/* STRUCT-PRINTER */
	Fget(ARG(0), 2);
}
