/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kto_element_type[] =
{
	MAKE_STRING(20, "unknown type code ~A"),	/* 0 */
};

void to_element_type(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 0)
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
	}
	else
	{
		if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 1)
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 23), ARG(0));	/* FIXNUM */
		}
		else
		{
			if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 2)
			{
				LOAD_SYMBOL(SYMBOL(Slisp, 24), ARG(0));	/* FLOAT */
			}
			else
			{
				if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 3)
				{
					LOAD_SYMBOL(SYMBOL(Slisp, 18), ARG(0));	/* CHARACTER */
				}
				else
				{
					if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) == 4)
					{
						LOAD_SYMBOL(SYMBOL(Slisp, 16), ARG(0));	/* BIT */
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kto_element_type[0], ARG(1));	/* unknown type code ~A */
						COPY(ARG(0), ARG(2));
						Ferror(ARG(1), 2);
					}
				}
			}
		}
	}
}
