/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void Falphanumericp(CL_FORM *base)
{
	COPY(ARG(0), ARG(1));
	Falpha_char_p(ARG(1));
	if(CL_TRUEP(ARG(1)))
	{
		COPY(ARG(1), ARG(0));
	}
	else
	{
		Fdigit_char_p(ARG(0), 1);
	}
}
