/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT KPenumerate_files[] =
{
	MAKE_STRING(1, "."),	/* 0 */
	MAKE_STRING(1, "."),	/* 2 */
};

void Penumerate_files(CL_FORM *base)
{
	COPY(ARG(1), ARG(4));
	LOAD_SYMBOL(SYMBOL(Slisp, 276), ARG(5));	/* LOCAL */
	pathname_name1(ARG(4));
	mv_count = 1;
	COPY(ARG(1), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 276), ARG(6));	/* LOCAL */
	pathname_type1(ARG(5));
	mv_count = 1;
	COPY(ARG(1), ARG(6));
	Fpathname_version(ARG(6));
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 44), ARG(7));	/* STRING */
		COPY(ARG(0), ARG(8));
		COPY(ARG(4), ARG(9));
		Fconcatenate(ARG(7), 3);
		if(CL_TRUEP(ARG(5)))
		{
			LOAD_NIL(ARG(8));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
		}
		if(CL_TRUEP(ARG(8)))
		{
			goto THEN1;
		}
		else
		{
		}	/* UNSPECIFIC */
		if(CL_SYMBOLP(ARG(5)) && GET_SYMBOL(ARG(5)) == SYMBOL(Slisp, 266))
		{
			THEN1:;
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 44), ARG(8));	/* STRING */
			COPY(ARG(7), ARG(9));
			LOAD_SMSTR((CL_FORM *)&KPenumerate_files[0], ARG(10));	/* . */
			COPY(ARG(5), ARG(11));
			Fconcatenate(ARG(8), 4);
			COPY(ARG(8), ARG(7));
		}
		if(CL_TRUEP(ARG(6)))
		{
			LOAD_NIL(ARG(8));
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(8));	/* T */
		}
		if(CL_TRUEP(ARG(8)))
		{
			goto THEN2;
		}
		else
		{
		}	/* NEWEST */
		if(CL_SYMBOLP(ARG(6)) && GET_SYMBOL(ARG(6)) == SYMBOL(Slisp, 269))
		{
			THEN2:;
		}
		else
		{
			LOAD_SYMBOL(SYMBOL(Slisp, 44), ARG(8));	/* STRING */
			COPY(ARG(7), ARG(9));
			LOAD_SMSTR((CL_FORM *)&KPenumerate_files[2], ARG(10));	/* . */
			COPY(ARG(6), ARG(11));
			quick_integer_to_string(ARG(11));
			Fconcatenate(ARG(8), 4);
			COPY(ARG(8), ARG(7));
		}
		LOAD_NIL(ARG(8));
		if(CL_TRUEP(ARG(8)))
		{
			goto THEN3;
		}
		else
		{
			COPY(ARG(7), ARG(9));
			LOAD_NIL(ARG(10));
			unix_file_kind1(ARG(9));
		}
		if(CL_TRUEP(ARG(9)))
		{
			THEN3:;
			COPY(ARG(3), ARG(0));
			COPY(ARG(7), ARG(1));
			Ffuncall(ARG(0), 2);
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
	else
	{
		LOAD_NIL(ARG(7));
		if(CL_TRUEP(ARG(7)))
		{
			goto THEN4;
		}
		else
		{
			COPY(ARG(0), ARG(8));
			LOAD_NIL(ARG(9));
			unix_file_kind1(ARG(8));
		}
		if(CL_TRUEP(ARG(8)))
		{
			THEN4:;
			COPY(ARG(3), ARG(7));
			COPY(ARG(0), ARG(8));
			Ffuncall(ARG(7), 2);
			COPY(ARG(7), ARG(0));
		}
		else
		{
			LOAD_NIL(ARG(0));
		}
	}
}
