/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void list_nreverse(CL_FORM *base)
{
	LOAD_NIL(ARG(1));
	COPY(ARG(0), ARG(2));
	M1_1:;
	if(CL_CONSP(ARG(2)))
	{
		COPY(GET_CDR(ARG(2)), ARG(3));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(3));	/* ~a is not a list */
		COPY(ARG(2), ARG(4));
		Ferror(ARG(3), 2);
	}
	if(CL_CONSP(ARG(2)))
	{
		COPY(ARG(1), GET_CDR(ARG(2)));
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&KClisp[254], ARG(4));	/* ~a is not a cons */
		COPY(ARG(2), ARG(5));
		Ferror(ARG(4), 2);
	}
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(2), ARG(1));
		COPY(ARG(3), ARG(2));
		goto M1_1;
	}
	else
	{
		COPY(ARG(2), ARG(0));
	}
	goto RETURN1;
	RETURN1:;
}
