/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kmake_list1[] =
{
	MAKE_STRING(32, "make-list: ~A is an illegal size"),	/* 0 */
};

static void Z22_f(CL_FORM *base);

void make_list1(CL_FORM *base)
{
	LOAD_FIXNUM(ARG(3), 0, ARG(3));
	if(CL_FIXNUMP(ARG(0)) && GET_FIXNUM(ARG(0)) >= GET_FIXNUM(ARG(3)))
	{
	}
	else
	{
		LOAD_SMSTR((CL_FORM *)&Kmake_list1[0], ARG(2));	/* make-list: ~A is an illegal size */
		COPY(ARG(0), ARG(3));
		Ferror(ARG(2), 2);
	}
	COPY(ARG(0), ARG(2));
	Fzerop(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(3));
		F1minus(ARG(3));
		COPY(ARG(1), ARG(4));
		Z22_f(ARG(3));
		ALLOC_CONS(ARG(4), ARG(1), ARG(3), ARG(0));
	}
}

static void Z22_f(CL_FORM *base)
{
	COPY(ARG(0), ARG(2));
	Fzerop(ARG(2));
	if(CL_TRUEP(ARG(2)))
	{
		LOAD_NIL(ARG(0));
	}
	else
	{
		COPY(ARG(0), ARG(3));
		F1minus(ARG(3));
		COPY(ARG(1), ARG(4));
		Z22_f(ARG(3));
		ALLOC_CONS(ARG(4), ARG(1), ARG(3), ARG(0));
	}
}
