/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void member_if1(CL_FORM *base)
{
	COPY(ARG(1), ARG(3));
	M1_1:;
	if(CL_TRUEP(ARG(3)))
	{
		COPY(ARG(0), ARG(4));
		if(CL_TRUEP(ARG(2)))
		{
			COPY(ARG(2), ARG(5));
			if(CL_CONSP(ARG(3)))
			{
				COPY(GET_CAR(ARG(3)), ARG(6));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(6));	/* ~a is not a list */
				COPY(ARG(3), ARG(7));
				Ferror(ARG(6), 2);
			}
			Ffuncall(ARG(5), 2);
			mv_count = 1;
		}
		else
		{
			if(CL_CONSP(ARG(3)))
			{
				COPY(GET_CAR(ARG(3)), ARG(5));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(5));	/* ~a is not a list */
				COPY(ARG(3), ARG(6));
				Ferror(ARG(5), 2);
			}
		}
		Ffuncall(ARG(4), 2);
		mv_count = 1;
		if(CL_TRUEP(ARG(4)))
		{
			COPY(ARG(3), ARG(0));
		}
		else
		{
			COPY(ARG(3), ARG(4));
			COPY(ARG(4), ARG(5));
			if(CL_CONSP(ARG(5)))
			{
				COPY(GET_CDR(ARG(5)), ARG(3));
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(3));	/* ~a is not a list */
				COPY(ARG(5), ARG(4));
				Ferror(ARG(3), 2);
			}
			goto M1_1;
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
	goto RETURN1;
	RETURN1:;
}
