/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

GEN_GLOBAL_FUNARG(Cnil_fun, nil_fun, 0);

void nil_fun(CL_FORM *base)
{
	LOAD_NIL(ARG(0));
}
