/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z16_nsubst_if_internal(CL_FORM *base, CL_FORM *display[]);

void nsubst_if1(CL_FORM *base)
{
	CL_FORM *display[1];
	COPY(ARG(2), ARG(4));
	display[0] = ARG(0);
	Z16_nsubst_if_internal(ARG(4), display);
	COPY(ARG(4), ARG(0));
}

static void Z16_nsubst_if_internal(CL_FORM *base, CL_FORM *display[])
{
	COPY(&display[0][1], ARG(1));
	if(CL_TRUEP(&display[0][3]))
	{
		COPY(&display[0][3], ARG(2));
		COPY(ARG(0), ARG(3));
		Ffuncall(ARG(2), 2);
		mv_count = 1;
	}
	else
	{
		COPY(ARG(0), ARG(2));
	}
	Ffuncall(ARG(1), 2);
	mv_count = 1;
	if(CL_TRUEP(ARG(1)))
	{
		COPY(&display[0][0], ARG(0));
	}
	else
	{
		if(CL_ATOMP(ARG(0)))
		{
		}
		else
		{
			COPY(GET_CAR(ARG(0)), ARG(1));
			Z16_nsubst_if_internal(ARG(1), display);
			COPY(GET_CDR(ARG(0)), ARG(2));
			Z16_nsubst_if_internal(ARG(2), display);
			COPY(ARG(1), GET_CAR(ARG(0)));
			COPY(ARG(2), GET_CDR(ARG(0)));
		}
	}
}
