/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kopen1[] =
{
	MAKE_STRING(1, "r"),	/* 0 */
	MAKE_STRING(17, "~s does not exist"),	/* 2 */
	MAKE_STRING(2, "w+"),	/* 4 */
	MAKE_STRING(17, "can not create ~S"),	/* 6 */
	MAKE_STRING(17, "illegal option ~s"),	/* 8 */
	MAKE_STRING(22, "file already exists ~s"),	/* 10 */
	MAKE_STRING(2, "r+"),	/* 12 */
	MAKE_STRING(2, "a+"),	/* 14 */
	MAKE_STRING(2, "w+"),	/* 16 */
	MAKE_STRING(23, "unimplemented option ~S"),	/* 18 */
	MAKE_STRING(2, "r+"),	/* 20 */
	MAKE_STRING(15, "can not open ~S"),	/* 22 */
};

static void Z55_get_io_file(CL_FORM *base, CL_FORM *display[]);

void open1(CL_FORM *base)
{
	CL_FORM *display[1];
	CONTENV new_cont;
	CL_FORM *caller_base;
	new_cont.bind_top = bind_top;
	new_cont.last = last_cont;
	LOAD_UNIQUE_TAG(ARG(4));
	caller_base = (CL_FORM *)SETJMP(new_cont.jmp_buf);
	if(caller_base == NULL)
	{
		last_cont = &new_cont;
		LOAD_NIL(ARG(5));
		LOAD_NIL(ARG(6));
		COPY(ARG(0), ARG(7));
		Fnamestring(ARG(7));
		mv_count = 1;
		COPY(ARG(7), ARG(0));
		LOAD_SMSTR((CL_FORM *)&Kopen1[0], ARG(8));	/* r */
		c_fopen(ARG(7));
		COPY(ARG(7), ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
		}
		else
		{
			if(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 220))	/* ERROR */
			{
				LOAD_SMSTR((CL_FORM *)&Kopen1[2], ARG(7));	/* ~s does not exist */
				COPY(ARG(0), ARG(8));
				Ferror(ARG(7), 2);
			}
			else
			{
				if(CL_TRUEP(ARG(3)))
				{
					if(CL_SYMBOLP(ARG(3)) && GET_SYMBOL(ARG(3)) == SYMBOL(Slisp, 226))	/* CREATE */
					{
						COPY(ARG(0), ARG(6));
						LOAD_SMSTR((CL_FORM *)&Kopen1[4], ARG(7));	/* w+ */
						c_fopen(ARG(6));
						if(CL_TRUEP(ARG(6)))
						{
						}
						else
						{
							LOAD_SMSTR((CL_FORM *)&Kopen1[6], ARG(7));	/* can not create ~S */
							COPY(ARG(0), ARG(8));
							Ferror(ARG(7), 2);
						}
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Kopen1[8], ARG(7));	/* illegal option ~s */
						COPY(ARG(3), ARG(8));
						Ferror(ARG(7), 2);
					}
				}
				else
				{
					LOAD_NIL(ARG(0));
					goto RETURN1;
				}
			}
		}
		LOAD_BOOL(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 218), ARG(7));	/* INPUT */
		if(CL_TRUEP(ARG(7)))
		{
			goto THEN1;
		}
		else
		{
		}	/* PROBE */
		if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 227))
		{
			THEN1:;
			if(CL_TRUEP(ARG(6)))
			{
				LOAD_NIL(ARG(7));
				COPY(ARG(6), ARG(8));
				COPY(ARG(8), ARG(9));
				COPY(ARG(9), ARG(10));
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(11));	/* STREAM */
				rt_struct_typep(ARG(10));
				if(CL_TRUEP(ARG(10)))
				{
					COPY(OFFSET(AR_BASE(GET_FORM(ARG(9))), 9 + 1), ARG(8));
				}
				else
				{
					COPY(SYMVAL(Slisp, 352), ARG(8));	/* NO_STRUCT */
					LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(10));	/* STREAM */
					Ferror(ARG(8), 3);
				}
				COPY(ARG(6), ARG(9));
				Ffuncall(ARG(8), 2);
				mv_count = 1;
				COPY(ARG(0), ARG(7));
				LOAD_SMSTR((CL_FORM *)&Kopen1[20], ARG(8));	/* r+ */
				c_fopen(ARG(7));
				COPY(ARG(7), ARG(5));
			}
			if(CL_TRUEP(ARG(5)))
			{
			}
			else
			{
				LOAD_SMSTR((CL_FORM *)&Kopen1[22], ARG(7));	/* can not open ~S */
				COPY(ARG(0), ARG(8));
				Ferror(ARG(7), 2);
			}
			COPY(ARG(5), ARG(7));
			COPY(ARG(0), ARG(8));
			make_file_input_stream(ARG(7));
			if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 227))	/* PROBE */
			{
				LOAD_NIL(ARG(8));
				COPY(ARG(7), ARG(9));
				COPY(ARG(9), ARG(10));
				COPY(ARG(10), ARG(11));
				LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(12));	/* STREAM */
				rt_struct_typep(ARG(11));
				if(CL_TRUEP(ARG(11)))
				{
					COPY(OFFSET(AR_BASE(GET_FORM(ARG(10))), 9 + 1), ARG(9));
				}
				else
				{
					COPY(SYMVAL(Slisp, 352), ARG(9));	/* NO_STRUCT */
					LOAD_SYMBOL(SYMBOL(Slisp, 64), ARG(11));	/* STREAM */
					Ferror(ARG(9), 3);
				}
				COPY(ARG(7), ARG(10));
				Ffuncall(ARG(9), 2);
				mv_count = 1;
			}
			COPY(ARG(7), ARG(0));
		}
		else
		{
			if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 222))	/* OUTPUT */
			{
				display[0] = ARG(0);
				Z55_get_io_file(ARG(7), display);
				COPY(ARG(0), ARG(8));
				make_file_output_stream(ARG(7));
				COPY(ARG(7), ARG(0));
			}
			else
			{
				if(CL_SYMBOLP(ARG(1)) && GET_SYMBOL(ARG(1)) == SYMBOL(Slisp, 223))	/* IO */
				{
					display[0] = ARG(0);
					Z55_get_io_file(ARG(7), display);
					COPY(ARG(0), ARG(8));
					make_file_io_stream(ARG(7));
					COPY(ARG(7), ARG(0));
				}
				else
				{
					LOAD_NIL(ARG(0));
				}
			}
		}
		RETURN1:;
		last_cont = new_cont.last;
	}
	else
	{
		last_cont = new_cont.last;
		if(EQ(STACK(caller_base, 0), ARG(4)))
		{
			COPY(STACK(caller_base, 1), ARG(0));
		}
		else
		{
			call_cont(caller_base);
		}
	}
}

static void Z55_get_io_file(CL_FORM *base, CL_FORM *display[])
{
	if(CL_TRUEP(&display[0][5]))
	{
		COPY(&display[0][5], ARG(0));
		c_fclose(ARG(0));
		if(CL_SYMBOLP(&display[0][2]) && GET_SYMBOL(&display[0][2]) == SYMBOL(Slisp, 220))	/* ERROR */
		{
			LOAD_SMSTR((CL_FORM *)&Kopen1[10], ARG(0));	/* file already exists ~s */
			COPY(&display[0][0], ARG(1));
			Ferror(ARG(0), 2);
		}
		else
		{
			if(CL_SYMBOLP(&display[0][2]) && GET_SYMBOL(&display[0][2]) == SYMBOL(Slisp, 224))	/* OVERWRITE */
			{
				COPY(&display[0][0], ARG(0));
				LOAD_SMSTR((CL_FORM *)&Kopen1[12], ARG(1));	/* r+ */
				c_fopen(ARG(0));
			}
			else
			{
				if(CL_SYMBOLP(&display[0][2]) && GET_SYMBOL(&display[0][2]) == SYMBOL(Slisp, 225))	/* APPEND */
				{
					COPY(&display[0][0], ARG(0));
					LOAD_SMSTR((CL_FORM *)&Kopen1[14], ARG(1));	/* a+ */
					c_fopen(ARG(0));
				}
				else
				{
					LOAD_BOOL(CL_SYMBOLP(&display[0][2]) && GET_SYMBOL(&display[0][2]) == SYMBOL(Slisp, 229), ARG(0));	/* SUPERSEDE */
					if(CL_TRUEP(ARG(0)))
					{
						goto THEN1;
					}
					else
					{
					}	/* NEW-VERSION */
					if(CL_SYMBOLP(&display[0][2]) && GET_SYMBOL(&display[0][2]) == SYMBOL(Slisp, 230))
					{
						THEN1:;
						COPY(&display[0][0], ARG(0));
						LOAD_SMSTR((CL_FORM *)&Kopen1[16], ARG(1));	/* w+ */
						c_fopen(ARG(0));
					}
					else
					{
						if(CL_TRUEP(&display[0][2]))
						{
							LOAD_SMSTR((CL_FORM *)&Kopen1[18], ARG(0));	/* unimplemented option ~S */
							COPY(&display[0][2], ARG(1));
							Ferror(ARG(0), 2);
						}
						else
						{
							COPY(&display[0][4], ARG(0));
							LOAD_NIL(ARG(1));
							call_cont(ARG(0));
						}
					}
				}
			}
		}
	}
	else
	{
		COPY(&display[0][6], ARG(0));
	}
}
