/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kread_line1[] =
{
	MAKE_STRING(22, "unexpected end of file"),	/* 0 */
};

void read_line1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_SYMBOLP(ARG(0)) && GET_SYMBOL(ARG(0)) == SYMBOL(Slisp, 48))	/* T */
		{
			COPY(SYMVAL(Slisp, 59), ARG(0));	/* *TERMINAL-IO* */
		}
	}
	else
	{
		COPY(SYMVAL(Slisp, 60), ARG(0));	/* *STANDARD-INPUT* */
	}
	COPY(ARG(0), ARG(4));
	LOAD_NIL(ARG(5));
	LOAD_NIL(ARG(6));
	LOAD_NIL(ARG(7));
	read_char1(ARG(4));
	if(CL_TRUEP(ARG(4)))
	{
		LOAD_FIXNUM(ARG(5), 0, ARG(5));
		COPY(SYMVAL(Slisp, 448), ARG(6));	/* *TOKEN* */
		Fset_fill_pointer(ARG(5));
		M1_1:;
		if(CL_CHARP(ARG(4)) && GET_CHAR(ARG(4)) == '\n')
		{
			COPY(SYMVAL(Slisp, 448), ARG(0));	/* *TOKEN* */
			LOAD_FIXNUM(ARG(1), 0, ARG(1));
			LOAD_NIL(ARG(2));
			subseq1(ARG(0));
			LOAD_NIL(ARG(1));
			COPY(ARG(1), &mv_buf[0]);
			mv_count = 2;
			goto RETURN1;
		}
		COPY(ARG(4), ARG(5));
		COPY(SYMVAL(Slisp, 448), ARG(6));	/* *TOKEN* */
		LOAD_NIL(ARG(7));
		vector_push_extend1(ARG(5));
		COPY(ARG(0), ARG(5));
		COPY(ARG(5), ARG(4));
		LOAD_NIL(ARG(5));
		LOAD_NIL(ARG(6));
		LOAD_NIL(ARG(7));
		read_char1(ARG(4));
		if(CL_TRUEP(ARG(4)))
		{
		}
		else
		{
			COPY(SYMVAL(Slisp, 448), ARG(0));	/* *TOKEN* */
			LOAD_FIXNUM(ARG(1), 0, ARG(1));
			LOAD_NIL(ARG(2));
			subseq1(ARG(0));
			LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
			COPY(ARG(1), &mv_buf[0]);
			mv_count = 2;
			goto RETURN1;
		}
		goto M1_1;
		RETURN1:;
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			LOAD_SMSTR((CL_FORM *)&Kread_line1[0], ARG(5));	/* unexpected end of file */
			Ferror(ARG(5), 1);
		}
		COPY(ARG(2), ARG(0));
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(1));	/* T */
		COPY(ARG(1), &mv_buf[0]);
		mv_count = 2;
	}
}
