/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

void rt_set_vref(CL_FORM *base)
{
	LOAD_BOOL(CL_SMVECP(ARG(1)), ARG(3));
	if(CL_TRUEP(ARG(3)))
	{
		goto THEN1;
	}
	else
	{
		COPY(ARG(1), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(5));	/* COMPLEX-VECTOR */
		rt_struct_typep(ARG(4));
	}
	if(CL_TRUEP(ARG(4)))
	{
		THEN1:;
	}
	else
	{
		COPY(SYMVAL(Slisp, 58), ARG(3));	/* WRONG_TYPE */
		COPY(ARG(1), ARG(4));
		LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(5));	/* VECTOR */
		Ferror(ARG(3), 3);
	}
	Fset_row_major_aref(ARG(0));
}
