/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

static void Z162_lambda(CL_FORM *base);
GEN_STATIC_GLOBAL_FUNARG(CZ162_lambda, Z162_lambda, 0);

void rt_startup(CL_FORM *base)
{
	LOAD_SYMBOL(SYMBOL(Slisp, 508), ARG(0));	/* ERROR-CATCHER */
	LOAD_GLOBFUN(&CZ162_lambda, ARG(1));
	rt_catch(ARG(0));
}

static void Z162_lambda(CL_FORM *base)
{
	Imain(ARG(0));
	LOAD_FIXNUM(ARG(0), 0, ARG(0));
}
