/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Ksequence_type[] =
{
	MAKE_STRING(16, "Unexpected error"),	/* 0 */
};

void sequence_type(CL_FORM *base)
{
	if(CL_LISTP(ARG(0)))
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 28), ARG(0));	/* LIST */
	}
	else
	{
		LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(1));
		if(CL_TRUEP(ARG(1)))
		{
			goto THEN1;
		}
		else
		{
			COPY(ARG(0), ARG(2));
			LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(3));	/* COMPLEX-VECTOR */
			rt_struct_typep(ARG(2));
		}
		if(CL_TRUEP(ARG(2)))
		{
			THEN1:;
			LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(1));	/* VECTOR */
			COPY(ARG(0), ARG(2));
			array_element_type_internal(ARG(2));
			to_element_type(ARG(2));
			Flist(ARG(1), 2);
			COPY(ARG(1), ARG(0));
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&Ksequence_type[0], ARG(0));	/* Unexpected error */
			Ferror(ARG(0), 1);
		}
	}
}
