/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Ksubseq1[] =
{
	MAKE_STRING(23, "end of sequence reached"),	/* 0 */
};

void subseq1(CL_FORM *base)
{
	if(CL_TRUEP(ARG(0)))
	{
		if(CL_CONSP(ARG(0)))
		{
			COPY(ARG(0), ARG(3));
			COPY(ARG(2), ARG(4));
			LOAD_NIL(ARG(5));
			LOAD_NIL(ARG(6));
			ALLOC_CONS(ARG(7), ARG(5), ARG(6), ARG(5));
			COPY(ARG(1), ARG(6));
			COPY(ARG(3), ARG(7));
			Fnthcdr(ARG(6));
			COPY(ARG(6), ARG(3));
			if(CL_TRUEP(ARG(4)))
			{
				COPY(ARG(4), ARG(6));
				COPY(ARG(1), ARG(7));
				Fminus(ARG(6), 2);
				COPY(ARG(6), ARG(4));
				LOAD_FIXNUM(ARG(6), 0, ARG(6));
				M1_1:;
				COPY(ARG(6), ARG(7));
				COPY(ARG(4), ARG(8));
				Fge(ARG(7), 2);
				if(CL_TRUEP(ARG(7)))
				{
					goto RETURN1;
				}
				if(CL_ATOMP(ARG(3)))
				{
					LOAD_SMSTR((CL_FORM *)&Ksubseq1[0], ARG(7));	/* end of sequence reached */
					Ferror(ARG(7), 1);
				}
				if(CL_CONSP(ARG(3)))
				{
					COPY(GET_CAR(ARG(3)), ARG(7));
				}
				else
				{
					if(CL_TRUEP(ARG(3)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(7));	/* ~a is not a list */
						COPY(ARG(3), ARG(8));
						Ferror(ARG(7), 2);
					}
					else
					{
						COPY(ARG(3), ARG(7));
					}
				}
				COPY(ARG(3), ARG(8));
				COPY(ARG(8), ARG(9));
				if(CL_CONSP(ARG(9)))
				{
					COPY(GET_CDR(ARG(9)), ARG(3));
				}
				else
				{
					if(CL_TRUEP(ARG(9)))
					{
						LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(10));	/* ~a is not a list */
						COPY(ARG(9), ARG(11));
						Ferror(ARG(10), 2);
					}
					else
					{
						COPY(ARG(9), ARG(3));
					}
				}
				COPY(ARG(5), ARG(8));
				add_q(ARG(7));
				F1plus(ARG(6));
				goto M1_1;
				RETURN1:;
			}
			else
			{
				M2_1:;
				if(CL_TRUEP(ARG(3)))
				{
				}
				else
				{
					goto RETURN2;
				}
				if(CL_CONSP(ARG(3)))
				{
					COPY(GET_CAR(ARG(3)), ARG(6));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[264], ARG(6));	/* ~a is not a list */
					COPY(ARG(3), ARG(7));
					Ferror(ARG(6), 2);
				}
				COPY(ARG(3), ARG(7));
				COPY(ARG(7), ARG(8));
				if(CL_CONSP(ARG(8)))
				{
					COPY(GET_CDR(ARG(8)), ARG(3));
				}
				else
				{
					LOAD_SMSTR((CL_FORM *)&KClisp[262], ARG(9));	/* ~a is not a list */
					COPY(ARG(8), ARG(10));
					Ferror(ARG(9), 2);
				}
				COPY(ARG(5), ARG(7));
				add_q(ARG(6));
				goto M2_1;
				RETURN2:;
			}
			COPY(GET_CAR(ARG(5)), ARG(0));
		}
		else
		{
			LOAD_BOOL(CL_SMVECP(ARG(0)), ARG(3));
			if(CL_TRUEP(ARG(3)))
			{
				goto THEN1;
			}
			else
			{
				COPY(ARG(0), ARG(4));
				LOAD_SYMBOL(SYMBOL(Slisp, 150), ARG(5));	/* COMPLEX-VECTOR */
				rt_struct_typep(ARG(4));
			}
			if(CL_TRUEP(ARG(4)))
			{
				THEN1:;
				COPY(ARG(0), ARG(3));
				COPY(ARG(1), ARG(4));
				COPY(ARG(2), ARG(5));
				COPY(ARG(4), ARG(6));
				COPY(ARG(5), ARG(7));
				COPY(ARG(3), ARG(8));
				Flength(ARG(8));
				check_seq_start_end(ARG(6));
				COPY(ARG(6), ARG(5));
				LOAD_SYMBOL(SYMBOL(Slisp, 47), ARG(6));	/* VECTOR */
				COPY(ARG(3), ARG(7));
				if(CL_SMVECP(ARG(7)))
				{
					rt_plain_vector_element_code(ARG(7));
				}
				else
				{
					COPY(ARG(7), ARG(8));
					LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(9));	/* COMPLEX-BASE-ARRAY */
					rt_struct_typep(ARG(8));
					if(CL_TRUEP(ARG(8)))
					{
						COPY(ARG(7), ARG(8));
						M3_1:;
						COPY(ARG(8), ARG(9));
						COPY(ARG(9), ARG(10));
						COPY(ARG(10), ARG(11));
						LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(12));	/* COMPLEX-BASE-ARRAY */
						rt_struct_typep(ARG(11));
						if(CL_TRUEP(ARG(11)))
						{
							COPY(OFFSET(AR_BASE(GET_FORM(ARG(10))), 0 + 1), ARG(8));
						}
						else
						{
							COPY(SYMVAL(Slisp, 352), ARG(8));	/* NO_STRUCT */
							COPY(ARG(10), ARG(9));
							LOAD_SYMBOL(SYMBOL(Slisp, 145), ARG(10));	/* COMPLEX-BASE-ARRAY */
							Ferror(ARG(8), 3);
						}
						if(CL_SMVECP(ARG(8)))
						{
						}
						else
						{
							goto M3_1;
						}
						goto RETURN3;
						RETURN3:;
						rt_plain_vector_element_code(ARG(8));
						COPY(ARG(8), ARG(7));
					}
					else
					{
						COPY(SYMVAL(Slisp, 152), ARG(8));	/* NO_ARRAY */
						COPY(ARG(7), ARG(9));
						Ferror(ARG(8), 2);
					}
				}
				to_element_type(ARG(7));
				Flist(ARG(6), 2);
				COPY(ARG(5), ARG(7));
				COPY(ARG(4), ARG(8));
				Fminus(ARG(7), 2);
				LOAD_NIL(ARG(8));
				LOAD_NIL(ARG(9));
				make_sequence1(ARG(6));
				COPY(ARG(4), ARG(7));
				LOAD_FIXNUM(ARG(8), 0, ARG(8));
				M4_1:;
				COPY(ARG(7), ARG(9));
				COPY(ARG(5), ARG(10));
				Fnumeql(ARG(9), 2);
				if(CL_TRUEP(ARG(9)))
				{
					COPY(ARG(6), ARG(0));
					goto RETURN4;
				}
				COPY(ARG(3), ARG(9));
				COPY(ARG(7), ARG(10));
				Felt(ARG(9));
				COPY(ARG(6), ARG(10));
				COPY(ARG(8), ARG(11));
				Fset_elt(ARG(9));
				COPY(ARG(7), ARG(9));
				F1plus(ARG(9));
				F1plus(ARG(8));
				COPY(ARG(9), ARG(7));
				goto M4_1;
				RETURN4:;
			}
			else
			{
				COPY(SYMVAL(Slisp, 58), ARG(3));	/* WRONG_TYPE */
				COPY(ARG(0), ARG(4));
				LOAD_SYMBOL(SYMBOL(Slisp, 36), ARG(5));	/* SEQUENCE */
				Ferror(ARG(3), 3);
			}
		}
	}
	else
	{
		LOAD_NIL(ARG(0));
	}
}
