/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Ktype_code_p[] =
{
	MAKE_STRING(19, "unknow type code ~A"),	/* 0 */
};

void type_code_p(CL_FORM *base)
{
	if(CL_FIXNUMP(ARG(1)) && GET_FIXNUM(ARG(1)) == 0)
	{
		LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
	}
	else
	{
		if(CL_FIXNUMP(ARG(1)) && GET_FIXNUM(ARG(1)) == 1)
		{
			LOAD_BOOL(CL_FIXNUMP(ARG(0)), ARG(0));
		}
		else
		{
			if(CL_FIXNUMP(ARG(1)) && GET_FIXNUM(ARG(1)) == 2)
			{
				LOAD_BOOL(CL_FLOATP(ARG(0)), ARG(0));
			}
			else
			{
				if(CL_FIXNUMP(ARG(1)) && GET_FIXNUM(ARG(1)) == 3)
				{
					LOAD_BOOL(CL_CHARP(ARG(0)), ARG(0));
				}
				else
				{
					if(CL_FIXNUMP(ARG(1)) && GET_FIXNUM(ARG(1)) == 4)
					{
						if(CL_FIXNUMP(ARG(0)))
						{
							LOAD_FIXNUM(ARG(2), 0, ARG(2));
							COPY(ARG(0), ARG(3));
							LOAD_FIXNUM(ARG(4), 1, ARG(4));
							Fle(ARG(2), 3);
							COPY(ARG(2), ARG(0));
						}
						else
						{
							LOAD_NIL(ARG(0));
						}
					}
					else
					{
						LOAD_SMSTR((CL_FORM *)&Ktype_code_p[0], ARG(0));	/* unknow type code ~A */
						Ferror(ARG(0), 2);
					}
				}
			}
		}
	}
}
