/* This file was generated by CLiCC 0.6.4 [obrep 1] */
#define __OBREP 1
#include <c_decl.h>
#include "sys.h"
#include "lisp.h"

CL_INIT Kuse_package1[] =
{
	MAKE_STRING(12, "can\'t use ~S"),	/* 0 */
	MAKE_STRING(32, "~S in ~S conflicts with ~S in ~S"),	/* 2 */
};

static void Z51_lambda(CL_FORM *base);

void use_package1(CL_FORM *base)
{
	GEN_HEAPVAR(ARG(1), ARG(2));
	COPY(INDIRECT(ARG(1)), ARG(2));
	coerce_to_package(ARG(2));
	COPY(ARG(2), INDIRECT(ARG(1)));
	if(CL_LISTP(ARG(0)))
	{
	}
	else
	{
		COPY(ARG(0), ARG(2));
		Flist(ARG(2), 1);
		COPY(ARG(2), ARG(0));
	}
	LOAD_NIL(ARG(2));
	GEN_HEAPVAR(ARG(2), ARG(3));
	COPY(ARG(0), ARG(3));
	M1_1:;
	if(CL_ATOMP(ARG(3)))
	{
		LOAD_NIL(INDIRECT(ARG(2)));
		goto RETURN1;
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CAR(ARG(4)), INDIRECT(ARG(2)));
	COPY(INDIRECT(ARG(2)), ARG(4));
	coerce_to_package(ARG(4));
	COPY(ARG(4), INDIRECT(ARG(2)));
	if(EQ(INDIRECT(ARG(2)), SYMVAL(Slisp, 390)))	/* *KEYWORD-PACKAGE* */
	{
		LOAD_SMSTR((CL_FORM *)&Kuse_package1[0], ARG(4));	/* can't use ~S */
		COPY(INDIRECT(ARG(2)), ARG(5));
		Ferror(ARG(4), 2);
	}
	COPY(INDIRECT(ARG(2)), ARG(4));
	COPY(INDIRECT(ARG(1)), ARG(5));
	LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
	rt_struct_typep(ARG(5));
	if(CL_TRUEP(ARG(5)))
	{
		COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(1)))), 5 + 1), ARG(5));
	}
	else
	{
		COPY(SYMVAL(Slisp, 352), ARG(5));	/* NO_STRUCT */
		COPY(INDIRECT(ARG(1)), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
		Ferror(ARG(5), 3);
	}
	COPY(ARG(4), ARG(6));
	COPY(ARG(5), ARG(7));
	LOAD_NIL(ARG(8));
	LOAD_NIL(ARG(9));
	LOAD_NIL(ARG(10));
	member1(ARG(6));
	if(CL_TRUEP(ARG(6)))
	{
	}
	else
	{
		GEN_CLOSURE(array, ARG(4), 5, Z51_lambda, 1);
		COPY(ARG(2), &array[3]);
		COPY(ARG(1), &array[4]);
		LOAD_CLOSURE(array, ARG(4));
		COPY(ARG(4), ARG(4));
		COPY(INDIRECT(ARG(2)), ARG(5));
		rt_do_external_symbols_iterator(ARG(4));
		COPY(INDIRECT(ARG(1)), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		rt_struct_typep(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(1)))), 5 + 1), ARG(5));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(5));	/* NO_STRUCT */
			COPY(INDIRECT(ARG(1)), ARG(6));
			LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
			Ferror(ARG(5), 3);
		}
		ALLOC_CONS(ARG(6), INDIRECT(ARG(2)), ARG(5), ARG(4));
		LOAD_FIXNUM(ARG(5), 5, ARG(5));
		COPY(INDIRECT(ARG(1)), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
		rt_struct_typep(ARG(6));
		if(CL_TRUEP(ARG(6)))
		{
			COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(1)))), 5 + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
			COPY(INDIRECT(ARG(1)), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(8));	/* PACKAGE */
			Ferror(ARG(6), 3);
		}
		COPY(INDIRECT(ARG(2)), ARG(5));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
		rt_struct_typep(ARG(5));
		if(CL_TRUEP(ARG(5)))
		{
			COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(2)))), 6 + 1), ARG(5));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(5));	/* NO_STRUCT */
			COPY(INDIRECT(ARG(2)), ARG(6));
			LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
			Ferror(ARG(5), 3);
		}
		ALLOC_CONS(ARG(6), INDIRECT(ARG(1)), ARG(5), ARG(4));
		LOAD_FIXNUM(ARG(5), 6, ARG(5));
		COPY(INDIRECT(ARG(2)), ARG(6));
		LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(7));	/* PACKAGE */
		rt_struct_typep(ARG(6));
		if(CL_TRUEP(ARG(6)))
		{
			COPY(ARG(4), OFFSET(AR_BASE(GET_FORM(INDIRECT(ARG(2)))), 6 + 1));
		}
		else
		{
			COPY(SYMVAL(Slisp, 352), ARG(6));	/* NO_STRUCT */
			COPY(INDIRECT(ARG(2)), ARG(7));
			LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(8));	/* PACKAGE */
			Ferror(ARG(6), 3);
		}
	}
	COPY(ARG(3), ARG(4));
	COPY(GET_CDR(ARG(4)), ARG(3));
	goto M1_1;
	RETURN1:;
	LOAD_SYMBOL(SYMBOL(Slisp, 48), ARG(0));	/* T */
}

static void Z51_lambda(CL_FORM *base)
{
	if(CL_SYMBOLP(ARG(1)))
	{
		LOAD_SMSTR(SYM_NAME(ARG(1)), ARG(2));
	}
	else
	{
		if(CL_TRUEP(ARG(1)))
		{
			COPY(SYMVAL(Slisp, 676), ARG(2));	/* SYM_EXPECTED */
			COPY(ARG(1), ARG(3));
			Ferror(ARG(2), 2);
		}
		else
		{
			LOAD_SMSTR((CL_FORM *)&KClisp[266], ARG(2));	/* NIL */
		}
	}
	COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(3));
	find_symbol1(ARG(2));
	COPY(&mv_buf[0], ARG(3));
	{
		int nargs;
		nargs = 2;
		mv_count = 1;
		{
			switch(nargs)
			{
				case 0:
				LOAD_NIL(ARG(2));
				case 1:
				LOAD_NIL(ARG(3));
				nargs = 2;
			}
			if(CL_TRUEP(ARG(3)))
			{
				if(EQ(ARG(1), ARG(2)))
				{
					goto ELSE1;
				}
				else
				{
					COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(4));
					LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(5));	/* PACKAGE */
					rt_struct_typep(ARG(4));
					if(CL_TRUEP(ARG(4)))
					{
						COPY(OFFSET(AR_BASE(GET_FORM(INDIRECT(GET_FORM(ARG(0)) + 4))), 4 + 1), ARG(4));
					}
					else
					{
						COPY(SYMVAL(Slisp, 352), ARG(4));	/* NO_STRUCT */
						COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(5));
						LOAD_SYMBOL(SYMBOL(Slisp, 354), ARG(6));	/* PACKAGE */
						Ferror(ARG(4), 3);
					}
					COPY(ARG(2), ARG(5));
					COPY(ARG(4), ARG(6));
					LOAD_NIL(ARG(7));
					LOAD_NIL(ARG(8));
					LOAD_NIL(ARG(9));
					member1(ARG(5));
					COPY(ARG(5), ARG(4));
					if(CL_TRUEP(ARG(4)))
					{
						goto ELSE1;
					}
					else
					{
						goto THEN2;
					}
				}
			}
			else
			{
				goto ELSE1;
			}
			{
				THEN2:;
				LOAD_SMSTR((CL_FORM *)&Kuse_package1[2], ARG(4));	/* ~S in ~S conflicts with ~S in ~S */
				COPY(ARG(2), ARG(5));
				COPY(INDIRECT(GET_FORM(ARG(0)) + 4), ARG(6));
				COPY(ARG(1), ARG(7));
				COPY(INDIRECT(GET_FORM(ARG(0)) + 3), ARG(8));
				Ferror(ARG(4), 5);
			}
			ELSE1:;
		}
	}
	LOAD_NIL(ARG(0));
}
